### ISSUE TITLE
Get part of Matrix fails when used in user defined function

### ISSUE THREAD

**Issue by LloydLS** [josdejong/mathjs#1024]
Version: "3.20.1"

*Description:* Passing a matrix as an argument in a custom function returns an error message, whereas the same custom function works if the matrix is defined previously as a global variable.

*Broken example:* Feed in matrix through the function:
```
calcVal(b) = b[1, range(1, size(b)[2] )]
calcVal( [[1,2,3,4],[5,6,7,8]] ) // Returns: IndexError: Index out of range (2 > 0)
// should return: [[1, 2, 3, 4]]
```

*Working example:* Define matrix variable first:
```
b = [[1,2,3,4],[5,6,7,8]]
calcVal(b) = b[1, range(1, size(b)[2] )]
calcVal(b) // Returns: [[1, 2, 3, 4]]
```

(MathJS is awesome btw, thanks!)

**Comment by ThomasBrierley** [comment]
If size is replaced with an explicit array of indices `[1, 2, 3, 4]` it works. Something about invoking `size` inside a function seems to break the local reference `b`.

I suspect the working example only works because it's using the global reference instead.

**Comment by josdejong** [comment]
Thanks for bringing this up. This is indeed due to a conflict with an internally used variable `size`.

Funny thing is that this issue is solved in the new compiler I wrote last weekend, see https://github.com/josdejong/mathjs/issues/1019#issuecomment-359264526. The new compiler will be released in v4 (I expect to release a beta of v4 within a few weeks).

**Comment by josdejong** [comment]
This should be fixed now in v4, can you give that a try @LloydLS ?

**Comment by LloydLS** [comment]
Hi Jos,

Looks good, thanks!
