### ISSUE TITLE
default behavior of `format`

### ISSUE THREAD

**Issue by taoqf** [josdejong/mathjs#1031]
I am confused about `format`,  I checked the `formatNumber` and find the default `notation` is `auto`, I supposed the default behavior is `fixed`. 
https://github.com/josdejong/mathjs/blob/master/lib/utils/number.js#L130

**Comment by taoqf** [comment]
I think I get it. But I have another question: what's deffrent between
```js
format(2018.123, undefined)
```
and
```js
format(2018.123)
```
is this an issue?

**Comment by taoqf** [comment]
I expect if i pass an precision >=0 , use `fixed`, else use `auto`. by the way, the test
https://github.com/josdejong/mathjs/blob/master/test/function/string/format.test.js#L38 `1/3` confused me at the first time.

**Comment by josdejong** [comment]
The default notation for `math.format` is indeed `auto`, see also docs: http://mathjs.org/docs/reference/functions/format.html 

math.js is quite strict, therefore it will throw an error for `format(2018.123, undefined)`. If you pass that, you probably did not intend so (maybe you pass an `options` object that comes from somewhere else, but it is accidentally undefined instead of an object or something).

Defining `precision` or not will not change the applied `notation`, it's a separate setting. `precision` can be defined both when using `fixed` or `auto`. Please read the docs, I hope after that things will make sense :).

**Comment by taoqf** [comment]
All right. Thank you after all.

**Comment by josdejong** [comment]
:+1:
