### ISSUE TITLE
size() mismatch of 2D matrix generated using .map()

### ISSUE THREAD

**Issue by LloydLS** [josdejong/mathjs#1066]
Hi,

size() of 2d matrix returns array with two elements:
```
b = [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
size(b) // [3, 3]
```

whereas, size() of 2d matrix generated via .map() returns array with only one element:
```
b = [0,1,2].map( f(x,i,a)  = ones(3) ) // [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
size(b) // [3] 
```

Is this a bug, I expected them to be the same? Present in v4.0.1 and v3.x

Thanks,

**Comment by josdejong** [comment]
Ah, that's an interesting one. The result of the map is a 1d matrix containing 1d matrices, rather than a single 2d matrix. 

I have to think a bit about whether it would be logic/desirable/possible to turn the return values of a map into a multi-dimensional matrix in case there are arrays returned. This can get complicated very easily though. What to do with an input like `b = [0,1,2].map( f(x,i,a)  = ones(x) )` for example? In that case the returned arrays have different size.

**Comment by LloydLS** [comment]
Thanks Jos,

To give some context of what I'm using this for, I want to generate a set of x, y coordinates that I can pass into a function that will return z coordinates; example (a 3d Gaussian):

```
raw = range(0,4,1); // [0, 1, 2, 3, 4] (the basic coordinate range)
xData = raw.map( f(x,i,a)  = x = a ); // [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
yData = raw.map( f(x,i,a)  = zeros(size(a)[1]) + i[1] );  // [[0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3], [4, 4, 4, 4, 4]]

 gaussian3d(x, y, centre, width, height) = (height / ( 2 * pi * square(width) ) ) * ( dotDivide(  -1 * (square(x - centre)  + square(y - centre)),  (2 * square(width)) ) ).map( f(q,i,a) = exp(q)    );  

zData = gaussian3d(xData, yData, 2, 0.5, 7) ; // returns z coords in [[]] matrix
```

Thanks again!

**Comment by josdejong** [comment]
I think the underlying issue here is that the expression parser does not support scripting (like for loops), and you're really operating on the edge of what you can do with single line functions/expressions. It would be great to extend the expression parser of course but that will not be overnight. 

I think a neat workaround to solve the original issue of having a matix containing matrixes is:

```
b = [0,1,2].map( f(x,i,a)  = ones(3) )
size(b)  # [3] because b is a 1d matrix containing three 1d matrices
c = matrix(b.toArray())
size(c)  # [3,3]  now c is a two dimensional matrix
```

It could also help to create some helper functions in JavaScript and import them in mathjs to work around the limitations of the expression parser, like some sort of "repeat" function to create your xData and yData.

**Comment by LloydLS** [comment]
Thanks Jos, that works well!

**Comment by josdejong** [comment]
:+1:
