### ISSUE TITLE
Failing since updating this package from 4.1.1 to 4.2.2

### ISSUE THREAD

**Issue by SimonSimCity** [josdejong/mathjs#1101]
Today I've updated my package to MathJS `v4.2.2` and found this error when trying to start it:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/projects/test/node_modules/mathjs/dist/math.js:38:4)
```

I can confirm that it worked with MathJS `v4.1.1` so I'm for now switching back to it ...

Don't know how much it has to say, but I'm using your library in a Meteor project.

**Comment by josdejong** [comment]
Thanks for reporting @SimonSimCity . 

I think this could be related to changed behavior in webpack, which was upgraded from `v3.3.11` to `v4.6.0` in mathjs@4.2.0 (see [history](https://github.com/josdejong/mathjs/blob/master/HISTORY.md#2018-05-02-version-420), see [commit](https://github.com/josdejong/mathjs/commit/68b5e3ffe6e24472f6e1b04e66c219fa04451adb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)). Haven't looked into it yet.

**Comment by josdejong** [comment]
@SimonSimCity how can I reproduce this issue? Do you have some minimalist setup/demo which replicates the issue?

**Comment by jackschmidt** [comment]
I found two reproducers.

In node, if I do `math=require('mathjs/dist/math.js')` then I get this error. However, if I do the more reasonable `math=require('mathjs')` everything is fine.

In a browser, if I do `importScript('https://cdnjs.cloudflare.com/ajax/libs/mathjs/4.2.2/math.min.js')` from within a Web Worker, I also get the error. (So create a short js file `worker.js` with that line in it, then from within the browser call `new Worker('worker.js')` to get the error.)

It does seem like `dist/math.js` has a misnamed "universalModuleDefinition" since it doesn't work in workers or node.

**Comment by josdejong** [comment]
This seems to be an issue in webpack 4, see https://github.com/webpack/webpack/issues/6642

I've solved it by adding `globalObject: 'this'` to the webpack config, and the bundle seems to work fine now in the browser, WebWorkers, and node.js. 

@jackschmidt would be great if you can verify whether this issue is solved in mathjs `v4.3.0`.

**Comment by jackschmidt** [comment]
Looks good in browser, web workers, and node when installed from npm (and unpkg, jsdelivr for browser and workers).

**Comment by josdejong** [comment]
:+1: thanks for the fast feedback.

**Comment by SimonSimCity** [comment]
Sorry for the very belayed response ... I too can confirm it works again with the latest version 🎉
