### ISSUE TITLE
In-place operations

### ISSUE THREAD

**Issue by torfsen** [josdejong/mathjs#1134]
Currently, if I want to add a vector `y` to an existing vector `x` and store the result in `x` I need to do
```
x = math.add(x, y);
```
This means that new storage has to be allocated to hold the result of the addition. I'd like to avoid that.

I suggest in-place variants of those operations where it makes sense, e.g. `math.iadd`:
```
math.iadd(x, y); // Add y to x in-place, no return value
```

From an implementation point of view, `add(x, y)` could easily be implemented via `iadd` by something like

```
function add(x, y) {
  let result = math.clone(x);
  result.iadd(y);
  return result;
}
```

Almost all arithmetic, bitwise, complex, logical, trigonometry and some of the matrix and set functions could benefit from an in-place variant.

**Comment by josdejong** [comment]
In general, I strongly prefer immutable objects and pure functions. Your proposal is exactly the opposite of that, so there must be a really good reason for it.

For matrices, reuse may seriously improve performance, which can be a valid reason. We should validate whether this is indeed the case though, and get to know how much we could gain.

From a practical point of view: it would require a _huge_ amount of refactoring, we should keep that in mind.

**Comment by josdejong** [comment]
Yeah, first we should do a benchmark to see how many impact it would have.

@torfsen how does numpy do this? Does numpy have such functions?

Just thinking aloud: maybe we could consider `iadd` like functions only for specific operations instead of for "all "functions. I'm thinking about the operators `+=`, `-=`, `*=`, and `/=`.  These are operations I regularly use in loops to do cumulatives and things like that. We could implement these operators in the expression parser, and have them powered by ``iadd`, `isubtract`, `imultiply`, and `idivide`.

An other direction is that we could have such functions as methods on the Matrix class but not as pure functions, i.e. methods can be mutable but functions not. There are already immutable methods on Matrix like `.set(...)` and `.resize(...)`.

**Comment by harrysarson** [comment]
I believe a much greater improvement to performance would come from using something like numpy's ndarray to store vectors and matrices rather than javscript arrays and therefore that should be a priority.

Additionally, I would argue for more meaningful method names such as `matrix.inplaceAdd` or `matrix.modifyAdd` or even `matrix.withMutation.add`

**Comment by harrysarson** [comment]
See #760

**Comment by Nekomajin42** [comment]
Please don't forget the `%=`!

And what do you think about the `++` and `--` operators?

**Comment by josdejong** [comment]
@harrysarson  good point. we should really first put these ideas for improvement in perspective. See also the [`benchmark` folder](https://github.com/josdejong/mathjs/tree/master/benchmark), where for example the performance of the JavaScript library [`ndarray`](https://www.npmjs.com/package/ndarray) (using `Float64Array`) against other libraries like `numericjs` which is amazingly fast but uses nested JavaScript arrays.

**Comment by gwhitney** [comment]
Going to reference this in the "future of matrices" discussion #2702 so closing it.
