### ISSUE TITLE
Math.rationalize won't simplify xy-yx

### ISSUE THREAD

**Issue by sahi1l** [josdejong/mathjs#1179]
This is either a bug or an annoying inconsistency.   
`math.rationalize("x*y+y*x").toString()` returns `2*x*y`, 
but `math.rationalize("x*y-y*x").toString()` returns `x*y-y*x` and not zero.

**Comment by josdejong** [comment]
Thanks for reporting. This simplification is done by `math.simplify`, which is used by `math.rationalize`, I think we'll have to address this in `math.simplify`, I will change the title of this issue accordingly.

Sounds like we could improve `simplify` with a rule to simplify this too. @firepick1 and @paulobuchsbaum do you think this is easy to add, or is there some complications because of the subtraction?

**Comment by sahi1l** [comment]
It may help to "alphabetize" symbols that are multiplied together, to have some sort of canonical form: turn "c*a*b" into "a*b*c".

**Comment by josdejong** [comment]
Yes I think you're right @sahi1l , since when I run `math.simplify('x*y-x*y')`, the output is `0`.

**Comment by josdejong** [comment]
hm you may be right that it's not that easy. Taking into account variables with exponents is a whole different story I agree. But right now the expected behavior of collecting terms already works, only the ordering is missing. Sounds like we need a rule which checks whether we have a multiplication of two (or more?) symbols and if so, order them alphabetically.

**Comment by sahi1l** [comment]
"Alphabetize" doesn't have to be literal, of course; so long as you have a function that converts nodes into something sortable (like a string or a number), that will work.  So for instance, in x^2*y^3*(z-3), you can sort the strings "x^2", "y^3", and "(z-3)" alphabetically.  I guess it's tricky when you have three or more factors, because of the tree structure (* (^ x 2) (* (^ y 3) (- z 3)).  [Pardon the LISP, I don't know how else to represent the tree.]  I suppose it would be difficult to make multiplication an operator that can take a variable number of arguments, like (* (^ x 2) (^ y 3) (- z 3))?  Way easier to sort then.

**Comment by josdejong** [comment]
> "Alphabetize" doesn't have to be literal, of course;

yeah, and currently collecting terms already works for `+` so such a mechanism is already in place.

**Comment by firepick1** [comment]
[String.localeCompare()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare)

**Comment by gwhitney** [comment]
I don't actually think any alphabetization is required, as the rule-matching engine now tries many orderings of the terms. I think the difficulty is that it doesn't try all possible associations of the terms, and hence it is more able to find common subterms on the left; but the rule for collecting terms was written to find matches on the right. See the PR referenced above for detail.

**Comment by josdejong** [comment]
Makes sense, if the matching engine tries out all combinations, ordering is not needed (unless for performance reasons or so)

**Comment by josdejong** [comment]
Fixed in `v10.1.0`, see #2484.
