### ISSUE TITLE
feature: add axis for sum() 

### ISSUE THREAD

**Issue by alvinhui** [josdejong/mathjs#1244]
## Function declaration

```
sum(matrix: Matrix, axis: number): number|Matrix;
```

## Examples

default:

```javascript
math.sum([[2, 5, 8], [4, 3, 2], [1, 7, 0]]) 
// 32
```

`axis=0`:

```javascript
math.sum([[2, 5, 8], [4, 3, 2], [1, 7, 0]], 0) 
// [ 7, 15, 10]
```

`axis=1`:

```javascript
math.sum([[2, 5, 8], [4, 3, 2], [1, 7, 0]], 1) 
// [15,  9,  8]
```

**Comment by alvinhui** [comment]
I think `sum` is not necessary to support multiple parameters.

like `math.sum([[2,4]], [4, 5])` can replace to `math.add([[2, 4]], [4, 5])`

**Comment by josdejong** [comment]
Interesting idea @alvinhui , thanks.

This would be similar to how `concat` works, this function also has an optional last argument `dim`: http://mathjs.org/docs/reference/functions/concat.html

**Comment by alvinhui** [comment]
@josdejong This feature may extend to other methods, such as `math.ver`

**Comment by josdejong** [comment]
Thanks for your offer @bnlcas , that would be great. The list with functions seems complete though in mathjs we don't have functions `cumsum` and `diff` (unless you create these too ;)), so that would leave:

```
mean, std, var, sum, prod, max, min
```

What is the exact API that you're envisioning for this new functionality? 

One point we have to think about is how to change `sum` to support an input like `sum(matrix, axis)`, I think this will conflict with the current support for input like `sum(1,2,3)`.

**Comment by bnlcas** [comment]
Cool. Let me look into adding cumsum and diff after patching the existing functions. Mean Max and Min already have this feature, so that leaves sum, var, prod and std. I think it would be simplest to start with sum and move on to the other features.

To add this functionality to sum I basically just copied the architecture used in mean(). Mean handles mean(1,2,3) using the typed function interface so mean(num,num,num) is handled differently than mean(mat,num).

```  
  const sum = typed('sum', {
    // sum([a, b, c, d, ...])
    'Array | Matrix': _sum,

    // sum([a, b, c, d, ...], dim)
    'Array | Matrix, number | BigNumber': _nsumDim,

    // sum(a, b, c, d, ...)
    '...': function (args) {
      if (containsCollections(args)) {
        throw new TypeError('Scalar values expected in function sum')
      }

      return _sum(args)
    }
  })
```

``` 
  function _nsumDim (array, dim) {
    try {
      const sum = reduce(array, dim, add)
      return sum
    } catch (err) {
      throw improveErrorMessage(err, 'sum')
    }
  }
```

This is passing the unit tests for sum.test.js (with the exception that I changed the unit test that throws are error for math.sum(matrix, dim) to check the values).

I'll submit a PR for this feature, you can take a look to see that this fits with the rest of the codebase.
