### ISSUE TITLE
can't compare "undefined" with something using greater/smaller operators

### ISSUE THREAD

**Issue by AnastasiaArtyom** [josdejong/mathjs#1245]
I tried doing something like this:
undefined < 1
and expected to get "false" result, but something went wrong:
![image](https://user-images.githubusercontent.com/17142125/45479943-7bf94300-b750-11e8-98fc-9dce1c94ecf9.png)

**Comment by harrysarson** [comment]
Hi @AnastasiaArtyom, thanks for the report.

I believe mathjs used to allow these comparisons but they confused users and lead to some tricky bugs. I think there might be a better way here, if you want to share your use case I would be happy to see if I can help.

**Comment by josdejong** [comment]
Harry you're right we've changed the behavior of undefined and null not so long ago because it lead to confusing situations.

@AnastasiaArtyom In general, if some value is `undefined`, then there is something wrong, and you need to fix that first. Can you explain why you need `smaller` to support undefined? Why are there `undefined` values in your calculations?

**Comment by AnastasiaArtyom** [comment]
I face with this problem when try evaluating this expression:
`a <= b or c <= d`
where `a, b, c` are numbers(e.g `a = b = c = 0`), but `d` is `undefined`. I expect the result to be `true`.
This `undefined` value happens because of this: e.g `a ` and `c` are some constants and somewhere I have 2 branches. e.g:
```
if (some_condition) {
    b = some_number
} else {
    d = some_number
}
```
how can i resolve this case? because theoretically it can be evaluated.
And in general. if I have something like this:
`typeof(d) != undefined and d < 5`
why should it lead to this error?
It's correct. If `d` is `undefined` the second part will never be executed. why i can get only the error or `true` result?

**Comment by harrysarson** [comment]
If you want a quick work around you should initialise both `b` and `d` to `-Infinity`.

However, in my opinion having `undefined`s floating will lead to much grief for you in the long run.
`mathjs` throws errors when `undefined` appears in a comparison in order to alert users that something has gone wrong. I would try to refactor your code to remove the uses of `undefined` but it is of course up to you 😏

**Comment by AnastasiaArtyom** [comment]
how can I automate this? if i have 2 expressions with `d`:
```
d <=a
...
d >=b
```
and `d` may be not defined. I can't replace it everywhere with `-Infinity` or `Infinity` because it can result in wrong result. Is there a constant that  guarantees a safe execution and the correct result?

**Comment by josdejong** [comment]
Will close this issue because of inactivity. Feel free to reopen if needed.
