### ISSUE TITLE
mathjs get wrong answer of expression (4349^5249) % 7031 

### ISSUE THREAD

**Issue by youth7** [josdejong/mathjs#1258]
the right answer should be `1234` , but _mathjs_ return `512`，here is my demo
```js
const math = require("mathjs")
math.config({
    number: "BigNumber",  
    precision: 200 
});
console.log(math.format(math.eval("(4349^5249) % 7031")))
```

**Comment by josdejong** [comment]
Your expression first calculates `4349^5249` and then calculates the modulus of that result. 

According to [wolfram alpha](http://www.wolframalpha.com/input/?i=4349%5E5249) the result of `4349^5249` is a value with 19098 digits. This means that your `precision: 200` is not sufficient. Setting `precision: 20000` instead is too slow to be practical I'm afraid.

**Comment by youth7** [comment]
> 
> 
> Your expression first calculates `4349^5249` and then calculates the modulus of that result.
> 
> According to [wolfram alpha](http://www.wolframalpha.com/input/?i=4349%5E5249) the result of `4349^5249` is a value with 19098 digits. This means that your `precision: 200` is not sufficient. Setting `precision: 20000` instead is too slow to be practical I'm afraid.

got it , I will close this issue soon . Don't konw how mathjs calcuate `4349^5249`, but python just take less than 1 second to get the right result(I have try this in command line like this : `pow(4349, 5249)`) . Hope you can improve this later.

**Comment by josdejong** [comment]
Indeed! Python has a long integer data type that makes this possible.

I was just checking out: Chrome also supports a BigInt data type since shortly (other browsers still have to follow), and it indeed supports your expression (`**` is the power operator), thy the following in your Chrome developer console (execution takes about 1 ms):

```
4349n ** 5249n
```
Will be interesting to add support for BigInt to mathjs!

**Comment by josdejong** [comment]
See #1096
