### ISSUE TITLE
How to get "-1/2" to be parsed to -\frac{1}{2} instead of \frac{-1}{2} ?

### ISSUE THREAD

**Issue by nioate** [josdejong/mathjs#1271]
Hi,
the code `math.parse("-1/2").toTex()` results in `\frac{-1}{2}`, i.e. {-1}/2, but I would like to obtain `-\frac{1}{2}`, i.e. -{1/2}. Looking at the expression tree, the "error" occurs in `math.parse()`, not in `.toTex()`
Is this behaviour intended? If so, is there any way to easily change it by some configuration? 

Of course I might change the expression to `math.parse("-(1/2)")`, but then the result contains the parentheses as well, which I would like to avoid.

Thanks!

**Comment by josdejong** [comment]
In the expression parser of mathjs, unary minus has a [higher precedence](http://mathjs.org/docs/expressions/syntax.html#precedence) than division. So `-1/2` is interpreted as `((-1)/2)`. You cannot change this precedence, and maybe you should not want to because this can lead to nasty issues. What you could do is write a custom handler for `toTex` (see docs: http://mathjs.org/docs/expressions/customization.html#handler) or try to do something with a regexp to change the output.

**Comment by josdejong** [comment]
Or, probably not practical, build an expression tree by hand:

```js
const tree  = new math.expression.node.OperatorNode('-', 'unaryMinus', [
  new math.expression.node.OperatorNode('/', 'divide', [
    new math.expression.node.ConstantNode(1), 
    new math.expression.node.ConstantNode(2)
  ])
])

console.log(tree.toTex()) // "-\frac{1}{2}"
```
