### ISSUE TITLE
simplify(string) doesn't combine disordered same degree polynomial elements

### ISSUE THREAD

**Issue by makrasnov100** [josdejong/mathjs#1290]
**Description:**
There seems to be a problem with mathjs not recognizing which terms it can combine into one during the simplify operation. This may be a problem with the math.string() not with math.simplify(). The test seems to fail when elements of a polynomial are not ordered by their degree and also have the same coefficients.

**Version:** mathjs  5.2.0 (production)

**Reproduction Steps:**
1. Go here http://mathnotepad.com/
2. Enter the following `string(simplify("5 + (5 * x) - (3 * x) + 2"))`
3. You will see the inccorect output
Output: `"5 * (x + 1) - 3 * x + 2"` but Expected: `"2 x + 7"`

OR

Download and Run Jest Test Suit "math.simplify.test.js" by following the ReadMe included
[code.zip](https://github.com/josdejong/mathjs/files/2509458/code.zip)

Note that thesame input without equation parentheses results in thesame output:
`"string(simplify("5 + 5 * x - 3 * x + 2"))"` --> `"5 * (x + 1) - 3 * x + 2"`
However changing the elements to being sorted by degrees results in the correct output
`"string(simplify("5 + 2 + 5 * x - 3 * x"))"` --> `"2 x + 7"`

**Severity:** 3 (1-crash 4-trivial)
**Priority** 3 (1-blocking 4-few people care)

**Enviroment:** 
Node.js (8.12.0 LTS) 
OR 
Latest (10/24/2018) Chrome Browser at http://mathnotepad.com/

Results Report:
<img width="434" alt="resultsreport" src="https://user-images.githubusercontent.com/32151128/47415741-0dcd7600-d729-11e8-82a9-2a24e10b7d8a.png">

**Comment by ericman314** [comment]
Thanks for the detailed bug report.

`simplify` has come a long way since its first implementation through huge efforts by many people. It is an iterative pattern matcher, so it finds patterns in an expression and replaces them in an attempt to make the expression simpler. In doing this there can be multiple patterns that match an expression, and replacing the patterns in a different order can result in the algorithm taking different paths, and getting "stuck" at what it thinks is the simplest but is actually not.

There are multiple ways to simplify an expression. Sometimes, factoring produces the simplest expression, and other times, expanding an expression does. Sometimes it's unclear which is simpler, like `a ^ 2 - b ^ 2` versus `(a + b) * (a - b)`.

It's been a long time since I've contributed to `simplify`, so I'm not familiar with all the enhancements made recently. But it does have some capability to factor an expression. Modifying your original expression a little:

```js
math.simplify("(5 * x) - (3 * x) + 2")
// 2 * (x + 1)
```

The problem is, if part of an expression gets factored, that could prevent combining like terms from other parts of the expression. I think this might be what is happening to `5 + 5 * x - 3 * x + 2`. The first part is factored into `5 * (x + 1)`, but then the `3 * x` can no longer be combined.

My apologies if this has already been implemented in `simplify`, but what I would suggest is a multi-step approach to simplifying polynomials:

1. Apply a limited set of `simplify` rules, to get rid of things like `* 1` or `+ 0`
2. Expand polynomials, order and combine like terms, and combine fractions (using @paulobuchsbaum's excellent `rationalize` function, for example)
3. Factor, if desired

The pattern matching method is powerful, but there might be more efficient, algorithmic ways to simplify polynomials.
 
For reference here are a few relevant issues:

#890
#920 
#926
#1179

**Comment by gwhitney** [comment]
I agree with the comments above, and I believe the best way around this particular issue as a result is to prioritize the collection of nonconstant terms over the collection of like constants. For details see the PR referenced above.

**Comment by josdejong** [comment]
Fixed in `v10.1.0`, see #2484.
