### ISSUE TITLE
Derived units (e.g. 1m/1s =1m/s) 

### ISSUE THREAD

**Issue by oskbor** [josdejong/mathjs#13]
Hi,
I must say I am really impressed by this library! I toyed around a bit with the parser and one thing that I thought would be very powerful was if different units could be calculated. e.g. 

    a = 1s
    b= 1m
    c = b/a (currently throws an error but would be cool if it could return 1 m/s)

Is this something you plan on supporting? If you could provide some guidelines on how this could be implemented I could give it a try (not super skilled in javascript but stubborn ;) )

**Comment by mikberg** [comment]
[js-quantities](https://github.com/gentooboontoo/js-quantities) has this functionality.

IMO, I wouldn't worry too much about simplification, e.g. from `kg*m*s^-2` to `N` in the first run, this has value without that functionality. Conversions like `(4 min + 30 sec)/km to mile/min` are awesome.

**Comment by ericman314** [comment]
Once upon a time I wrote a C# app that did expression parsing with derived units, which I now use almost every day for engineering calculations. Now I'm looking to migrate it to JS as part of a larger web application, but this library looks like a much better jumping off point. I think your idea of storing lists of units with powers will work. I wonder if it would be necessary to redefine <code>N</code> and <code>lbf</code> and the others as a list of units, as you have proposed, rather than atomic entities? For example, <code>N</code> is defined as <code>1 kg * m * s^-2</code>. 

As far as displaying the Unit in a pretty format--that's a tricky problem I never figured out. There's no way for the algorithm to know whether the user wants to see <code>5 m^2/s^2</code> or <code>5 J/kg</code>. However, the code could provide the user with a list of built-in or user-defined units (or units the user has recently used) that are dimensionally consistent with the result. A web developer could use this list, for example, to populate a drop-down list allowing a user to convert the result to different units.

I would like to help, but I've never contributed to a GitHub project before.

**Comment by josdejong** [comment]
@ericman314 thanks for your offer, would be great if you could work on this. The handiest way is to clone the github project to your own account, create a new feature branch there to work on this new feature, and once you've made a start you can make a pull request (PR) to the `develop` branch of mathjs so we can discuss and/or evaluate your approach.

**Comment by ericman314** [comment]
OK, I submitted a pull request. Still needs more work, but I'm eager to see whether you think it's going the right direction.

**Comment by josdejong** [comment]
I will close this issue since we now have support for derived units thanks to @ericman314  :)
