### ISSUE TITLE
The issues of statement

### ISSUE THREAD

**Issue by chaositao** [josdejong/mathjs#1326]
At math.js, the 55908 line of vesion 5.2.3.
'string, Object |Â Array, number | Object': _print
What is the 'Â Array'?
when I use '$.extend(true,{}, {boxed:true}, options)' ,it's has a error!

**Comment by josdejong** [comment]
Thanks for reporting @chaositao . Turns out there was a non-breaking space and an other non-ascii character in the source code of the file `print.js`. 

I've written a small script to check for non-ascii characters in all source code. You can run this using `npm run validate:ascii`. The only issue was in print.js. There are other files containing extended-ascii characters but only in the comments, I don't think that will lead to errors. 

Before fixing print.js it looked like this:

![image](https://user-images.githubusercontent.com/568626/48800266-9845cd00-ed09-11e8-9738-2d65d6a3f575.png)
