### ISSUE TITLE
Feature request: Calculate combination with repetition

### ISSUE THREAD

**Issue by aneilbaboo** [josdejong/mathjs#1329]
It would be nice to have a combination function allowing repeating elements:

I.e., this:

<img src="https://latex.codecogs.com/gif.latex?\frac{(r&space;&plus;&space;n&space;-&space;1)!}{r!(n-1)!}" title="\frac{(r + n - 1)!}{r!(n-1)!}" />

**EDIT**: Thanks @waseemyusuf for catch my typo.

**Comment by josdejong** [comment]
Sounds good. Anyone interested in implementing a new function for this? We already have function `factorial`, `permutations` and `combinations` and I guess this would be a nice addition.

**Comment by waseemyusuf** [comment]
@josdejong, hey, I have been working on implementing a function for combinations with replacement and I am pretty much done with this task. A few points to note before I make a pull request:

### Naming:
I named this function `multicombinations()` because `combinationsWithRepitition()` is too long. Do you have any other suggestions or does `multicombinations` sound good?

### Edge Case:
What should `multicombinations(0, 0)` return? I think it should be 1. However, I am having it throw an error instead, because:

<a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\textup{multicombinations(n,&space;r)}&space;:=&space;\binom{r&plus;n-1}{r}&space;=&space;\binom{-1}{&space;0}&space;\textup{,&space;if&space;n&space;=&space;0,&space;r&space;=&space;0}" target="_blank"><img src="https://latex.codecogs.com/png.latex?\inline&space;\textup{multicombinations(n,&space;r)}&space;:=&space;\binom{r&plus;n-1}{r}&space;=&space;\binom{-1}{&space;0}&space;\textup{,&space;if&space;n&space;=&space;0,&space;r&space;=&space;0}" title="\textup{multicombinations(n, r)} := \binom{r+n-1}{r} = \binom{-1}{ 0} \textup{, if n = 0, r = 0}" /></a>
* `multicombinations(n, r)` is equivalent to `combinations(r+n-1, r)`
* so, `multicombinations(0, 0)`, then, must be equal to `combinations(-1, 0)`

My concern here is that this would imply working with a negative factorial! Note that without my explicit error handling for this case, my code would trivially return `1` for `n = 0, r = 0`, without needing to change the general case, so that's pretty neat. What do you suggest I do here? Throw error, or return 1?

### For the record:
I am pretty sure @aneilbaboo has made a typo in his equation. The correct formula should be `(r + n - 1)! / r!(n - 1)!`.

**Comment by aneilbaboo** [comment]
Ugh. You're right @waseemyusuf. 🤦‍♂️

(corrected)

**Comment by josdejong** [comment]
Thanks for picking this up @waseemyusuf ! 

It makes sense to me to throw an error for `multicombinations(0, 0)`, and also with negative inputs.

Qua: naming I strongly favor a clear name over a short one. In mathematics the phrase "combinations with repetition" is really strong, so it would be good if this comes back in the name. If I google for "multi combinations" I'm not finding anything related to combinations with repetition. The full name `combinationsWithRep` is very long though. How about `combinationsWithRep` ? Just 2 characters longer than your proposal :wink: .

**Comment by waseemyusuf** [comment]
Yeah, `combinationsWithRep` makes clear sense. I'll change the name to that, and you can expect a PR in a few minutes.

**Comment by josdejong** [comment]
Cool, thanks!

**Comment by waseemyusuf** [comment]
@josdejong This issue can be closed now. The feature was added in PR #1588

**Comment by josdejong** [comment]
Yes, thanks. Will do so once released ok?

**Comment by waseemyusuf** [comment]
Oh, ok. 😅 I thought you forgot to close it.

**Comment by josdejong** [comment]
The new function `combinationsWithRep` is now available in `v6.1.0`. Thanks again Waseem!
