### ISSUE TITLE
plot(f(x)) doen't work

### ISSUE THREAD

**Issue by vespadj** [josdejong/mathjs#1388]
http://mathnotepad.com/
version 0.9.16

plot(f(x)) is blank in all browser and also in the default   formula:
```
f(x) = (sin(x) + cos(x/2)) * 5
plot(f(x), x^2-5)
```

in console appair: 
TypeError: "undefined is not a function"

`plot(something_not_declared) `
print a line y=x

From a screenshot in v.0.9.3 plot worked ok  see http://josdejong.com/projects/

**Comment by josdejong** [comment]
Thanks for reporting @vespadj , I can reproduce this issue. Will fix it asap.

**Comment by josdejong** [comment]
I found the cause, it's a combination of two things. Working on a solution.

**Comment by josdejong** [comment]
@vespadj this is fixed now in Math Notepad v0.9.17.

The cause was a combination of a bug in math.js which did not correctly map over all variables of a FunctionNode, and Math Notepad using a "smart" way to chain scopes with variables of all expressions together, which didn't work anymore in the latest versions of math.js. I replaced this "smart" solution with a dumb one, everything works again now :)
