### ISSUE TITLE
Subtle change in parsing of functions in 5.4.2

### ISSUE THREAD

**Issue by javazen** [josdejong/mathjs#1409]
One of the things my code does is to traverse a parse tree, looking for all the symbol names. I have been doing this by code like this:
```
    var names = [];
    node.traverse(function (node, path, parent) {
        if (node.type === 'SymbolNode') {
            if (names.indexOf(node.name) === -1) names.push(node.name);
        }
    });
```

This had always worked, but in 5.4.2 function names like 'sqrt' began appearing in the array of names, which is not what I want. I found a workaround but I don't know if it's the best thing:
```
    if (node.type === 'SymbolNode' && path !== 'fn')
```

Was this change intentional? If so, is the workaround I'm using sufficient?

Thanks!

**Comment by josdejong** [comment]
That's correct, there was a bug in the `traverse` function of `FunctionNode` which was causing it not to loop over the symbol or property that the function was pointing to, and this was fixed in v5.4.2. Sorry to hear that fixing this bug caused your code to break :(

So for example the expression `x + f(2)` should traverse over an operator node `+`, a symbol node `x`, a function node having symbol node `f`, and a constant node `2`. Before the bug was fixed, the function didn't loop over `f`.

See history: https://github.com/josdejong/mathjs/blob/develop/HISTORY.md#2019-01-25-version-542

**Comment by josdejong** [comment]
You can recognize whether a symbol is a direct function call by checking whether 
`parent.type === 'FunctionNode'`. For method invocations like `obj.foo(2)` that doesn't work but I don't know if that's relevant for you.

**Comment by chrisko** [comment]
>_This had always worked, but in 5.4.2 function names like 'sqrt' began appearing in the array of names, which is not what I want._

We'd been making the same assumption as you, @javazen, and our function names started popping up in much the same way! I was glad to find your report.

>_You can recognize whether a symbol is a direct function call by checking whether
`parent.type === 'FunctionNode'`._

Excluding those `(parent && parent.isFunctionNode)` cases did the trick, thanks @josdejong.

**Comment by harrysarson** [comment]
Obligatory XKCD:
![image](https://user-images.githubusercontent.com/16308754/52917092-30d6f380-32df-11e9-887c-fff377e1a571.png)

**Comment by josdejong** [comment]
:rofl: 

Yeah I don't like it but fixing a bug per definition changes existing behavior. Maybe I should have marked this fix as a major change instead.

Will close this topic now.
