### ISSUE TITLE
math.inv() doesn't signal "determinant is zero" on this input

### ISSUE THREAD

**Issue by CiccioTecchio** [josdejong/mathjs#1463]
If I want to calculate the inverse of this  matrix
```javascript
var A = [[1,2,3],[4,5,6],[7,8,9]];
print(math.det(A));
print(math.inv(A));
```
the result is
```javascript
0
[[6.4337137533864e+14, -1.2867427506773e+15, 6.4337137533864e+14],
[-1.2867427506773e+15, 2.5734855013546e+15, -1.2867427506773e+15],
[6.4337137533864e+14, -1.2867427506773e+15, 6.4337137533864e+14]]
```

**Comment by ericman314** [comment]
This is due to round-off error in the intermediate steps to calculate the inverse. The inverse function does check for singular matrices, but the check is for whether a certain intermediate value during the calculation is _exactly_ 0, which due to round-off error is not usually the case. So that check could perhaps be improved.
