### ISSUE TITLE
When rounding numbers, lowerExp is not always respected

### ISSUE THREAD

**Issue by jstafford** [josdejong/mathjs#1530]
This is a fairly minor nit picky bug, but we ran into it because we're making a UI that exposes format settings to the end user and this case turned up in testing. 

Consider the scenario where formatting options are:
notation = ‘auto’
precision = 1
lowerExp = -2

The format the following numbers 0.009, 0.0096, and 0.01
input: 0.009, output: 9e-3 as expected
input 0.0096, output 1e-2 but expected 0.01. This is the bug.
input 0.01, output 0.01 as expected

as sample code:
```
  const tests = [0.009, 0.0096, 0.01]
  for (const testNumber of tests) {
    const formattedNum = math.format(testNumber, {notation: 'auto', precision: 1, lowerExp: -2})
    console.log(`input: ${testNumber}, output: ${formattedNum}`)
  }
```

**Comment by josdejong** [comment]
Thanks for reporting Jason, that's an interesting case. It turned out the formatting function did _first_ apply the boundaries `lowerExp` and `upperExp`, and _after_ that did the rounding of the number. 

Fixed via: https://github.com/josdejong/mathjs/commit/f54599a7013f4623b30cf1f9ef9834d026c9204a, scheduled for v6.0.0.
