### ISSUE TITLE
expression loader

### ISSUE THREAD

**Issue by vankop** [josdejong/mathjs#1535]
Hi!

I didn't find webpack loader for mathjs expressions, so I decided to write it 😁 See https://github.com/vankop/mathjs-webpack-loader

It will be great, if you decided to official support it, or create your own.

Also I faced with problem, that I can't just use `mathjs.json.reviver` on root object, so I need to `revive` nodes recursively. It will be great to implement `revive` method for plain JSON as well as it does for `JSON.parse`.

**Comment by josdejong** [comment]
Thanks for sharing. I don't fully understand your loader, when and why would I need it?

Do you use the JSON recover the right way? It does work recursive, check out the docs for examples.

**Comment by vankop** [comment]
For example, html book splitted by chapters with N formulas in each chapter. So creating parsed expression on fly could be a bit expensive + there is no need to create N functions to compute formulas (writing code autogeneration for this will be overkill) + this code powered by webpack =) we can use code-splitting (creating one chunk on each chapter).

**Comment by josdejong** [comment]
Like in a static site or html generator? I'm still trying to grasp the use-case your loader. I sort of get it but it feels quite devious to solve something like this on the level of Webpack instead of having it handled by the site generator. It's probably me, but I also don't understand the examples: I would expect not having to load mathjs and call .compile and stuff like?

**Comment by vankop** [comment]
No, it is isomorphic app.

**Comment by josdejong** [comment]
:+1: thanks for sharing.
