### ISSUE TITLE
Calculating psuedoinverse of a matrix

### ISSUE THREAD

**Issue by Toso82** [josdejong/mathjs#1563]
It is possible to add function to create inverse of not square Matrix?

**Comment by ericman314** [comment]
Do you mean to invert each element of a non-square matrix? For that you can use `dotPow`:

```js
math.dotPow([[1, 2, 3], [4, 5, 6]], -1)
// returns [[1, 0.5, 0.33333333333333], [0.25, 0.2, 0.16666666666667]]
```

But ordinary matrix inversion is only possible for square matrices:
```js
math.inv([[1, 2], [3, 4]])  
// returns [[-2, 1], [1.5, -0.5]]
```

**Comment by Toso82** [comment]
@ericman314  I mean the possibility to calculate pseudo inverse  matrix for multy variable linear regression 

https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse

I know that inv it is only for square matrix.

**Comment by ericman314** [comment]
Oooooh, fascinating. Yes I suppose it is possible to add that feature. The following statement from the article you linked is ominous:

> Writing one's own implementation of SVD is a major programming project that requires a significant numerical expertise.

 The pseudoinverse is implemented in other packages as `pinv`. Perhaps we should study some of those implementations.

**Comment by Toso82** [comment]
Ok thanks, i think there is a good function to add so i can't use other library

**Comment by josdejong** [comment]
Sounds interesting. I love the warning Eric points too. Anyone interested in investigating what it would require to implement this in mathjs, to see if it's worth the effort?

**Comment by HanchaiN** [comment]
[QR decomposition](https://en.wikipedia.org/wiki/Moore–Penrose_inverse#The_QR_method) seems to be an alternative approach since it may require less complex implementation.
The existing [`math.qr`](https://mathjs.org/docs/reference/functions/qr.html), [`math.usolve`](https://mathjs.org/docs/reference/functions/usolve.html), and [`math.lsolve`](https://mathjs.org/docs/reference/functions/lsolve.html) can be used to implement the algorithm.
```js
function pinv(A) {  // Moore–Penrose inverse
    let {Q, R} = math.qr(A),  // QR decomposition
        RT = math.ctranspose(R),
        AT = math.ctranspose(A);
    return math.concat(...new Array(math.size(AT)[1]).fill(0)
        .map((_,i)=>math.column(AT, i))  // Compute the substitution on each columns seperately
        .map(AT_ => math.usolve(R, math.lsolve(RT, AT_))));  // Forward and Backward substitution
}
```
(This code is untested, don't expect much.)

Still, [(compact) singular value decomposition](https://en.wikipedia.org/wiki/Singular_value_decomposition) will be helpful to have in the library and can be more computationally "simple" and "accurate" (according to the Wikipedia, at least).

**Comment by gwhitney** [comment]
Either a working pinv or an svd implementation or both would be a welcome addition to mathjs; feel free to make a PR if you are able to.
