### ISSUE TITLE
mathjs.org compromised

### ISSUE THREAD

**Issue by drschwabe** [josdejong/mathjs#1571]
Noticed the Google Custom search on mathjs.org is returning all sorts of junk/spam results like from this page: 

http://pheghoode.mathjs.org/irbw-spore-1.html

just wanted to bring attention to this issue if it hasn't already been addressed

**Comment by josdejong** [comment]
That's weird, looks like there is some site on a subdomain of mathjs.org. Will look into it asap.

**Comment by josdejong** [comment]
Turns out it was a misconfiguration in the DNS for mathjs.org, a github-pages static site, which had a whildcard `*.mathjs.org` in the DNS. Github explicitely warns against this [in the docs](https://help.github.com/en/articles/setting-up-a-custom-subdomain):

> Danger: Do _not_ use wildcard DNS records (e.g. `*.example.com`) with GitHub Pages! A wildcard DNS record will allow _anyone_ to host a GitHub Pages site at one of _your_ subdomains.

The rogue subdomain is not available anymore as soon as the DNS is updated everywhere.

I've also contacted github about the misuse.
