### ISSUE TITLE
Configure DBL_EPSILON?

### ISSUE THREAD

**Issue by tonyxiao** [josdejong/mathjs#1614]
```ts
> math.equal(6.65 - 3.32 - 3.33, 0)
false
```
I'd like the result to be `true` and can't figure out a way to do that with math.js without my own hacks. What's the right way to do this?

**Comment by josdejong** [comment]
The way nearly equal is calculated is explained here in the docs:

https://mathjs.org/docs/datatypes/numbers.html#equality

comparing almost zero against amost zero is a special case. You can either make sure both sides are not close to zero, for example add 1 to both sides:

```js
math.equal(6.65 - 3.32 - 3.33 + 1, 0 + 1)
```

or you can look if BigNumbers solve your issue: https://mathjs.org/docs/datatypes/bignumbers.html

**Comment by gwhitney** [comment]
> ```ts
> > math.equal(6.65 - 3.32 - 3.33, 0)
> false
> ```
> 
> I'd like the result to be `true` and can't figure out a way to do that with math.js without my own hacks. What's the right way to do this?

Just as a general principle, whatever the technique for approximate comparison is, it's always better to do e.g. `equal(6.65, 3.32+3.33)` than `equal(6.65-3.32-3.33, 0)` because all information on the floating-point scale of the quantities you're trying to compare is lost in the second alternative. That said, `equal()` does have a special case for zero, it's just not possible to tune it to always work when you'd "want it to". See #2752 and #2788 for recent efforts to address these aspects in a systematic/configurable way.
