### ISSUE TITLE
[Question] Individual Imports

### ISSUE THREAD

**Issue by Ericky14** [josdejong/mathjs#1752]
Is there any way to do individual imports on this package? I only use `intersect`, and it seems the bundle size of this package is quite large.

**Comment by josdejong** [comment]
Most functions of mathjs support multiple data types (number, BigNumber, Unit, Matrix, etc.), and so if you pick just a single function you will still get all these data types bundled along. 

Since v6.0.0 we do have number-only implementations for quite some functions (not yet for `intersect` I'm afraid), so you have a light weight solution if you don't need all these data types.

You can read more about it here: https://mathjs.org/docs/custom_bundling.html

Does that help?

**Comment by Ericky14** [comment]
Yes, thank you
