### ISSUE TITLE
Engineering notation without zeros

### ISSUE THREAD

**Issue by proximous** [josdejong/mathjs#1813]
I'm trying to understand the difference between precision and fixed and if either can help me.

I need to display numbers where I don't know the underlying precision, so I'm just looking to display them in Engineering notation with the least zeros possible. For example:

123456780.0 -> 123.45678e6
452550000.0 -> 452.55e6
600000000.0 -> 600.0e6
9000000000.0 -> 9.0e9

Is this possible with the format command? I can't seem to find a single format command that would work for all of these cases.

**Comment by josdejong** [comment]
Thanks for bringing this up @proximous. I tried it out with your values and discovered there is a bug in `format`:

```js
math.format([123456780, 45255e4, 600000000, 9000000000], {notation: 'engineering'})
// output is: [123.456780e+6, 452.550000e+6, 600e+6, 9e+9]
// should be: [123.45678e+6,  452.55e+6,     600e+6, 9e+9]  (no needless trailing zeros)
``` 

This is a bug in the number implementation of `math.format`, it works correctly for `BigNumber`:

```js
math.format(math.bignumber([123456780, 45255e4, 600000000, 9000000000]), {notation: 'engineering'})
// output: [123.45678e+6, 452.55e+6, 600e+6, 9e+9]
``` 

The only difference with the outputs you want is no needless trailing `.0`. What is the reason you would like to have these trailing `.0` in foor example `9.0e9`? (It's in some programming languages a way to denote a floating point value instead of an integer number, but it has no mathematical meaning this way unless you would really see it as a significant digit).

**Comment by josdejong** [comment]
@proximous the issue with trailing zeros is resolved in `mathjs@6.6.3`

**Comment by proximous** [comment]
Downloaded version 6.3.3 and it works great! Thanks! I don't need the trailing `.0`. That just the floating point format I'm used to seeing, but your library works great for me with this fix!

**Comment by josdejong** [comment]
Great to hear :+1:
