### ISSUE TITLE
Online / Incremental standard deviation

### ISSUE THREAD

**Issue by nasht00** [josdejong/mathjs#1835]
Is there a way to compute std/avg/min/max etc but incrementally?

Meaning I receive the data in sequence and not as a complete set?

**Comment by josdejong** [comment]
Hm, no there is not something like that, except for the function `cumsum` for which a PR is being made: #1765. 

What would you like to have exactly? Functions like `cumstd`, `cumavg`, etc?

**Comment by nasht00** [comment]
Looking at the cumsum documentation, I'm not sure it's the same.

Imagine a loop (in reality probably a stream), and for each iteration I want to to insert the data point and refresh the mean and standard deviation. Without having to manage all the historical values in an array.

I ended up using https://www.npmjs.com/package/stats-incremental, which did the work.

**Comment by josdejong** [comment]
Good to hear you found a good solution 👍 . It sounds indeed like you're in need of a streaming API for statistics. Something like an object `IncrementalStd(initialData)` with methods `.add(newData)` and `getStd()`. 

Would you like to explore how we could build something like that in mathjs, or shall we close this issue since have a working solution already?

**Comment by nasht00** [comment]
For the sake of my project, the solution I found is enough for me.

I'll leave it up to you whether you still want to keep this in your todo list...

**Comment by josdejong** [comment]
Good to hear!

Let's close this issue for now, and reopen if there is again a need for it. Thanks for your inputs 👍
