### ISSUE TITLE
Support for feet and inches abbreviation?

### ISSUE THREAD

**Issue by gap777** [josdejong/mathjs#1852]
Hi,
Is there a way in mathjs to treat `12 "` as 12 inches, and `6 '` as 6 feet?
Thanks

**Comment by josdejong** [comment]
The quote and double quote characters and `'`, `"` are used for strings, so that is conflicting. There may be a possibility to use the characters for both in the parser, I'm not entirely sure.

If you're not using text in your application, you could write a regular expression to replace all `"` occurrences with `inch`, and all occurrences of `'` with `feet`, and after that evaluate the expression.
