### ISSUE TITLE
Make resize() accept output from size()

### ISSUE THREAD

**Issue by mightypenguin** [josdejong/mathjs#1882]
Something like this would be nice.
let mymatrix = matrix();
.... add things to mymatrix....
let s = size(mymatrix);
let n = matrix().resize(s);

**Comment by josdejong** [comment]
That's a very good point. I can hardly believe this limitation never occurred to me 😂 . Fixed via https://github.com/josdejong/mathjs/commit/6c7f4c860e85dfae4558685ef68a0d0cb5164655 (not yet published).

Note that alternatively you can use the `resize` function instead of the method which already works:

```js
let s = math.size(mymatrix);
let n = math.resize(matrix, s);
```

**Comment by josdejong** [comment]
FYI: there is an open discussion about how we can make behavior of the `size` function and methods better consistent, see #1771.
