### ISSUE TITLE
No access to `toTex` field for built-in functions since MathJS 6

### ISSUE THREAD

**Issue by ovk** [josdejong/mathjs#1900]
Prior to MathJS 6 many built-in functions had `toTex` field that defined convertion to TeX. This was useful because it allowed for an easy function alias definition, such that it preserves `toTex` of the original function, for example:

```js
var nCr = math.typed('nCr', {
  'number, number': function (n, k) {
    return math.combinations(n, k);
  }
});

nCr.toTex = math.combinations.toTex;
math.import({ 'nCr': nCr });

console.log(math.eval('nCr(4, 3)'));
```
(see this [working example](https://jsfiddle.net/xpoygLst/))

However, since MathJS this field is gone. Looking at commit history, it seems like that was done deliberately (see https://github.com/josdejong/mathjs/commit/19275e5eaadf2a3b3133bb11fcac1c32765b65fe#diff-e9fcb2d2b7fb7ee58e53567a4e0ea345 ). But unfortunately, the `latexFunctions` is not accessible.

Not sure if such use-case was considered, but I was relying on it for defining aliases that preserve TeX representation.
Is there now a better way to do this? Or should `latexFunctions` be made easily accessible (perhaps, on `math` object)?

**Comment by josdejong** [comment]
Thanks for reporting @ovk . 

At first I thought this the `.toTex` functionality was fully deprecated, as described in [the commit that you link to](https://github.com/josdejong/mathjs/commit/19275e5eaadf2a3b3133bb11fcac1c32765b65fe#diff-88dc7475eedf918122374be6d7c2c151), but looking at the current code that is still functional. (I just created a commit to describe this deprecation but removed this again since it's not true). It's quite a while ago already 😅.

The use case of reading for example `math.combinations.toTex` for external use never crossed my mind, it was created only as an input for the `toTex` method. So, sorry for the confusion.

If this case of having an alias is a special case it may be easiest to just copy the `{ 2: '\\binom{${args[0]}}{${args[1]}}' }` in your code, it's no rocket science. If you have quite some of these aliases you can use a custom toTex handler ([see docs](https://mathjs.org/docs/expressions/customization.html#handler)), here a demo:

```js
const { create, all, FunctionNode } = require('.')

const math = create(all)

const nCr = math.typed('nCr', {
  'number, number': function (n, k) {
    return math.combinations(n, k)
  }
})

math.import({ 'nCr': nCr })

const texAliases = {
  'nCr': 'combinations'
}

function customLaTeX(node, options) {
  if (node.type === 'FunctionNode' && node.name in texAliases) {
    const alias = new FunctionNode(texAliases[node.name], node.args)

    return alias.toTex(options)
  }
}

const expression = math.parse('nCr(4, 3)')
console.log(expression.toTex({ handler: customLaTeX })) // "\binom{4}{3}"
```

**Comment by ovk** [comment]
Thank you @josdejong for such an elaborate response. You suggestion to hook a function alias to an existing function `toTex` via the custom Tex handler indeed works, and it helps me avoid hard coding Tex representations for each function alias.

But perhaps in the future you could consider implementing an easy way to define function aliases? I can see it being helpful in some cases, maybe even inside the MathJS library itself (like if you want to rename a function, but want to keep an old name as an alias for backwards compatibility).

*Please feel free to close this issue as resolved*

**Comment by josdejong** [comment]
You're welcome. 

If creating and working with function aliases is something that many people have to deal with and can make life easier we can definitely consider working something out for this. I have the feeling though that this is a bit of an edge case. If there is need for it let's reopen the issue.
