### ISSUE TITLE
missing math function: round-to up/down with precision

### ISSUE THREAD

**Issue by anieve01** [josdejong/mathjs#1901]
this math library will be complete if it includes the following math functionality, which is heavily used in financial use cases (e.g., banker's rounding): https://github.com/sindresorhus/round-to

**Comment by josdejong** [comment]
Thanks for your suggestion. Maybe we can extend the existing function `floor(x)` and `ceil(x)` to pass a number of digits like `round(x, n)`. Or we could extend `round` to allow passing rounding options like `UP`, `DOWN`, etc.

You can configure to use BigNumber (better anyway to use that for finanical data than regular numbers because regular numbers suffer a lot from round-off errors). The BigNumber library integrated in mathjs is powered by https://github.com/MikeMcl/decimal.js, which allows to configure different rounding options. So you could write a wrapper function to use that I think.

**Comment by rnd-debug** [comment]
Working on providing `floor(x, n)` and `ceil(x, n)`. Let's see how it goes.

**Comment by josdejong** [comment]
👍 thanks @rnd-debug !

**Comment by josdejong** [comment]
Available now in `v7.4.0`, thanks again @rnd-debug .
