### ISSUE TITLE
Bad answer with factorial

### ISSUE THREAD

**Issue by dev-kg** [josdejong/mathjs#1918]
# Prerequisites
- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
priority of operation would be respected all the time without unnecessary parenthesis
2^(2)! should equal 24

# Current Behavior
priority of operation is respected only if we add unnecessary parenthesis
(2^(2))! equal 24 (good answer)
but
2^(2)! equal 4 (wrong answer)

Thanks you for all your work :)

**Comment by josdejong** [comment]
Thanks Kevin for your question. Different math and programming applications may have slightly different order of preference of operators. Apparently the preference of the factorial operator `!` differs from what you expect. 

The preference of the operators of mathjs are described here: https://mathjs.org/docs/expressions/syntax.html#precedence 

If it turns out that all math applications use the preference you propose, we can consider changing it to recon with the expectation of people. I've done a quick check but for example Wolfram Alpha and Google use the same precedence to evaluate `2^(2)!` and return 4, like mathjs. What application are you using that returns 24?

**Comment by KevinGervais** [comment]
Actually we develop a user-friendly calculator that uses your library and it is impossible to fix our issue with factorial with your preference of operators configuration.

If it is easy to implement, would it be possible in the future to be able to add by ourself in the config of mathjs the order of operators?

**Comment by josdejong** [comment]
Implementing custom precedence of operators will be complex, I think we should not consider this for mathjs.

Some ideas:

- You can reconsider your precedence of `!`. Big examples like Google calculator and Wolfram alpha (and mathjs) use a different precedence. Most important though is what the users of your calculator will expect.
- Maybe it's possible to simply not allow ambiguity when entering a calculation like `2^2!`, that may be possible if users do not have free text input but work via buttons. 
- Make it explicit to the user how the operators are evaluated by displaying something like "(2^(2!))", see for example how https://snapcraft.io/qalculate does this.
- Find a different evaluator which does have the precedence you're looking for, or create your own using a parser-generator.
