### ISSUE TITLE
Adding decimals in simplify leaves unnecessary ratio

### ISSUE THREAD

**Issue by thunderkid** [josdejong/mathjs#2026]
On the mathnotepad, entering

```simplify("2.32423 + 3.3434")```

results in

```5.66763e+5 / 1e+5```

instead of just

```5.66763```

(I'm assuming this uses the current mathjs kernel, though I haven't checked it except on the notepad.)

**Comment by josdejong** [comment]
That is an interesting case, thanks for reporting.

The function `simplify` returns numeric input as a fraction normally, so `simplify("0.4")` returns "2 / 5". In this case the calculated fraction looks very odd with the `+5` exponent.

Anyone able to look into a fix for this?

**Comment by josdejong** [comment]
o wait a second, it makes sense I think: the fraction should have integer values, but since the integer values are quite large, they are represented with an exponent.

So this looks simpler:

```js
math.simplify('2.32423 + 3.3434').toString({ upperExp: 1e10 })
// "566763 / 100000"
```

So there isn't really a bug here, but I think we can think through if we do want to represent such values as a fraction. Maybe we can change the rules of `simplify` such that it does only output a fraction if the numerator and denominator are small enough. 

The `Fraction` outputs are handled by this piece of code: https://github.com/josdejong/mathjs/blob/fc042d0b781e1e51a73d0fd7b0d13584f987ff63/src/function/algebra/simplify/simplifyConstant.js#L73-L83

**Comment by thunderkid** [comment]
I see. Or is there some `simplifyToDecimal` option one could use instead?

**Comment by josdejong** [comment]
Fixed via  488943d (not yet published)

> I see. Or is there some `simplifyToDecimal` option one could use instead?

No but I think the fix I just made makes sense: only returning a fraction when numerator and denominator are small enough (hardcoded as `< 10000` right now).

**Comment by thunderkid** [comment]
Ok. So for a `simplicityToDecimal` you’d want to set `FRACTION_LIMIT = 1`?
Do you think this should be available as an option for `simplify`? It seems
like a common use case.

**Comment by josdejong** [comment]
Hm yeah that makes a lot of sense. Will do.

I also see there was already an option `exactFractions` which allows to completely disable returning fractions.

Thinking about it, this may be a breaking change, when simplify doesn't always return a fraction anymore. So in order not to have a breaking change, I will set this new option `fractionLimit` to `Infinity` by default.

**Comment by josdejong** [comment]
Implemented new option via 9250f44

**Comment by thunderkid** [comment]
That seems a good way to do it. 

But along these lines, I'm wondering whether when a fraction is output it should always default to `{upperExp: 1e100}`. Something of the form `5.66763e+5 / 1.23427e+5` obscures the fact that it's a ratio of integers rather than rounded decimals, whereas `566763/123427` makes this explicit. Scientific notation in ratios of integers seems confusing, but I'm not sure whether this might be a breaking change.

**Comment by josdejong** [comment]
Function simplify actually returns an expression of a division of two numbers. When calling `.toString`, we get the formatting with `e+5`, which is done by `math.format` (and not related to `simplify` itself). In general, formatting a large number with an exponent makes sense.

I think to "really" solve this, we could let `simplify` return a real `Fraction` instead of a division operator. A `Fraction` is not formatted with exponential notation: 

```js
math.format(math.fraction(566763, 100000))
// "566763/100000"
```

This would be a breaking change though.
