### ISSUE TITLE
Latest version is missing @babel/runtime

### ISSUE THREAD

**Issue by MelonCola** [josdejong/mathjs#2169]
The newest version causes a Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault' error, which can be fixed by adding an @babel/runtime to the dependencies.

I'm not going to try making a PR as I'm not familiar with babel and am not positive this is the correct solution, but as far as I can tell, from the docs here https://babeljs.io/docs/en/babel-plugin-transform-runtime, it is.

**Comment by josdejong** [comment]
Thanks for reporting @MelonCola . This regression was introduced in v9.3.1, where I added `@babel/runtime` in order to enable using generators in #2166. I've now reverted this, and we will look deeper into this in #2166 to set up a correct solution with babel, that should _not_ introduce `@babel/runtime` as a dependency.

**Comment by josdejong** [comment]
Fix is published now in `v9.3.2`
