### ISSUE TITLE
Import functions directly from CDN

### ISSUE THREAD

**Issue by RobertCardwell** [josdejong/mathjs#2194]
Hi,

thank you for such an excellent library! I've read the documentation and it does not appear possible to do something like this in a js file, by analogy with other libraries:

import {sqrt} from 'https://cdn.jsdelivr.net/npm/mathjs@9.3.2/lib/browser/math.js'

I get the error message:

"The requested module 'https://cdn.jsdelivr.net/npm/mathjs@9.3.2/lib/browser/math.js' does not provide an export named 'sqrt'"

Is this possible and I'm doing something wrong or might it be considered for a future version?

I do have the library working from a local instance. 

Cheers,

**Comment by m93a** [comment]
Hey Robert,
I have never used jsdelivr, so I have no idea how that works. But using plain NPM, it is definitely possible to import functions like `sqrt` directly from the package. The [README](https://github.com/josdejong/mathjs/blob/develop/README.md) has exactly this code as an example:
```typescript
import {
  atan2, chain, derivative, e, evaluate, log, pi, pow, round, sqrt
} from 'mathjs'
```
What environment are you using? If you're on Deno, you probably need to pull the type definitions from `@types/mathjs` since math.js doesn't come with its own TypeScript definitions yet.

**Comment by RobertCardwell** [comment]
Hello! Thank you for your rely. I was hoping to use it the same way as, for example, js-combinatorics - https://www.npmjs.com/package/js-combinatorics - which, while it can be installed by NPM, can also be imported (as I do use it) at runtime without any prior installation, as it says at that page:

[quote]
You don't even have to install if you import from CDNs.

import * as $C from 'https://cdn.jsdelivr.net/npm/js-combinatorics@1.4.5/combinatoric
[/end quote]

That's how I'd like to use math.js if it is possible, for the sake of portability.

**Comment by josdejong** [comment]
The file /lib/browser/math.js is a bundle with UMD format, not suitable to consume as ESM import. We have ESM exports under /lib/esm, but that cannot yet be consumed directly from the browser because (a) it's a huge amount of requests for individual files, and (b) the npm dependencies are imported with an absolute path. It would be nice to have an ESM bundle that can be used directly in the browser though.

**Comment by RobertCardwell** [comment]
Thanks for the detailed explanation. I'll close this issue.
