### ISSUE TITLE
Parser can't distinguish variables implicitly multiplied by parentheses from function invocation

### ISSUE THREAD

**Issue by joshhansen** [josdejong/mathjs#2230]
Consider the following:

    math.parse('x(y + 2)')

This is meant to convey a variable `x` times a parenthetical expression `(y + 2)`. However, MathJS interprets it as if there were a function `x` being invoked with argument `y + 2`.

I would expect `FunctionNode`s to result only when a known function name is used, like `sin(y + 2)`, and perhaps certain conventional function names by default, like `f` and `g`.

If the defaults are considered appropriate as they are, I would at least like the ability to customize the set of names considered to be functions, perhaps using the parser object (`math.parser()`). Or maybe the ability to define variable names without necessarily having to give them a value, with the parser respecting the declaration.

I am willing to work on this functionality myself and attempt to create a PR but I wanted to get thoughts on design before I put in the work.

**Comment by joshhansen** [comment]
An additional reason to make `parse` aware of variable and/or function names would be for understanding multiple implicitly multiplied variables as separate. For example, `math.parse('xyz')` gives a single symbol node rather than three symbol nodes implicitly multiplied..
Of course, the case of a single variable with a longer name should also be supported:

**Comment by m93a** [comment]
The two use cases you listed are supported using this syntax:
 * `(x)(y+1)` === `x * (y+1)`
 * `x y z` === `x*y*z`

Regarding `xyz`: I would argue that the variables' values should not affect the way expressions are parsed – making `xyz` parse as either `x*y*z` or `xyz` depending on whether a variable called `xyz` exists sounds like an unintuitive and error-prone design to me.

The case with `x(y+1)` is more difficult to decide. As a user, I would expect that if `f` and `g` were functions, something like `(f + g)(x)` would result in `f(x) + g(x)`, not `(f + g)*x`, but if `f` and `g` were numbers, I'd expect `(f + g)*x`. On the other hand both are in theory possible with the current syntax:
```
h = f + g
h(x)
// → f(x) + g(x)

(f + g)(x)
// → (f + g) * x
```

**Comment by joshhansen** [comment]
I'm parsing user input and hoping to make the experience as natural as possible. Requiring explicit multiplies or spaces between variables doesn't line up very well with how math is commonly used, so I'll want to support these use cases one way or another.

I punted the issue of multiple implicit multiplies of variables (`xyz`) to another issue, #2236

As for function invocation vs implicit multiplication, the expression language docs already seem to imply that only a fixed set of functions are valid:

"Functions are called by entering their name, followed by zero or more arguments enclosed by parentheses. All available functions are listed on the page Functions."

But the parser acts as if anything can be invoked as a function.

Limiting `FunctionNode` output to known functions (whether library builtins or user defined via the expression language or parser object)---and otherwise outputting a `SymbolNode` implicitly multiplied by the parenthetical expression---would resolve this issue in my eyes. I'm not looking for support of `(f + g)(x)` at this time, which seems more involved.

I could probably attempt this myself but I'd like to get a dynamic list of function names rather than just statically copying them (requiring manually updating later) and I'm not sure how to do that. Pointers welcome. (How is [this list](https://mathjs.org/docs/reference/functions.html) generated?)

**Comment by josdejong** [comment]
> Regarding `xyz`: I would argue that the variables' values should not affect the way expressions are parsed – making `xyz` parse as either `x*y*z` or `xyz` depending on whether a variable called `xyz` exists sounds like an unintuitive and error-prone design to me.

I agree with @m93a on this, well explained. Implicit multiplication opens up a lot of ambiguity, and because of that I'm not a big fan of it (ie. when entering `1/2x` do you mean `(1/2)*x` or `(1/(2*x)`?). 

I do understand that it is *really* convenient to be able to enter `x(y + 2)` and have it just work when `x` holds a value and not a function. Like I said in https://github.com/josdejong/mathjs/issues/2236#issuecomment-855210188, starting to support this kind of behavior (differing behavior based on actual values of the scope) can lead to complex issues very quickly, so we need to be careful and think it through, and _if_ we want to implement support for it, do so in a new function like `smartEvaluate` or something like that. It would be interesting to explore the possibilities and difficulties in more detail.

I think to support these cases, you could write a transform, similar to the example I gave in https://github.com/josdejong/mathjs/issues/2236#issuecomment-855210188, where you replace `FunctionNode` instances which refer to a value and not a function.

**Comment by m93a** [comment]
Closing this for now, can reopen if needed
