### ISSUE TITLE
Variable names containing dots

### ISSUE THREAD

**Issue by WieFel** [josdejong/mathjs#2242]
Hi,
is there a way to support variable names that have dots inside? e.g. `prg.temperature` or possibly also multiple dots.
My goal would be to evaluate equations like: `prg.temperature + prg.brightness + 7`

Maybe it is possible to switch off the behaviour of interpreting dots as property-accessors!?

Any help is welcome!

**Comment by josdejong** [comment]
The dot `.` is a reserved keyword and can indeed not be used in a variable name. 

You can use nested objects and properties though, so maybe you could do:

```js
const scope = {
  prg: {
    temperature : 25,
    brightness: 66
  }
}
const result = math.evaluate('prg.temperature + prg.brightness + 7', scope) // 98
```

**Comment by WieFel** [comment]
@josdejong thanks for the answer.
It wouldn't help to do some parser customization like [this](https://mathjs.org/docs/expressions/customization.html#customize-supported-characters), right? For example add the `.` as a recognized character to `isAlpha`...?!

I also have a problem when parsing the expression and trying to get the variables...
e.g. using `prg.temperature + prg.brightness + 7` and calling this function on it:
```javascript
/**
 * @param {string} expression 
 * @returns a list of variables in the order they appear within the expression.
 */
export function getVariableNames(expression) {
    const node = math.parse(expression);
    const filtered = node.filter(node => node.isSymbolNode).map(e => e.name);
    return filtered;
}
```
yields `[ "prg", "prg" ]`, instead of the expected `[ "prg.temperature", "prg.brightness" ]`.

**Comment by josdejong** [comment]
The example I gave above doesn't make `prg.temperature`, instead, it makes a variable `prg` which is an object containing two properties `temperature` and `brightness`.


You could try out if customizing `isAlpha` works for you, could be, but it feels a bit tricky.

Another idea; you could do some pre-processing of an expression using a regular expression, replacing dots in a variable name with an `_` for example, ie. turn `'prg.temperature + prg.brightness + 7'` into `'prg_temperature + prg_brightness + 7'`, which makes it valid variable names. Error messages regarding the variables could be misleading though when they contain a `_` instead of `.`.

**Comment by WieFel** [comment]
In the end I got it working by using a custom `isAlpha` function:
```javascript
const isAlphaOriginal = math.parse.isAlpha
math.parse.isAlpha = function (c, cPrev, cNext) {
  return isAlphaOriginal(c, cPrev, cNext) || (c === '.')
}
```

Parsing and calculation with variables containing dots is now working.
Also, floating point numbers (e.g. `5.7`) are not affected by this and work as expected.

**Comment by josdejong** [comment]
👍  thanks for sharing your solution
