### ISSUE TITLE
`type/bignumber/BigNumber.js` is run >100 times during `npm test`

### ISSUE THREAD

**Issue by m93a** [josdejong/mathjs#2243]
## Steps to reproduce
1. open `type/bignumber/BigNumber.js`
1. add `console.log('Constructing BigNumber)` to `createBigNumberClass` (alternatively, just [clone my code](https://github.com/m93a/mathjs/blob/bug-create-bignumber-class/src/type/bignumber/BigNumber.js))
2. `npm test | grep "Constructing BigNumber"`
3. The message is logged more than 100 times

## Screenshots
![image](https://user-images.githubusercontent.com/1671665/121197325-8305ff00-c871-11eb-8886-45dabc31e8eb.png)
![image](https://user-images.githubusercontent.com/1671665/121197421-93b67500-c871-11eb-8b68-28d62d9a73c4.png)
![image](https://user-images.githubusercontent.com/1671665/121197464-9f09a080-c871-11eb-8359-b27bd6273122.png)

.

That sounds like something that should **not** happen, right?

**Comment by josdejong** [comment]
Yes, this is expected behavior. 

Every time you create a mathjs instance, a new instance of every function is created, bound to the passed config and dependencies. In the unit tests there are quite some tests checking whether configuration is applied correctly, so you see things like `const math2 = math.create()` and `const bigmath = math.create({ precision: 100 })` etc.

**Comment by m93a** [comment]
Ah, you're right! Doing a quick Ctrl+F in the test folder yielded ~70 instances of `create(`. That's on the same order of magnitude 😁️

Thanks!

**Comment by josdejong** [comment]
👍
