### ISSUE TITLE
Undocumented `implicit` set on `unaryMinus` and `unaryPlus` OperatorNodes

### ISSUE THREAD

**Issue by joshhansen** [josdejong/mathjs#2255]
> math.parse('-1').implicit
false
> math.parse('+1').implicit
false

In unit tests I'm comparing nodes coming out of MathJS's `parse` to nodes I have constructed myself. I'm finding an unexpected difference in that `unaryMinus` and `unaryPlus` seem to always have `implicit = false`.

Can you help me understand the meaning of this flag so that I can decide whether to set it or not (and to what) in the nodes I construct using `new OperatorNode`? I can't find anything in the documentation, which as far as I can tell only talks about implicit in the context of implicit multiplies.

**Comment by m93a** [comment]
Ah, don't mind that :) The `implicit` is a property of the `OperatorNode` class, but it is only ever used in implicit multiplication, otherwise it is always set to `false`.

[Here's](https://github.com/josdejong/mathjs/blob/develop/src/expression/node/OperatorNode.js#L41) the relevant code that sets `op.implicit` – you can see that it sets `op.implicit = false` if you omit the last parameter in `OperatorNode`'s constructor. And as you can see [here](https://github.com/josdejong/mathjs/blob/develop/src/expression/parse.js#L1147), that's exactly what we do in `parseUnary`. Therefore, unary plus and minus nodes will always have `node.implicit == false`.

> Can you help me understand the meaning of this flag so that I can decide whether to set it or not (and to what) in the nodes I construct using `new OperatorNode`?

The simple answer is: if you're not dealing with multiplication, omit the last parameter and it will be good.

**Comment by josdejong** [comment]
Thanks @joshhansen , I've documented the `implicit` property now via https://github.com/josdejong/mathjs/commit/8b3e0e1067c38821054e1b53df8b2d5ea039d3ce
