### ISSUE TITLE
Update version of Chart.js in examples

### ISSUE THREAD

**Issue by aravintht7** [josdejong/mathjs#2278]
<div type='discussions-op-text'>

<sup>Originally posted by **aravintht7** July  7, 2021</sup>
path : mathjs\examples\browser\rocket_trajectory_optimization.html 

In rocket_trajectory_optimization.html  file this specific script needs to be updated to the latest version, this has high security vulnerability when we scan our project with white source. 
upgrade chart.js from 2.5.0 to 2.9.4
https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js

Please upgrade it to https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js</div>

**Comment by m93a** [comment]
Hey Aravinth,
thanks for reaching out!

Would you mind sharing what the security vulnerability is? Example files aren't security critical, so it is hard to imagine a vulnerability that would be relevant there. According to [Snyk](https://snyk.io/test/npm/chart.js/2.5.0), the 2.5 version of chart.js suffers from prototype pollution, however since there no untrusted code in example files, so the only person who could pwn the developer is... the developer themselves.

Updating packages to the latest versions is always a good practise, but I am yet to see how this is a security vulnerability of math.js

Thanks!
