### ISSUE TITLE
This is not the correct result: chain(0.39).multiply(5).done();

### ISSUE THREAD

**Issue by Vibing** [josdejong/mathjs#2283]
```js
chain(0.39).multiply(5).done(); // 1.9500000000000002
```
It should be 1.95

**Comment by Yaffle** [comment]
This matches the JavaScript 0.39*5
seems, you need to use 
```
math.chain(math.bignumber(0.39)).multiply(math.bignumber(5)).done()
```

**Comment by HTG-YT** [comment]
This is most likely due to the lose of precision in floating-point arithmetic.

**Comment by m93a** [comment]
Hey @Vibing,
The behavior you described is indeed the expected behavior. I recommend that you read something about how floating point arithmetic works, it is valuable knowledge for doing *any* numerical computations 😁️ These are great resources to get you started:
 * [JavaScript deep dive – Floating point numbers and the (in)famous rounding errors](https://www.matthewburfield.com/javascript-deep-dive-floating-point-numbers/)
 * [Python Tutorial: Floating point](https://docs.python.org/3/tutorial/floatingpoint.html)
 * [Wikipedia: Floating-point arithmetic](https://en.wikipedia.org/wiki/Floating-point_arithmetic)

That said, if you don't like rounding errors in decimal numbers, you probably want to use the decimal representation with `math.bignumber`, as recommended by Yaffle.
