### ISSUE TITLE
Typescript: bump from version 9.5.0 to 9.5.1 broke everything

### ISSUE THREAD

**Issue by sylvainar** [josdejong/mathjs#2339]
Hi there!

It's really awesome that the types have been realigned, however it broke a lot of things in my setup. I was relying on MathNode a lot for typing, and was really affected by this change:
![Screenshot_20211014_143705](https://user-images.githubusercontent.com/9823286/137318919-5c2fa848-ad0d-444b-ba57-fb6026ed4db9.png)

I'm gonna fix them, however it was a bit rough because it was a minor version change and in semver you're not supposed to introduce breaking changes.

Cheers!

**Comment by josdejong** [comment]
I've now published two new versions:

- `v9.5.2` reverting the breaking changes in the TypeScript definitions introduced in `v9.5.1`
- `v10.0.0` applying the breaking changes in the TypeScript definitions again

**Comment by sylvainar** [comment]
Awesome!

**Comment by joshhansen** [comment]
@josdejong This just came to my attention. The new major version seems like a reasonable resolution to me. I think it was agreed in the #2290 PR that the best approach to `MathNode` was as a union type, so while we could keep the interface named `MathNode` instead of `MathNodeCommon` and introduce a new `MathNodeAll` union type or something, I think it's better to take the hit with a breaking change and major version bump. My apologies to @sylvainar for not anticipating the breakage, though!

**Comment by josdejong** [comment]
Thanks @joshhansen, agree, the solution you created is the most neat for the long term, only it's a breaking change 👍

**Comment by sylvainar** [comment]
Totally agree, new types are really nice to work with
