### ISSUE TITLE
add complex conjugation, real, imag parts to list of valid parse() expressions?

### ISSUE THREAD

**Issue by schuelaw** [josdejong/mathjs#2406]
I'm trying to build some visualization tools for complex functions. It works well with the expression parser, but would be wonderful to allow user to specify complex conjugates, real and imag parts in the functions they wish to visualize. I guess this is a feature request. (Love the library, thank you for creating it.)

**Comment by gwhitney** [comment]
Using the jsbin linked on the homepage, all of 're(2+3i)', 'im(2+3i)', and 'conj(2+3i)' appear to work in the parser already.

**Comment by schuelaw** [comment]
Indeed! They are there and functioning properly. I guess this is now just a request to add these functions to the documentation for the parse() function. Thank you.

**Comment by gwhitney** [comment]
And thanks for taking the time to provide feedback about this project. Please see https://mathjs.org/docs/expressions/syntax.html#complex-numbers -- both `re()` and `im()` are mentioned explicity. Admittedly, `conj()` is not, but that page doesn't purport to incorporate an exhaustive listing of all allowed functions -- which is available at https://mathjs.org/docs/expressions/syntax.html#complex-numbers and which does mention `conj()`. One feature of mathjs is that every function on the function reference may be used either directly from javascript or through the parse/compile/evaluate mechanism, or via chaining.  If you have specific suggestions about particular places that the documentation should be improved, I'd suggest you post them or even better file a pull request.

**Comment by schuelaw** [comment]
Sorry I missed that. I appreciate your taking the time to help me out. The pathway to my question was to scan the documentation linked above for something like real part, imaginary part and conjugation. Clearly I missed re() and im(). I actually searched that page for "conjugation" and, not finding it, jumped over to the docs for parse() https://mathjs.org/docs/expressions/parsing.html and performed a similar scan and search for the string "conjugation". Not finding anything, I decided to post here.

I don't see `conj()` in the link you posted, possibly it's not the link you intended to post since it's a dupe of the earlier link that doesn't have `conj()` in it?

Finally, if you're open to it, I'm happy to work on the documentation. I'm not super sure how to do it, but I'll dig into it a bit.

**Comment by gwhitney** [comment]
Oops, sorry about the cut and paste error on the second link, I have edited to fix it.

If you have any remaining concern with the documentation, feel free to post it and/or offer a pull request.

(Note I am not the - or even a - maintainer of mathjs, just an active user thereof trying to help out since for now the primary maintainer/author is very busy midweek.)

**Comment by gwhitney** [comment]
As far as we can see, the information needed is there but absolutely if you or anyone has further suggestions on how to organize it better to make it more accessible or easier to find, please re-open this issue or file a new issue with the suggestions. Thanks so much for being involved! (Closing due to lack of further activity.)
