### ISSUE TITLE
Docs: page for `rationalize` somewhat garbled

### ISSUE THREAD

**Issue by gwhitney** [josdejong/mathjs#2408]
See https://mathjs.org/docs/reference/functions/rationalize.html#returns. The difficulty is that the complicated specification of the return type of this function is too much for the current parser in `tools/docgenerator.js` to handle. As far as fixing this goes, would you be looking to make that parser more powerful, or to just make a special case for this one function? (I don't yet have a broad enough perspective on everything that's in mathjs to know if there are numerous other functions that would benefit from a more capable documentation parser, or if this is really an isolated case.)

**Comment by josdejong** [comment]
Ah, good point. This has to do with markdown. The reason here is that the description contains a pipe character `|`, and because we put this description inside a table, it will create a new column.

In https://github.com/josdejong/mathjs/commit/0838448098e7bf1c6115f509122c46e71b8d8994 I have improved the description to make it better readable. 

It would be nice to improve the `docgenerator.js` to warn about usage of special characters like `|` inside tables. And maybe to support multi line documentation like in `rationalize`, but that may be relatively complex and is only needed very sparsely, so that's probably overkill.
