### ISSUE TITLE
Units divide

### ISSUE THREAD

**Issue by fpiou** [josdejong/mathjs#2421]
Is it a normal thing ?

```Javascript
math.unit('1 cm').divide(math.unit('3 cm'))
> 0.33333333333333337 // attempt 0.33333333333333333
```

**Comment by gwhitney** [comment]
The slight floating-point difference between `math.evaluate('1cm/3cm')` and plain JavaScript `1/3` arises because `1cm` and `3cm` implicitly convert internally to `0.01 m` and `0.03 m` (everything goes to its base unit), and so you will find that you get exactly the same floating-point value as plain JavaScript `0.01/0.03`. The slight difference between `1/3` and `0.01/0.03` is in turn a limitation of IEEE 754 64-bit floating-point arithmetic. For exact values of rational divisions of units, use Fractions instead of plain numbers; or for more precision, use BigNumbers.

**Comment by josdejong** [comment]
See https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors for more information
