### ISSUE TITLE
Timeout for large calculations

### ISSUE THREAD

**Issue by dipunj** [josdejong/mathjs#2426]
Hi, I have been using this library to create a UI calculator in React, thank you so much for this amazing project!

I have noticed an issue, which when fixed, could improve the library.

When I call a heavy operation like `math.evaluate('9999999999!')`, the library innocuously gets busy trying to find out the result (which would be too big and probably extremely CPU intensive to calculate).

Such an operation blocks the event loop, since `math.evaluate()` is synchronous. This could make the page unresponsive. Is there a way we could timeout the function call or make this and other calculation methods asynchronous?

Please feel free to correct me if I am wrong or any other way through which I can circumvent the issue? I understand that I can put a check on the input expression itself to ensure such a large expression is not passed to the `evaluate` call, but it would really be great if the library handled this internally, or had a `math.config` flag such `timeout`.

**Comment by gwhitney** [comment]
Glad the library is helpful for you, Dipunj!

I feel modern JavaScript has some features that allow you to handle potentially long-running synchronous computations gracefully without blocking. One good example is the web worker facility, supported by [almost all](https://caniuse.com/webworkers) recent browsers. Please take a look at the code in PR #2438 for an example of using web workers to prevent the mathjs home page from blocking on a long computation (I didn't find huge factorials to take too long -- they just returned Infinity because they overflow pretty quickly -- but `sum(pickRandom([0,1],10000000)` reliably took a noticeable amount of time.)

Hence, I think it would just be an unnecessary complication to make mathjs functions asynchronous or for them to periodically yield to the event loop or to have a `timeout` config option so that they would throw an error if they took too long. (Note that if you want to give up on the computation a web worker is trying to perform, you can terminate it whenever you like.)

Hope this is helpful! If you don't think that existing general mechanisms for handling long computations will cover your use case and you have a specific proposal for how mathjs should be changed/enhanced, please do post again with more details on your situation. If there's no further feedback, we will close this in a week or so.

**Comment by josdejong** [comment]
I think the following (existing) example is probably what you're looking for:

https://mathjs.org/examples/advanced/web_server/index.html

I implemented the `workerpool` library exactly for this purpose, being able to timeout heavy calculations and protect against running out of memory by running calculations in a separate child process. It's powering https://api.mathjs.org, try out your expression there 😁

**Comment by dipunj** [comment]
Thank you for your suggestions @josdejong and @gwhitney. I think the web worker approach solves this issue very well. Additionally, in my case, I am using BigNumber, which is probably why the overflow didn't happen for `9999999999!`.
