### ISSUE TITLE
math.fraction()

### ISSUE THREAD

**Issue by fpiou** [josdejong/mathjs#2427]
I don't anderstand why the result is not the same.
```Javascript
f = math.fraction(4,5.1)
console.log(f.toFraction()) --> 2251799813685248/2871044762448691
f = math.fraction(4/5.1)
console.log(f.toFraction()) --> 40/51
```

Is it possible to add a constructeur of math.fraction(a,b) with a and b decimal ?
```Javascript
f = math.fraction(0)
f.n = 4
f.d = 5.1
console.log(f.toLatex()) // --> \dfrac{4}{5.1}
console.log(f.simplify().toLatex()) // --> \dfrac{40}{51}
console.log(f.toFraction()) // --> 4/5.1
console.log(f.simplify().toFraction()) // --> 40/51
```

**Comment by josdejong** [comment]
The fraction `4/5.1` (or `40/15`) has an infinite number of digits. Here are the first thousand: 

```
0.7843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431372549019607843137254901960784313725490196078431373
```

When you first evaluate `4/5.1`, you put get the result in a `number` which can hold up to about 16 digits: `0.7843137254901962`. So the value is already rounded (and not exact) before you send it to Fraction.js. Accidentally, this results in the exact representation of `40/51` again when Fraction.js normalizes the value.

Fraction.js itself does do some normalization internally. Apparently it normalizes this value as `2251799813685248/2871044762448691`. I suppose this normalization involves round-off errors.

**Comment by gwhitney** [comment]
Then this would seem to be a bug in Fraction.js that should be reported upstream. I do see there the long-outstanding issue that you already reported which has something of a similar flavor, but in that case "too many" digits for the accuracy of `number` type were being supplied. Here, we have the numerator/denominator version of the fraction constructor, which should if anything be more accurate than the "supply a single float" constructor, producing wonky results, since it seems that `number` should be plenty precise enough to detect that the best-approximating fraction with numerator 4 and denominator float(5.1)  is 40/51 (even though I understand that 5.1 is not exactly representable as a float).

Jos, if you agree that it's something that should be reported upstream, which of the three of us do you think should do it?

And finally, fpiou, in the meantime you might try:
```
function frac (x,y) {
    return math.divide(math.fraction(x), math.fraction(y))
}
```
At least, `frac(4, 5.1)` returns 40/51.

**Comment by josdejong** [comment]
@infusion any chance on improving the normalization of Fraction.js for input like `new Fraction(4, 5.1)`?

Related: https://github.com/infusion/Fraction.js/issues/28

**Comment by infusion** [comment]
While it would be possible to add decimal numerators and denominators by running the Farey-sequence algorithm twice that is used to interpret a single decimal number ATM, I don't quite get the point here. Rational numbers are defined to be ℤ / ℕ and so does Fraction.js. When putting decimal numbers into the gears of Fraction.js, I would call it undefined behavior. What the OP is asking for is a rational numbers division, which is `Fraction(4).div(5.1)` in Fraction.js syntax or as @gwhitney suggested with Math.js syntax.

I wouldn't call it a bug and as every function uses the `(numerator, denominator)` constructor internally to create a new return object, I wouldn't want to run the decimal places algorithm for performance reasons either (even if there is an optimization already).

Or am I missing something?

About the BigInt version of Fraction.js: The code in `bigfraction.js` is maintained besides the "old legacy" version and the test suite already runs against the BigInt version. The only reason the switch to the `BigInt` version didn't happen already is a) I'm not sure if a switch is safe already as Math.js and Fraction.js might face some older browsers in the wild and b) When users hack around the `n` and `d` attributes, they expect it to be `Number`. A `fraction.n * 3` would badly break some codebases. Maybe we should discuss this elsewhere.

Robert

**Comment by gwhitney** [comment]
Let me start by saying a hearty thanks for the excellent rational-number library, @infusion! If I might just mention my perspective: given that JavaScript doesn't have separate float and integer types (other than BigInt, which I understand is basically ready but maybe some work needs to be done on the mathjs side to help with that transition), a client of Fraction.js can see `new Fraction(4, 5.1)` as a perfectly well-formed call, and the expected semantics are clear, but currently the results are a bit off-kilter. From that point of view, wouldn't you want to just check if either argument to that constructor is non-integer and if so, initialize the new Fraction to `Fraction(4).div(5.1)` instead? (You could still have an internal constructor that doesn't do the check, if the cost of the check for all internal constructions is too high...) It would seem to be a nice invariant if always `new Fraction(x, y) == new Fraction(x).div(y)` and implementing it that way when one of x, y is non-integer would ensure that property. Or alternatively, if `new Fraction(4,5.1)` is really going to be designated as undefined behavior, it might be polite of the library to throw an error indicating that, rather than simply supply a somewhat odd result. Just thinking aloud.

**Comment by infusion** [comment]
Well, I'm not completely against it, especially as we're in the JS universe and a `Number` can quickly have some `x % 1 != 0`. Saying/documenting the numerator and denominator of the `(n, d)` constructor has to be integer, should at least convert the `Number` to an integer internally (which can be done with an integer NOP such as `x >>> 0` or `x | 0`). The reason I decided against this, and allowing this behavior the OP is complaining about is that I wanted to max out the range we can operate on with Fraction.js to `Number.MAX_SAFE_INTEGER`.

The big question to me is, as you imply @gwhitney , should we change the constructor from `(numerator, denominator)` to `(num1, num2)`, where both numbers are assumed to be rational. Rational is important here, as `Fraction(Math.SQRT2, Math.SQRT2)` should not be expected to give something meaningful. If so, I would remove all internal `new Fraction(x, y)` calls and build an own constructor using `Object.create(Fraction.prototype)`, as I already did in BitSet.js. This should (insignificantly) improve performance as we're not calling the bulky Fraction.js constructor anymore as a nice side-effect.

The second question is, if we decide for it, should we fix this on Fraction.js or Math.js? Math.js could fix this by `(n, d) => d % 1 !== 0 ? new Fraction(n).div(d) : new Fraction(n, d)`. 

So, it's more a philosophical question, if this is a) a real usecase and b) where it should be implemented. What are your thoughts @josdejong ?

**Comment by josdejong** [comment]
Ahhh, I wasn't aware that `new Fraction(n, d)` was really different from `new Fraction(n).div(d)`. 

> The second question is, if we decide for it, should we fix this on Fraction.js or Math.js? Math.js could fix this by `(n, d) => d % 1 !== 0 ? new Fraction(n).div(d) : new Fraction(n, d)`.

In the end I would just like to see fractions work as good as possible. I'm totally fine with implementing this logic in mathjs to improve this behavior. From a Fraction.js point of view I would have the same reasoning though. It looks like the internal `parse` function used in `new Fraction(n, d)` can be improved upon with this simple "trick" (and maybe there are more possibilities for improvements), which would just benefit Fraction.js in general. 

But on the other hand, I can also imagine we just do not accept non-integer input for the arguments of Fraction, make this more strict by just throwing an exception.

**Comment by infusion** [comment]
There is only a difference between `new Fraction(n, d)` and `new Fraction(n).div(d)` for `n` and `d` not being integers of course. But did you also expect `new Fraction(n, d)` to work with rational numbers? If so, I might be wrong here and I underestimated the case.

**Comment by josdejong** [comment]
Right now, `mathjs.fraction(n, d)` returns `new Fraction(n, d)`, and `n` and `d` can be any `number` value, also rational numbers.

> But did you also expect new Fraction(n, d) to work with rational numbers?

I've never thought of it so far. But currently it's possible to pass rational numbers: neither mathjs nor Fraction.js will complain. So I guess we can either:

1. throw an error for rational number input (thinking about it more, this option makes sense to me)
2. make it work better for rational numbers with the ideas shared above

Both approaches could be implemented in either `mathjs` or `Fraction.js`. @infusion do you think it's valuable to make Fraction.js deal with this? If not we'll implement something in mathjs

**Comment by infusion** [comment]
I think I would change it on Fraction.js to not diverge Math.js and Fraction.js on such minor details, if we decide against the throwing option. About the `n` and `d` attributes: I would not implement checks for that, maybe adding a readme not on that, but I would not blow up checks for something that never came up so far. And if someone uses these attributes as setters, I would assume the one had a peek into the source to understand implications.

In that rush I would also refactor all internal constructor calls as I mentioned. And yes, maybe there are further optimizations this way. Only question is, should we do it? ;D

**Comment by gwhitney** [comment]
Well, I think I've already expressed my opinion that it's best not to let calls that a client might innocently write produce questionable results, so I will chime out from further comment beyond that "vote" that some change should be made, and let the leaders decide the final disposition.

**Comment by josdejong** [comment]
My preference is to throw an exception when constructing a fraction with a non-integer nominator or denominator.

**Comment by infusion** [comment]
Silently truncating the numerator and denominator is then out, as it would also result in behavior the client wouldn't expect, as @gwhitney says.

Then I'll add checks for the numerator and denominator and throw.

**Comment by josdejong** [comment]
Yes, so the original truncation issue cannot occur and will throw an error instead. Thanks Robert!

**Comment by infusion** [comment]
Okay done. I pushed it to the master branch already, as all tests are passing. Could you please take a copy of Fraction.js and test if math.js also passes everything? If so, I would release a new version and push it to npm.

A few notes:

- A Fraction instantiation now avoids `new Fraction` and creates them quicker with `Object.create`
- The faster instantiation now also makes `let x = Fraction(123)` fast (without new keyword)
- Rational numbers `(123.45, 123.45)` now throw, while `(123.45)` of course still works
- When switching to bigfraction.js one day we should remember, that we lose `NaN` Fractions. `Fraction(NaN).toString() == "NaN"`, while the BigInt version throws an invalid param exception

**Comment by gwhitney** [comment]
I am pleased to report that with the latest fraction.js, mathjs `npm run test:all` reports no errors, and `math.fraction(22,7)` works fine, but the OP's case `math.fraction(4,5.1)` throws an error. So that all seems well.  Not to pick any nits, and I am totally OK with the status quo at this point, but just to mention that the error message I got was
```
    internalBinding('errors').triggerUncaughtException(
                              ^
InvalidParameter
```
which wasn't necessarily that informative to someone unclear on the integer requirement; some folks might find it helpful if it mentioned something like "5.1 is not an integer", but obviously this should be to your taste in how far to go with exceptional conditions. Thanks so much for making this change! We'll update to the latest version of Fraction.js once it's published and then close this issue. 

@fpiou, of course that won't have the effect of making the constructor work the way you envisioned, but as you can see it turns out it was never intended to work that way, and we recommend something like the `frac(x,y)` function I posted above.

**Comment by infusion** [comment]
@gwhitney You are right. I spent some time on exception management and I like how it turned out, also with an individual exception for the floating point case here.
Besides that, also the `simplify()` method got a rewrite for performance reasons. All in all, many small changes made 4.2.0, which finally got published on npm.
Sorry to @fpiou that we didn't solve it the way you maybe wished it to be solved, but thanks for bringing this up and making the Math.js + Fraction.js duo better!

**Comment by fpiou** [comment]
I think the discussion is pretty clear and i anderstand the choice.

That was not what we expected indeed.
Our aim was to keep the numerator and denominator and operate
with him to obtain differents writing of a rationnal number.
Maybe it's not relevant for the Fractions.js class.

Thanks for your pretty good librairies.

**Comment by josdejong** [comment]
Thanks @infusion and @gwhitney , looks good 👍

**Comment by josdejong** [comment]
The new version of Fraction.js is now used in the latest version of mathjs, `v10.4.0`.
