### ISSUE TITLE
Should constructors be available in evaluate(...)?

### ISSUE THREAD

**Issue by ChristopherChudzicki** [josdejong/mathjs#2489]
Currently `math.evaluate(BigNumber(1))` throws an error. Similarly for other constructors like `Complex`, `Matrix`, `AssignmentNode`, etc.

Should these be available for use in `math.evaluate`?

*I recently learned that `evaluate` can be used in `evaluate`. `math.evaluate('evaluate("1+1")')`. How cool!*

**Comment by josdejong** [comment]
> I recently learned that `evaluate` can be used in `evaluate`. `math.evaluate('evaluate("1+1")')`. How cool!

😂 


> Currently `math.evaluate(BigNumber(1))` throws an error. Similarly for other constructors like `Complex`, `Matrix`, `AssignmentNode`, etc.

These constructors need to be called like `new BigNumber(1)`. The expression parser doesn't have support for both `new` nor for the constructors. Typically, you don't need the constructors, except for some very low level stuff like extending methods on the prototype or so. Instead of using the constructors to create instances, you can call the factory functions like `bignumber(...)`, `complex(...)`, `matrix(...)`. Because they are on "mathjs" level, these functions are more flexible in what they can accept. Does that make sense?

**Comment by ChristopherChudzicki** [comment]
Ah, that makes sense, thanks. I had been wondering why `complex` etc existed.
