### ISSUE TITLE
Error is unclear when entity being called as a function is not a function.

### ISSUE THREAD

**Issue by grufkork** [josdejong/mathjs#2493]
When evaluating an expression that contains a symbol (either a value such as pi or e, or a variable like x or y) immediately followed by a parenthesis (with implicated multiplication), the following non-descriptive error is thrown:
```js
> math.evaluate("e(5)")
< math.min.js:1 Uncaught TypeError: h(...) is not a function
    at math.min.js:1:463146
    at Object.evaluate (math.min.js:1:409025)
    at Function.string (math.min.js:1:478231)
    at Object.evaluate (math.min.js:1:97422)
    at <anonymous>:1:6
```

Note that expressions such as `pi e` or `x x` evaluate correctly. Spaces however do not make a difference in the above issue. `pi (e)` for instance does not work.

I couldn't find anything else mentioning is, is it maybe a conscious decision due to some convention? It seems to be an unexpected error however.

**Comment by gwhitney** [comment]
The difficulty here is just that the error message is not clear. The syntax `e(5)` is function-call syntax, and cannot be used for multiplication, even though the analogous syntax with a numeric constant `7(5)` **is** implicit multiplication. But basically, the parser has no way to tell the difference between `e(5)` and, say, `log(5)`. Both of these are function calls. Think about `f(5)` -- when the parser encounters that, `f` may not have a value or its value may be different from what it will be at evaluation time. So it has to classify that as a function call or as multiplication purely based on _syntax_, it can't use anything about the _value_ of f. Similarly, when the parse encounters `e(5)` it doesn't know whether, maybe between then and evaluation, you will redefine the constant `e` (which is allowed) to a bona fide function.

But you are correct, the error message does not make it at all clear what is going on (the symbol "h" is arbitrary and comes from the minification process! -- in the on-line example REPL on mathjs.org, you get an "m" instead of an "h"). So I will rename this issue and file a PR that improves the error message.

**Comment by grufkork** [comment]
Excellent! Yeah the main problem was the cryptic message, this resolves it well.
