### ISSUE TITLE
Apparent wrong order of evaluation?

### ISSUE THREAD

**Issue by enkh-erdene-89** [josdejong/mathjs#2497]
6+3+6==6?(-2*4+2):5+2
if I evaluate above expression then result is giving **7**
I think it is **5**. Please fix it.

**Comment by gwhitney** [comment]
Checking the documentation https://mathjs.org/docs/expressions/syntax.html, we see that "+" has higher precedence (binds more tightly) than "==", so this parses as

(6+3+6) == 6 ? (-2*4 + 2) : 5+2

Which is indeed 5+2 or 7 as 15 is not == 6.
I guess you meant

6 + 3 + (6 == 6 ? (-2*4 + 2) : 5) + 2

Which is 6 + 3 + (-6) + 2, or 5. But that extra pair of parentheses is needed for this meaning, because of the precedence rules (which are not unique to mathjs but pretty standard, although there is a little variation between different systems).

**Comment by enkh-erdene-89** [comment]
OK Thanks I got it.
