### ISSUE TITLE
Ignore semicolon in single line Expression or throw warning?

### ISSUE THREAD

**Issue by koosvanderkolk** [josdejong/mathjs#2511]
```
let parser = math.parser();

let b = parser.evaluate('b = 1');
console.log(b); // Returns 1

let c = parser.evaluate('c = 1;');
console.log(c); // Returns empty result set
```

As @gwhitney patiently explained to me in https://github.com/josdejong/mathjs/issues/2510, the second behaviour is caused by the parser splitting the expression by the ';', resulting in two expressions "c=1" and "". Next, because `evaluate` returns the result of the last expression, the result set is empty.

Nevertheless, for me it would make more sense to just ignore the second (empty) expression OR to throw an error/warning, as I cannot think of any sensible use case in which the author of the expression "c=1;" expects an empty result set.

**Comment by gwhitney** [comment]
Thanks for the suggestion. I agree there is little utility in evaluating 'a = 1;' by itself as opposed to just evaluating 'a = 1'  and ignoring the result if you don't want it. But the behavior of ';' in ignoring the value of its previous expression (as opposed to the newline separator which does not ignore the value of the preceding expression), is a feature that allows a multi-line expression to precisely control which expressions will contribute to the value. I.e., in mathjs `;` serves as a flag that an expression is being evaluated for side effect only. (As opposed to JavaScript, in which `;` is so useless except if you want to cram multiple statements onto one visual line that it is now generally omitted entirely.)

To that point, it would be especially reasonable if an expression like `7;` which is inherently side-effect free, were to generate exceptional behavior. I don't think "generating a warning" is mainstream JavaScript behavior; I mean, it could console.log a message, but since the console is generally invisible in ordinary operation, that's unlikely to highlight the probable behavior. So it would be reasonable for `7;` to throw a "Side-effect-free expression evaluated solely for side effects" error. Jos, what are your thoughts on that?

On the other hand, the semantics of `a =1;` are clear: they are "Hey, I am assigning 1 to a solely for the purpose of setting/changing the value of a, not because I am going to use the result '1'."

So of course it will be interesting to see the response of @josdejong on this when there is an opportunity for Jos to weigh in, but I think it is unlikely any change to the behavior of 'a =1;' will ensue.

That said, this aspect of ';' that differs markedly from JavaScript is not listed in the top level bullet list of differences between the parser and JavaScript on https://mathjs.org/docs/expressions/syntax.html, and it seems clear to me it should be. I will make a change to the source that will add that point the next time the website is updated.

**Comment by gwhitney** [comment]
> Next, because `evaluate` returns the result of the last expression, the result set is empty.

Oh, and meant to say, that's not quite right: evaluate (on a multi-expression construct) returns the values of all expressions not terminated by `;`.

**Comment by koosvanderkolk** [comment]
Thanks for the reply!

In practice I indeed remove the trailing ;. 

Nevertheless, for me it is unexpected that evaluating the single line "a=3;" returns an empty result set, because mathjs apparently processes it as two separate expressions, namely "a=3" and "". 

Especially because this differs from JavaScript* and is not documented on https://mathjs.org/docs/expressions/syntax.html**.

*) E.g. entering "a=3;" in the JavaScript console returns 3, entering "a=3;b=4;" returns 4.
**) Maybe also document there that Objects cannot have numeric keys in the mathjs parser?

**Comment by koosvanderkolk** [comment]
Ok, thanks!

**Comment by josdejong** [comment]
Thanks for the clear explanation Glen and for updating the docs. The site is indeed not yet updated, will be after the first next release.
