### ISSUE TITLE
API Service Down

### ISSUE THREAD

**Issue by XJonnyP** [josdejong/mathjs#2519]
Not a code issue. Didn't know how else to alert the owner, in case they don't know, that the web service https://api.mathjs.org/ is reporting an application error from Heroku
![image](https://user-images.githubusercontent.com/3145572/162292417-4d529cd5-a4ef-4ccc-b3af-11f43106099e.png)

**Comment by josdejong** [comment]
Thanks for reporting. I got the alarms in my mailbox. The service crashed 3 times in the last 24 hours. I've restarted the service twice by hand, but if I don't, Heroku restarts the service after a while too. 

It has been a while, I think last year a crash only happened once or twice, after the improvements made in Jan 2021, see #2064. If the stability issues continue, I'll put effort in better isolating and limiting the load that an individual user can put on the server. There is basic rate limiting in place, but each request can yield up to 10 seconds of calculation. It would be nice if instead of a number of requests, each user gets a limited amount of calculation time in seconds per hour or so. And I can do some better tuning/limiting of memory usage.

**Comment by josdejong** [comment]
I'll keep this report open till next week. If the issues continue I'll take action, and if not I'll close this topic.

**Comment by josdejong** [comment]
The service has been stable again. That previous weekend it was down once more but after that there haven't been any issues again.

I'll close this issue now. Let's reopen it if the service has issues again.

**Comment by josdejong** [comment]
The API service was down two times in the last few days due to the server running out of memory. I've tuned the memory limits and and added some stability measures.
