### ISSUE TITLE
Generic numerical type.

### ISSUE THREAD

**Issue by HanchaiN** [josdejong/mathjs#2585]
By defining a numeric type interface, implementing new numerical types would not be too hard, additionally, type definition would be more generic.
This might be beneficial to #794, #2578, future feature requests, and user-defined types and might simplify external numerical types such as `Complex`, `BigNumber`, `Fraction`, and `Unit`.
For example, a numeric type is defined with necessary functions and properties such as `add`, `mult`, `toString`, etc.

**Comment by josdejong** [comment]
That is an interesting idea indeed. For example `Unit.js` supports "any" numeric type but this is still sort of hard coded to the types that mathjs knows. 

One question is wether `Complex` is also a numeric type: I would love to see `Complex` support a generic numeric type (Like `BigNumber`, `Fraction`) instead of only `number`. 

At some places mathjs works with "scalars": for example the matrix implementation of `add` uses `addScalar` to add individual elements of the two matrices.

How can we turn this idea into something concrete? I think it makes sense to first make the idea more concrete and then work out a proof of concept to see how it works out?

**Comment by gwhitney** [comment]
Possible duplicate of https://github.com/josdejong/mathjs/discussions/2212.

Also in the [Pocomath](https://code.studioinfinity.org/glen/pocomath) proof-of-concept for an alternate organization of mathjs, I have implemented a generic numerical type adapter (and use that to incorporate fraction.js). See `src/generic/all.mjs` and `src/generic/adapted.mjs` in that repository.

**Comment by HanchaiN** [comment]
Thanks for pointing that out, the idea is similar indeed. I'll just close this issue here since it is a duplicate.
