### ISSUE TITLE
BigNumber comparison wonky

### ISSUE THREAD

**Issue by f0o** [josdejong/mathjs#2629]
Is there a way to compare two BigNumbers without casting them into Number which might screw them up?

```
const ONE = bignumber(1)
add(ONE,ONE) === add(ONE,ONE) # false
add(ONE,ONE) == add(ONE,ONE) # false

add(ONE,ONE) == add(ONE,ONE).toNumber() # true
add(ONE,ONE) === add(ONE,ONE).toNumber() # false

add(ONE,ONE).toNumber() == add(ONE,ONE) # true
add(ONE,ONE).toNumber() === add(ONE,ONE) # false

add(ONE,ONE).toNumber() == add(ONE,ONE).toNumber() # true
add(ONE,ONE).toNumber() === add(ONE,ONE).toNumber() # false
```

**Comment by f0o** [comment]
https://mathjs.org/docs/reference/functions/compare.html

**Comment by josdejong** [comment]
You are using the JavaScript equality operators `==` and `===` here. You should _not_ rely on the _JavaScript_ equality operators to do these comparisons, they do not know how to handle BigNumbers (or other non-primitive data types). The JavaScript operators for example compare the instance reference instead of the numeric value of the BigNumber.

To compare BigNumbers, you can for use:

- the `math.equal(a, b)` function (can handle BigNumber, number etc, also in mixed use)
- the `a.equals(b)` method available on a BigNumber (only working for BigNumbers)
- the expression parser: `math.evaluate(['ONE = bignumber(1)', 'ONE + ONE == ONE + ONE'])`
