### ISSUE TITLE
The `test:types` script does not throw an error when there are TS issues

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#2633]
When solving #2632, I noticed that the `npm run test:types` script does not complain about these missing return types. Whilst when looking at the file in my IDE, I _do_ see the TypeScript issues. 

Apparently, the current script using `ts-node` is very forgiving, whereas we would like it to complain about all TypeScript issues and warnings:

```json
"test:types": "cd types && node --loader ts-node/esm ./index.ts",
```

When I change the script to use `tsc` itsef, I do get a lot of TS errors:

```json
"test:types": "cd types && tsc ./index.ts",
```

To test: introduce an issue in `types/index.d.ts`, like remove the return type of `simplifyConstant()`. Then, the script should fail.

Anyone interested into making the script actually complain about all TS issues?

**Comment by gwhitney** [comment]
Ah, well, when @samestep and I were working on #2448, we were just focused on looking for a way to get the script to run, which it was not before. I don't think it occurred to either of us that if there were actual TypeScript errors that it would still nevertheless run.

Is there any reason not to just change the script to
```
"test:types": "cd types && tsc ./index.ts && node --loader ts-node/esm index.ts",
```
to ensure that it both _compiles_ and _runs_, since apparently the latter does not imply the former (?!). Let me know if that seems OK to you and I will be happy to work up a PR that does that and corrects the resulting errors.

**Comment by gwhitney** [comment]
This turned out to be more straightforward than I thought. When the tsconfig.json is enhanced to list the file we want compiled,
```
tsc -p types/tsconfig.json
```
currently runs fine, but if you delete the return type of simplifyConstant it detects that error. So as far as I can tell there currently aren't any errors in the index.d.ts or the index.ts, and the PR I just filed seems like it ought to keep it that way. But I will leave it to @josdejong to try the PR and merge it if it seems like what was being sought.
