### ISSUE TITLE
math.round(86.0962* 25, 2) is not 2152.41

### ISSUE THREAD

**Issue by SunXinFei** [josdejong/mathjs#2843]
**Describe the bug**
```
86.0962* 25 = 2152.4049999999997
```
actual `86.0962* 25 = 2152.405`
so **2152.4049999999997** round 2 will get **2152.40**
but actual **2152.405** round 2 will get **2152.41**
any good idea?

**Comment by josdejong** [comment]
This is the most asked question. It is a floating point round-off error.

See docs: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

**Comment by SunXinFei** [comment]
> This is the most asked question. It is a floating point round-off error.
> 
> See docs: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

why mathjs math.evaluate not fixed the floating point round-off error. still get ... puzzled

**Comment by josdejong** [comment]
It can be solved: either you use `BigNumber` to make this issue happen less often. Or you round-off your result at the end with a function like `math.format`. But you have to decide that yourself. It is mostly a presentational issue, please read the docs I linked to.

If mathjs would automatically apply rounding say after every operation to reduce round-off errors, it could actually introduce wrong results, because it would remove the last few digits. It would basically "shift" the problem to a few digits less than it was before, but does not really solve it. It is simply the nature of floating point numbers.

```js
0.1 + 0.2 // 0.30000000000000004 oops, not good

// suppose mathjs would automatically apply rounding to 14 digits, then it solves this issue:
math.round(0.1 + 0.2, 14) // 0.3 

// but it introduces new issues with other operations, like (1/3)*3:
math.round(math.round(1/3, 14) * 3, 14)  // 0.99999999999999 oops, not good

//wheras the original would be ok:
1/3*3 // 1
```

**Comment by SunXinFei** [comment]
> 

get it, thks

**Comment by josdejong** [comment]
👍
