### ISSUE TITLE
Cannot use import statement outside a module error.

### ISSUE THREAD

**Issue by MasterNinad** [josdejong/mathjs#2862]
The issues section is used only for bug reports. Please use the [Discussions](https://github.com/josdejong/mathjs/discussions) section to ask questions and share ideas and suggestions.

**Describe the bug**
I wanted to use the math.js library for my calculator, so I downloaded it through npm. 
I tried to import the evaluate function - import { evaluate } from 'math.js' from my js file, but it didn't work.
It says - Cannot use import statement outside a module.

**To Reproduce**
1) Install mathjs through npm - npm install mathjs
2) Try to import any function from mathjs, like - import { evaluate } from 'math.js' from any js file.

**Comment by gwhitney** [comment]
[Oh, somehow this comment didn't get posted when I added the label; it's basically the same as Jos's] Is the error occurring in the js file where you are importing mathjs? Or is it occurring internal to mathjs? If it is occurring in your js file, is your file in fact a module? If you are executing it via Node, and it has a .js extension, and you do not have `"type": "module"` in your package.json, then Node does not consider your file to be a module and so will not allow top-level import statements. So please check that out and report back here as to whether the problem seems to be internal or external to mathjs.  Thank you.

**Comment by josdejong** [comment]
Closing this issue now due to lack of response. Please reopen if needed.
