### ISSUE TITLE
Become a collaborator of math.js?

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#337]
Hi @rjbaucells and @FSMaxB, 

you guys have done a lot of work for math.js lately, I'm really glad with this! Your contributions are of high quality and well tested. Would you like to become a collaborator on the project, so you can directly push improvements to the project? Of course we still need to discuss new ideas first, and you could for example push new ideas to a separate feature branch first. 

Don't feel forced, but if you like to you're welcome :).

**Comment by FSMaxB** [comment]
I don't dislike the idea of having direct commit access. This would allow me to commit simple fixes more easily. But I would still want to make heavy use of pull requests because your criticism has improved my code a lot.

I can't guarantee though that I stick around forever or that I will be able to continue contributing at the current rate.

**Comment by josdejong** [comment]
Ok great Max, I will add you as collaborator. No need to feel more responsible now or to stick around forever, it's just for convenience and recognition of the work you've done. Indeed the discussions around a PR works nicely, we can just keep doing that.

**Comment by rjbaucells** [comment]
I am in the same position as @FSMaxB, I have been contributing to the project a lot lately but I won't be able to do it at the same pace in the future. Thanks for the opportunity, I will not disappoint you.

**Comment by josdejong** [comment]
Ok thanks Rogelio! I've added you as collaborator. Just have fun as long as there are interesting challenges for you :)
