### ISSUE TITLE
Moving LaTeX definitions from 'lib/util/latex.js' to the individual functions

### ISSUE THREAD

**Issue by FSMaxB** [josdejong/mathjs#391]
Now that the LaTeX definition can be attached to functions themselves via a `toTex` property, I'd like to get rid of the long list in `lib/util/latex.js` and move everything to the individual functions.

This might sound trivial at first, but there are some obstacles.

Many of those `toTex` handlers require access to some of the values in `lib/util/latex.js` like the defaultTemplate, the list of operators, or maybe other things in the future. A naive approach would be to add `var latex = require('util/latex.js');` in every factory function, but as I understand it, this would be a huge waste of CPU time and RAM because every single factory function that needs access to `latex.js` would create it's own copy.

Is there a better, less redundant way to get access to `lib/util/latex.js` in every/most of those factory functions?

**Comment by josdejong** [comment]
If you do `var latex = require('util/latex.js')` from multiple files, the contents of `util/latex.js` is only loaded once in memory, so that's not the biggest concern. It's just quite some extra boilerplate to have to add this require statement in all functions. It's no problem for this subset of "special" operators/functions to need access to latex.js, but it would be nice if we could prevent this for the largest part of the common functions.

We had this discussion in the past, but one way to prevent a lot of boilerplate would be to let functions which do not have a `toTex` property attached automatically use the `defaultTemplate`. You loose information about which files are missing a `toTex` implementation then, which is a pity. 

We could invent some special notation to refer to the default template (like `myFunction.toTex = '${default}'`), but I'm not sure if that doesn't do more harm than good.

From a pragmatic point of view it will probably result in less complexity and less KB's when we just copy/paste the contents of the defaultTemplate (`'\\mathrm{${name}}\\left(${args}\\right)'`) in each of the functions. This is a terrible violation of the DRY principle, but it saves us from quite some indirection and boilerplate. Besides that this string will probably never change anyway (and if so, it's easy to refactor).

I'm not yet sure what's best to do, but I'm always in favor of "keep it simple".

**Comment by josdejong** [comment]
As a side note: thanks to your implementation of the ES6 template notation you should be able to replace templates like:

```
'\\left(${args[0]}\\right)' + exports.operators['pow'] + '{${args[1]}}'
```
with:
```
'\\left(${args[0]}\\right)${op}{${args[1]}}'
```

:D

**Comment by FSMaxB** [comment]
Good to know that require doesn't make a copy. This means that if I change a loaded module in one place it effects every other instance because it's just a reference. This is important information that I've been lacking, this has the potential to cause hard to find bugs if one is not aware of it.

Just copying the default template into the functions isn't that bad I guess, because it means that programmers don't have to look up the default definition and if the default is changed, all of the test cases have to be changed anyway, so I think I'll just do that.

The new template notation does **not** allow me to replace `exports.operators['pow']` with `${op}`. This would require me to first copy the actual operator into a new `op` property of the `FunctionNode`. Shall I add this to the constructor of `FunctionNode`? It would do the following:

1. Check if the current function (`name`) is a key in the list of operators.
2. If yes, copy the operator.
3. If not, use `undefined` thereby triggering an exception in `expandTemplate` if the property is used in a template.

**Comment by josdejong** [comment]
ah of course this `${op}` doesn't work: it needs to give the LaTeX name, not the ascii name... too bad.

I think copying the defaultTemplate everywhere is ok, it's plain and simple solution. How do you think about just leaving `toTex` undefined for functions needing the defaultTemplate (and using unit tests to validate whether the toTex output is ok)?

**Comment by FSMaxB** [comment]
Using the unit tests for that might be ok. The absence of a unit test then means that an output hasn't been specified. So I'll just leave `toTex` undefined in case of the default.

**Comment by josdejong** [comment]
Sounds good to me.
