### ISSUE TITLE
Error : math.eval('32 fahrenheit in celsius') = 5.68e-14

### ISSUE THREAD

**Issue by Jho5943** [josdejong/mathjs#404]
math.js Error

math.eval('32 fahrenheit in celsius') = 5.68

math.eval('31 fahrenheit in celsius') = -0.55555555555549 celsius

math.eval('33 fahrenheit in celsius') = 0.5555555555556 celsius

math.eval('32.01 fahrenheit in celsius') = 0.0055555555555884 celsius

**Comment by josdejong** [comment]
Thanks for your report. I think you're hitting an issue with round-off errors in numbers here.

The actual result of `math.eval('32 fahrenheit in celsius')` is not `5.68` but `5.684341886080802e-14`, mind the `e-14` at the end, which is very close to zero. What you could do is use the function format to round the results:

```
var ans = math.eval('32 fahrenheit in celsius');
math.format(ans, {notation: 'fixed', precision: 4}); // '0.0000'
```

It would be nice if we could extend the units with support for bignumbers and fractions instead of numbers, that would solve this issue for real.

**Comment by Chun5345** [comment]
Actually, it appears that the problem

math.eval('32 fahrenheit in celsius') 

should evaluate to 0

Round-off error does not appear to be a problem.

**Comment by josdejong** [comment]
The returned result `5.684341886080802e-14` *is* a round-off error and *should* return `0` (it's close to zero).

Here is a helper function which will round outputs for you:
```js
/**
 * Format a value as string. Rounds to 12 digits behind the decimal point.
 * Not applicable for small values (in the order of 1e-10 and smaller), 
 * as they are rounded to zero.
 * @param {number | Unit | Complex} value
 * @return {string} Returns a string with the formatted value
 */
function format(value) {
  var str = math.format(value, {notation: 'fixed', precision: 12}); 
                                // string like '0.000000000000 celsius'
  var rounded = math.eval(str); // Unit like 0 celsius
  return math.format(rounded);  // string like '0 celsius'
}
```
