### ISSUE TITLE
Number format, decimal separator / delimiter other than '.'

### ISSUE THREAD

**Issue by darklajid** [josdejong/mathjs#421]
I know that JS is to blame, but maybe it would be worth looking into this - depending on the architecture of the parser stages it might be possible to 'fix' this in math.js?

My culture/localization uses ',' instead of '.'.
I would love to use math.js, but a good deal of my input comes from users and will inevitably look like

    1.500,23 * 17

which currently throws due to the ',' (which is ~understandable~ and safe).

    1.500 * 17

returns 25.5 silently and that's never correct in these locales.

As far as I can tell there is no way to configure math.js for a different locale, right? The documentation doesn't mention this, and if [1] is the right place to look for the parsing of numbers, math.js is straight up using Number()?

It'd be great if you could consider this feature. I apologize if I missed something in the docs.

1: https://github.com/josdejong/mathjs/blob/master/lib/type/number.js

**Comment by FSMaxB** [comment]
This is indeed not possible in mathjs.

I'm German, too, but I really dislike using a comma as decimal separator (not on paper though). But that's not the point here xD.

I've been thinking about ways to achieve this, but it's not possible to replace `,` with `.`, because functions use  `,` to separate their arguments. It wouldn't be defined what `nthRoot(3,3)` means for example. Is it the 3rd root of 3 or is it the 2nd root of `3.3`? That would be ambiguous.

If you know for sure that the input doesn't contain any functions with more than one argument, you can just replace every `,` in the input with `.` using javascripts `String.prototype.replace` function. (and do the same thing backwards for the output).

**Comment by balagge** [comment]
I am Hungarian, which also uses comma for decimal separator. The standard solution in applications (like Excel, LibreOffice and the like) is to define a decimal separator and a list separator as well. If you change the decimal separator to "," comma, then you also have to change the list separator to something else (usually ";" semicolon). 

However, mathjs also uses semicolon for a second-level list separator, so this is not really a good idea.

I also happen to have a degree in mathematics, and normally (at least in my country) the decimal point is acceptable as decimal separator in mathematical context.

I have seen some technical / engineering texts rendered for print that use comma (which is linguistically the "correct" decimal separator), but that standard is only followed in actual print. (In which case the Excel solution of ";" as list separator is NOT usually followed. Instead, the spacing around the decimal comma would be different than the spacing around a list separator comma, I guess).

**Comment by josdejong** [comment]
Here in the Netherlands it's the same, comma's are normally used as decimal separator.

There is an example on how you could customize separators using a simple regular expression:

http://mathjs.org/examples/browser/custom_separators.html (live)
http://mathjs.org/examples/browser/custom_separators.html.html (code)

You should indeed be careful with what you replace the characters, as the replacement may conflict with other existing operators or separators.

**Comment by josdejong** [comment]
I suppose we can close this issue?
