### ISSUE TITLE
Find best prefix for derived units like `m^2`

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#435]
It would be nice if derived units would also be able to find the best prefix. 

```js
math.eval('3.2e6 m^2'); // returns 3.2e+6 m^2, could return 3.2 km^2 instead
```

In cases of a single unit having an exponent like `m^2` or `m^3` this is relatively straight forward. I'm not sure if we also would like to do this for derived units like `2.3e7 m/s` (how to distribute the prefixes over the units?).

**Comment by ericman314** [comment]
I think given the current behavior for single plain units, I would expect single units raised to a power to also find the best prefix. But with multiple units, how can we know what the user wants to see? It all depends on the context of the problem, which only the user knows. Velocities, for example, are almost always given in something like `m/s`, `km/s`, or `km/h`. You probably wouldn't ever see anything like `Mm/s` or `m/us`. We could go nuts trying to guess what the user wants, using heuristics or something, only to guess wrong one time out of ten and leave the user scratching his head.

IMHO, the output should be as predictable as possible. The current behavior is to preserve as many of the original units as possible that the user supplied, so that `1000 m / s` evaluates to `1000 m / s` and `1 km / s` to `1 km / s`. If the user wants more help beyond that, then we give them plenty of tools to convert the unit to something else, like the `to` operator does now. There could be some kind of "to SI" function that converts `W` into `kg m / s^3`, for example. Perhaps we could even add a function to provide suggestions for what the unit could be converted to (filtered by best prefixes?!), which for `30000 W` might suggest `kW` or `kJ / s` or `hp` or even `MMBTU / day`, while for `0.00003 W` might instead suggest `uW` or `erg/s`. If the user attempts to convert a unit to a non-matching unit, the error message itself could even offer a suggestion:

```js
math.eval('40 hp to J'); // Error: Units do not match. (Did you mean "J / s"?)
```

**Comment by josdejong** [comment]
Thanks, I agree. For units like m^2 it will be nice to get a matching prefix. For units like m/s the current behavior of preserving the provided units is best. You can indeed always convert yourself. Hints in case of invalid input is always nice of course, but we should not overthink

**Comment by josdejong** [comment]
Sorry pressed the close button...

**Comment by ericman314** [comment]
I've ran into a little snag where the prefix on one of the physical constants is changed by `_bestPrefix`:
```js
math.type.Unit.parse('1.1663645e-5 GeV^-2')   // 11.663645 TeV^-2
```

There's a few directions we could take:
- Do nothing and accept that occasionally the prefixes for a physical constant will change
- Manually set the `fixPrefix` flag for each physical constant
- Change the behavior of `Unit.format` so that `_bestPrefix` is only called when the unit list is simplified:
```js

math.type.Unit.parse('0.000001 J');   // 1e-6 J
math.type.Unit.parse('0.000001 N m'); // 1e-6 N m
math.eval('0.000001 J');   // 1e-6 J
// _bestPrefix is called here after the multiplication triggers a call to simplifyUnitListLazy
math.eval('0.000001 N m'); // 1 uJ   
```

The last option changes the behavior considerably, but I think the behavior is actually more predictable as the prefixes only change when the units are simplified. What do you think?

**Comment by josdejong** [comment]
I'm not sure if it's a problem when the prefix of physical constants is changed by `_bestPrefix`. Both representations are just valid representations. I agree that in some cases the representation may be less recognizable as you may be used to see `fermiCoupling` in `GeV^-2`, and `electronMass` in `kg`. On the other hand, it may be confusing too that in some cases it seems like `_bestPrefix` works, and in other cases not, the behavior may be less transparent from a user point of view. I'm afraid though that your third option will be confusing (though the logic behind it is understandable).

I'm ok with both your options 1 (always adjust prefix) and 2 (set `fixPrefix` true for physical constants), and have a slight preference for 2 (when creating a little helper function to parse a unit and set fixPrefix to true, we hardly have any overhead in the code).

**Comment by ericman314** [comment]
See PR #438
