### ISSUE TITLE
Getting leading zeros when displayMode = 'exponential'

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#455]
I have the code below to evaluate 5555 * 5555:
   var result = mathjs.eval('5555 * 5555');
   var disResult = mathjs.format(result, { notation: _displayMode, precision: 11});

When _displayMode = 'auto', I get the disResult = 3.0858025e+7  
but, when _displayMode = 'exponential', I get the disResult = 3.0858025000e+7

How can I get results back without leading zeros when _displayMode = 'exponential'?

**Comment by ericman314** [comment]
I'm guessing you are getting the zeros because you include `precision: 11` as an option. If it works for your specific application, then removing the `precision` option should eliminate the trailing zeros.

However, I think you might have uncovered a real issue. The docs state:

> `precision: number` A number between 0 and 16 to round the digits of the number. In case of notations 'exponential' and 'auto', `precision` defines the total number of significant digits returned....

This means both 'exponential' and 'auto' should be returning `3.0858025000e+7`, 11 significant digits. @josdejong, is this an error in the docs or in the code?

**Comment by josdejong** [comment]
@ericman314 the `"auto"` mode indeed doesn't output trailing zeros, it was meant to output numbers in a way that's easy for the eye. We should describe this more accurately in the docs.

@sonnyk22 this is a use case not covered by `math.format`. You could write a regexp to remove the trailing zeros of the formatted value.

**Comment by sonnyk22** [comment]
Thank you!
