### ISSUE TITLE
Reactive/aparent power and energy units

### ISSUE THREAD

**Issue by vonbloom** [josdejong/mathjs#476]
It would be usefull to add support for reactive/apparent power (VAR, VA) and energy (VARh, VAh) units.

https://en.wikipedia.org/wiki/AC_power

**Comment by ericman314** [comment]
I agree! Would you assign VA and VAR a value equivalent to W, or did you have something else in mind?

Along the same lines it would be nice to support complex units too. I believe complex arithmetic can be useful for three-phase power calculations, etc. There's been a bit of discussion on this here: #424

**Comment by vonbloom** [comment]
I woluld assign VA/VAR a value equivalent to W and VAh/VARh a value equivalent to Wh.

Thanks for the link to that discussion.

**Comment by FSMaxB** [comment]
I think this might need some more discussion.

I'm not entirely sure if VAR should just be a regular unit with real values. It might actually make sense to make it an imaginary unit. Then you could add W and VAR together and get W, for example (if this is even possible with the current Unit nodes).

**Comment by ericman314** [comment]
Good point. This is indeed tricky.

When you add reactive power (an imaginary value measured in `var`) to real power (a real value measured in `W`), you get apparent power (a complex value measured in `VA`). The absolute value of each unit is the same: `1 W`. But, engineers use the three different units to help keep track of which type of power (reactive, real, or apparent) they are talking about.

Good suggestion to define `var` as `(0 + i) W`. When a user writes `5 W + 5 var`, the result should be `(5 + 5i) W`. But if the user types `abs(5 W + 5 var)`, the evaluator should return ~` 7.07 VA`. Could the implementation of `abs` for `Units` recognize when a result should be expressed in `VA`?

**Comment by FSMaxB** [comment]
Oh, I meant W + VAR = VA of course, not W as in the comment earlier.

I don't know if abs can even do this. It would have to detect an OperatorNode with Units of the type W and var and create VA from that.

I'm not entirely sure right now how a sum of reactive and active power is represented unit-wise, it might just be VA with a complex value.

**Comment by josdejong** [comment]
Nice discussion, I've only basic knowledge about calculations with electricity, now I understand why @ericman314 wanted to add support for complex numbers in units in the first place. 

Isn't the issue with `abs` solvable by checking for the "special" case where the input is a complex unit in `W`, and in that case output a unit in `VA`?

**Comment by ericman314** [comment]
Perhaps we should also discuss how we will implement complex units generally, as this will have a strong effect on how we handle VA and VAR. I think the biggest issue we've identified so far is which types will depend on which.

@josdejong, I think that can work. Once we have an idea what the implementation will look like I'm sure it will become more clear the direction we should take with this.

**Comment by josdejong** [comment]
I think extending units with support for complex values will roughly mean the following:

- `Unit.value` property can now contain a `number` or `Complex` value.
- All calculations that operate on `Unit.value` should now use math functions like `math.add` and `math.multiply` instead of native operators like `+` and `-`, so they can automatically handle both `number` and `Complex`.
- The constructor of Unit needs to check whether the input value is a number or a Complex, and only allow a Complex value for units that support it (i.e. `VAR`).
- `Unit.toString` needs to support formatting a Complex value.
- Functions like `abs` that need to handle complex units in some special way need to be adjusted/extended.

**Comment by josdejong** [comment]
I've extended `Unit` with support for other numeric types (`BigNumber` and `Fraction`), it's in the `develop` branch. I expect it's now relatively easy to implement support for `VA` and `VAR`. Anyone interested in picking this up?

**Comment by ericman314** [comment]
Awesome, I'll check it out!

**Comment by ericman314** [comment]
I've added complex units; see #515. I haven't added the `VAR` and `VA` units yet, this PR is just to get complex units working.

**Comment by josdejong** [comment]
Thanks Eric, great. I'm wondering does it make sense to support complex values *always*, or do we only want to support complex values only for these specific units `VAR` and `VA`? Are there use cases where you want a complex valued weight like `"(2 + 3i) kg"`?

**Comment by ericman314** [comment]
Although I honestly don't think there are very many uses for complex units, I think general support for complex units is best.

Sometimes, getting a complex result for a calculation in which you expected to get a real result can be helpful in debugging your problem--where otherwise you would just get `NaN`. Say, for example, calculating the time for a projectile to reach a certain height `y`, if it has insufficient velocity your result might be `(34 + 5i) s` or something, giving you a hint that you've got the square root of a negative number in there somewhere.

Allowing complex units everywhere makes for a more feature-complete library; I think it's something a few people would expect to have.

**Comment by FSMaxB** [comment]
There are cases where virtual masses with negative values are used (in semiconductor physics for example), there might be cases for other units as well that require the use of numbers that would normally be undefined for that particular unit.

**Comment by josdejong** [comment]
Well, even when not very useful it won't hurk to allow support for complex numbers in general - it will cost hardly any code. Ok then let's allow complex numbers in units just for all cases.

**Comment by josdejong** [comment]
I think we can close this issue? Support for VA and VAR is implemented.
