### ISSUE TITLE
Open sourcing mathnotepad.com

### ISSUE THREAD

**Issue by oeb25** [josdejong/mathjs#487]
Have you thought about open sourcing mathnotepad.com?

I'd like play around with it, since there's some features I'm missing.

__Some of the features I'd like to have a look at__
- Export as image/pdf for tossing around. Personally needed for school assignments.
- Online storage _(at google drive maybe)_

**Comment by josdejong** [comment]
Thanks for your questions and ideas. Well, the largest part of Math Notepad is already open sourced, it's called math.js ;). I could for example open source the graphing part as a separate library some day too. 

Since math.js v2.0 was released, I'm putting effort in bringing Math Notepad to the next level, it's still not a v1.0. Copying/pasting calculations from other applications sucks for example. 

The good news: I'm currently working on online storage, I expect that to be finished in less than a month. Also implementing proper history (undo/redo), that's 90% done.

**Comment by Nekomajin42** [comment]
Will you release an API for Math Notepad? Opera has a sidebar, and and it would be good to implement a powerful commandline calculator.

**Comment by josdejong** [comment]
Do you mean like the the [command line interface of math.js](http://mathjs.org/docs/command_line_interface.html) (in the terminal), or more like the demo calculator on the [front page of the mathjs.org website](http://mathjs.org/index.html) (in a browser)?

**Comment by Nekomajin42** [comment]
I mean something like the mathnotepad.com interface without the surroundings.

**Comment by josdejong** [comment]
ah ok. You sort of can by using embedding the editor in your webpage, but it doesn't have an API. Sounds interesting/useful to create an API for this embedded editor.

**Comment by josdejong** [comment]
Hurray! [Math Notepad](http://mathnotepad.com) now supports storing your documents online. In a next stage, I will extend it with support for sharing with others, making a (readonly) version of your docs publicly available and have some registry for it where you can find docs from others, load/import docs into your current document, etc.
