### ISSUE TITLE
Best way to handle cos(270 deg)

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#494]
Presently, the MathJS library is returning a non-zero value for the following trig expressions in the DEG mode:

![calc1](https://cloud.githubusercontent.com/assets/6744710/10772305/d64f2d64-7ccb-11e5-8c30-f213e800a22b.png)

What is the best way to get a value of 0 returning?  Is there a special configuration settings in the MathJS.Config() function?

![calc2](https://cloud.githubusercontent.com/assets/6744710/10772351/104a1376-7ccc-11e5-9d1f-c95de4f07256.png)

**Comment by FSMaxB** [comment]
Take a look at #447.

**Comment by sonnyk22** [comment]
I tired doing it as instructed, but unfortunately it does not give me a 0 value.  I am using the below configuration settings:

![calc1](https://cloud.githubusercontent.com/assets/6744710/10773654/01e31434-7cd3-11e5-8ce3-6a2d9c027a60.png)

**Comment by josdejong** [comment]
There are multiple things going on here:

- The version of math.js that jsbin was using was very old and contained a bug with `cos`. I updated this. Sorry for that.
- I think you mean to do `math.eval('cos(90 deg)')` instead of `math.eval('cos(90)')`.
- Unfortunately, `math.eval('cos(90 deg)')` will fail for bignumbers: Units do not yet support BigNumbers or Fractions (or Complex numbers). Adding support for this is on the to-do list.

For solving round-off errors, see my comment in #491.

**Comment by sonnyk22** [comment]
The MathJS.round(x, n) function mentioned in #491 worked out perfectly for me to solve this issue.

Thank you!
