### ISSUE TITLE
How to represent a unit that is a ratio?

### ISSUE THREAD

**Issue by napalm272** [josdejong/mathjs#504]
Thanks for this great library.  I have been experimenting with the unit module and I wonder how would I represent a unit that is a ratio.  For example, the unit for humidity is usually % or part per million.  
It's probably a stupid question, but any help or hint is really appreciated.

**Comment by ericman314** [comment]
It's a great question. See #492 for a good discussion (several solutions near the bottom). 

Making `ppm` or `percent` a unit might work in simple expressions, but an expression like `exp(5 ppm)` would fail because the `exp` function currently doesn't support units. Instead, you could create a variable named `ppm`:

```js
var scope = {ppm: 1e-6};
var ans = math.eval('5 ppm', scope); // 5e-6
```

**Comment by ericman314** [comment]
However, if you would like to experiment, you could add a unit like `ppm` to the list of units in `Unit.js`:

```js
 ppm: {
      name: 'ppm',
      base: BASE_UNITS.NONE,
      prefixes: PREFIXES.NONE,
      value: 1e-6,
      offset: 0
    },
```

**Comment by napalm272** [comment]
Thanks, I think I'll modify Unit.js because I need to use the unit.to function.  I've read #492 and saw the potential problem, but I don't think I'll run into those issues.
