### ISSUE TITLE
consider adding matrix.transpose

### ISSUE THREAD

**Issue by mbana** [josdejong/mathjs#580]
I've been using the library lately. Thanks for making it available.

Is there a reason why the math.transpose isn't part of the matrix object itself?

I could submit PR, if you want?

**Comment by hgupta9** [comment]
Transpose is a function under the "math" namespace. We encourage all users to use that notation instead of using the public object API. See [transpose()](http://mathjs.org/docs/reference/functions/transpose.html) and [this list](http://mathjs.org/docs/reference/functions/categorical.html) for more functions.

**Comment by josdejong** [comment]
@hgupta9 is right, math.js mostly uses static functions rather then class methods. However, we're shifting towards an architecture where most methods are defined on the class, which can be an external project like [bignumber.js](https://github.com/MikeMcl/bignumber.js/) and [fraction.js](https://github.com/infusion/Fraction.js/), and the functions of math.js are more and more wrapper functions without logic (except for type conversion logic).

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time. Feel free to reopen if needed.
