### ISSUE TITLE
math.eval('tan(pi/2)') gives 16331239353195370 instead of Inifinity

### ISSUE THREAD

**Issue by q2apro** [josdejong/mathjs#589]
Using: 

	console.log(math.eval('tan(pi/2)'));

gives 

	`16331239353195370`

instead of Inifinity.

**Comment by josdejong** [comment]
math.js is a numeric application, and numeric applications have these round-off issues around zero and infinity. For example `math.eval('tan(pi)')` returns `-1.2246467991473532e-16` instead of `0`. 

The BigNumber trigonometric functions in math.js had some nifty edge case checking for these cases, but these will be removed in v3 in favor of a simple straightforward numeric implementation. 

The only solution here is to use a computer algebra system instead, which does do symbolic computation (search the issues section for this). We are working on that but it will take time.

**Comment by q2apro** [comment]
Thanks for the info. I thought this would be the problem. So until the new implementation, I would suggest to leave this issue open.

**Comment by josdejong** [comment]
I think we can close it, we have issues open to implement a CAS.

I'm thinking about adding an FAQ to the docs though to even more thoroughly explain the limitations of numeric calculation, many people have questions around round-off errors.
