### ISSUE TITLE
Proposal: design API with performance in mind

### ISSUE THREAD

**Issue by garrison** [josdejong/mathjs#59]
Have you considered making performance/speed an explicit goal of math.js?  For instance, if you were to require all matrices to have all numbers of a specified type (as e.g. numpy does), then you could in the future use [typed arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays) or even call into BLAS libraries using [node-ffi](https://github.com/rbranson/node-ffi) to gain additional performance advantages.  It will require some API changes, but could very well be worth it.  Even if we don't work directly on performance at the moment, refactoring parts of the API in ways that would allow them to be implemented with high performance could be quite useful in preparing for future growth.

**Comment by rreusser** [comment]
@sebpiq @garrison @josdejong — Sorry to bother you, but looks like you expressed interest in numpy-style ndarrays a couple years back and in the roadmap. Did you make or are you aware of any progress on this front? Just a couple days into implementing [my own math/science library](https://github.com/rreusser/spacetime.js), I've already realized that if I don't either use or build a coherent API that confronts the issue of real and complex matrices and vectors, then my effort is probably going to be wasted.

On a larger note, it seems like maybe asm.js + C/C++ is the one true future of trying to use JavaScript for math/science stuff. I could give it a couple years and wait until someone bites the bullet and compiles numpy into javascript, but whatever the solution is, I don't want to wait that long. Life is short. I'm on a sabbatical of sorts, so I have the bandwidth to work on this; I just don't want to waste my effort.

I totally understand if rewriting numpy isn't the aim of math.js, but I do think there's a need for some means of doing real-ish computation in JS (because JS excels where other languages fail—easily communicating content to large audience) so I'd love to hear thoughts or ideas on how to get there.

**Comment by josdejong** [comment]
@rreusser thanks for your feedback. I've read the introduction of your math library, it's exactly the same reason why I started math.js in the first place! It's indeed not the goal to create an exact clone of numpy, but numpy is a great source of inspiration here. We want to create a toolbox for advanced mathematics, and integrate working with various data types (like matrices, complex numbers, etc).

Right now math.js supports multidimensional (mixed) matrices, and 2d sparse matrices (implemented recently by @rjbaucells). We're right now refactoring the code into a modular structure (see discussion on [modularization](https://github.com/josdejong/mathjs/issues/280) and on [v2](https://github.com/josdejong/mathjs/issues/279)). When we are there it will be straight forward to implement support for typed arrays (homogeneous), which can improve performance a lot (no type checking needed for example).

I think it's important to keep the library available for both node.js and browsers, which means that we cannot just put functionality in C/C++ (though it could be implemented as a progressive enhancement for node.js environments). Optimizations like with asm.js and maybe object pools may help too in improving performance. 

Currently math.js offers a stable, powerful API, a broad base of basic mathematical functions, and supports the most commonly used data types. Next level is to implement more advanced maths functions, and to improve the performance. Think numerical functions like `lup` and `lusolve` which is recently implemented by @rjbaucells too). Integration and differentiation will be awesome, and CAS in general (see #87, #35, #38).

Feel free to email me to change minds on your intentions and ideas via github or by mailing me. It would be great to have a new contributor on the project :).

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time
