### ISSUE TITLE
eval fails at sin^2(x deg)

### ISSUE THREAD

**Issue by chmln** [josdejong/mathjs#619]
`math.eval("sin^2(x deg)",{x:45})` gets parsed correctly 
![screenshot_2016-03-21_23-43-25](https://cloud.githubusercontent.com/assets/11352152/13941509/c0195aea-efbe-11e5-8fa1-79d19a5b0946.png)

but fails
```
TypeError: Unexpected type of argument in function pow (expected: number or Complex or BigNumber or Fraction or Unit or Array or Matrix, actual: function, index: 0)
    at createError (.../node_modules/typed-function/typed-function.js:135:17)
    at Object.pow (eval at _typed (.../node_modules/typed-function/typed-function.js:1042:22), <anonymous>:491:9)
    at Object.defs.eval (eval at <anonymous> (.../node_modules/mathjs/lib/expression/node/Node.js:68:19), <anonymous>:3:303)
```

on the other hand
`math.eval("sin(x deg)^2",{x:45})` works properly

but it is quite misleading imo
![screenshot_2016-03-21_23-45-38](https://cloud.githubusercontent.com/assets/11352152/13941621/9c10c6e6-efbf-11e5-96e5-42b16f3e39f7.png)

Is there a solution apart from force showing all parentheses? 

Thank you.

**Comment by josdejong** [comment]
I think the confusion is in that there is an implicit multiplication here, `sin^2(x deg)` is evaluated as
`sin ^ 2 * (x * deg)`.

Since the latest version, v3.1.0, there is a new option `implicit` for `toString` and `toTex` to show or hide implicit multiplications. I think that would help. See docs:

https://github.com/josdejong/mathjs/blob/master/docs/expressions/customization.md#implicit-multiplication

**Comment by josdejong** [comment]
Is this still an issue?
