### ISSUE TITLE
Incorrect LaTeX for some predefined functions when passing the wrong number of parameters

### ISSUE THREAD

**Issue by FSMaxB** [josdejong/mathjs#636]
I just noticed a bug in the LaTeX output. Let's say you parse `sin(a,b) = a+b; sin(1, 2)` and run `toTex()` on it, the result is `'\\mathrm{sin}\\left(x,\\mathrm{y}\\right):= x+ y;\\;\\;\n\\sin\\left(1\\right)'`. The last occurence of `sin` misses the second parameter.

This happens because `sin` provides a template for LaTeX generation that only uses one parameter: `'\\sin\\left\\(${args[0]\\}\\right)'`.

I have no idea how to fix this without doing one of the following:
* keeping track of redefined functions and disabling the LaTeX-Templates for them (ugly)
* change every single function that supplies it's own LaTeX-String to support all numbers of arguments. (much work + ugly)
* Let the parser modify the `.toTex` properties of functions once they are redefined (can't do this because of it's side effects on the global mathjs instance)

Or we could just ignore this issue and hope that no one actually redefines one of the functions that provide a custom LaTeX output and still expects it to behave correctly with `toTex()`.

**Comment by josdejong** [comment]
wow, that's a tricky one. I doubt whether this would ever occur in practice but it is not impossible. 

I think that your second option is best: change the LaTeX template of all functions to display all arguments (`'\\sin\\left(${args}\\right)'`) instead just one or two. I don't think this is a particularly ugly solution, what do you find ugly about it?

It would be a relatively simple refactoring though we need to be careful to replace only the right occurrences. I can do the refactoring, this is easy to do with WebStorm.

**Comment by FSMaxB** [comment]
It's ugly in two regards:

1. It needs to be done for every single function that defines it's own LaTeX output, even ones that will be added in the future.
2. It makes the template language I introduced quite pointless for most functions, because you would suddenly need to distinguish between different amounts of arguments thereby requiring a dedicated handler function that handles those cases separately.

**Comment by josdejong** [comment]
Thanks for your clear arguments. Yes for functions we will have to use `${args}` instead of `${args[0]}`, but I don't see a problem there. What I find more important is a solution which does not silently hide  information from you, even if the information is partly invalid like `sin(1,2,3)`. It's up to the user to fix that but if you hide this from the user, he has no way to know about it and fix it.

The template language is an will be essential for all operators and some special functions like `nthRoot` and `combinations`. But we should not use the template stuff for the sake of using it but where it's appropriate and needed.

**Comment by FSMaxB** [comment]
I don't understand what you mean by "hiding information".

But reading the code I just noticed, that the solution to the problem I described doesn't actually require a handler function. It should be as easy doing this for all functions (all other numbers of arguments will automatically fall back to the default template):

```js
sin.toTex = {
  // LaTeX-Template for 1 argument
 1: '\\sin\\left\\(${args[0]\\}\\right)';
}
```

See [FunctionNode line 354](https://github.com/josdejong/mathjs/blob/26e1e26555b81b753d84eeb2bf6b99047e5682e6/lib/expression/node/FunctionNode.js#L354).

I didn't even remember that I wrote this, but now that I see it, I kind of remember using it for the LaTeX output of some of the functions, not sure which though.

**Comment by FSMaxB** [comment]
I'm not sure why this isn't documented. We'd have to take a look at the discussion we had at the time. My guess is that it shouldn't be considered part of the API so it wasn't documented, but I'm not sure.

**Comment by josdejong** [comment]
Ah, indeed :). I don't know why it's wasn't documented.

With "hiding information" I just mean that if you input say `sin(1,2,3)`, and call toTex, the tex representation shows `sin(1)` and hides the last two arguments from you, which can give confusion since these two arguments are actually there.

So there are two options to replace the current templates:

```js
sin.toTex = '\\sin\\left\\(${args[0]\\}\\right)';
```

- option 1

    ```js
    sin.toTex = {
     '1': '\\sin\\left\\(${args[0]\\}\\right)';
    }
    ``` 

- option 2

    ```js
    sin.toTex = '\\sin\\left\\(${args\\}\\right)';
    ```

Option 1 is most correct, but it contains a bit more magic. I have a slight preference for option 2 since that's simpler to understand and we're talking about an edge case only. I don't have a strong opinion here. What has your preference?

**Comment by FSMaxB** [comment]
I strongly prefer option 2 because most LaTeX templates that were defined manually don't make too much sense if you extend them to support a variable number of arguments and users will probably expect their overwritten functions to have the default LaTeX output.

Also many of the templates can't even be extended to support variable numbers of arguments because the LaTeX output would simply break or make no sense at all. Like `'\\left(${args[0]}' + latex.operators['xor'] + '${args[1]}\\right)'` or `'\\binom{${args[0]}}{${args[1]}}'`.

**Comment by josdejong** [comment]
Ok lets go for option 1 then :)

**Comment by FSMaxB** [comment]
I won't have the time to do this refactoring in the near future. You would either have to do it yourself or you'd have to wait a while until I find the time (which might be ok since this bug doesn't seem to critical).

**Comment by josdejong** [comment]
I think I can do it, maybe this weekend. It's indeed not critical.

**Comment by josdejong** [comment]
I've gone through all functions and made the `toTex` templates more strict, reckoning with the number of arguments.

I've left the functions which had the default template (`'\\mathrm{${name}}\\left(${args}\\right)'`) as they are, since some of them accept different numbers of arguments and it doesn't really help to make the `toTex` conditional since it falls back to the default template anyway. 

Just thinking, maybe we should change the functions that use the default template:

```js
format.toTex = '\\mathrm{${name}}\\left(${args}\\right)';
```

to something like:

```js
format.toTex = undefined;  // use default template
```

That way you get information that this function is using the default template, and it probably saves a few bytes of the bundle.

**Comment by FSMaxB** [comment]
Will this get stripped during the minification? Otherwise maybe remove the line entirely.

But I like the idea of explicitly stating that the default template was used. Thereby it is possible to distinguish between cases where a proper `toTex` is still missing and cases where the default template was intended.

**Comment by josdejong** [comment]
> Thereby it is possible to distinguish between cases where a proper toTex is still missing and cases where the default template was intended.

yes exactly, and we shouldn't loose that.

This shouldn't be stripped when minifying: the minifier cannot just decide to drop a property of an object because it's (initial) value is undefined. That would alter the behavior of for example `Object.keys(obj)`.

Ok I will refactor the places where the default toTex is used to `format.toTex = undefined`.

**Comment by josdejong** [comment]
Done in https://github.com/josdejong/mathjs/commit/b2066e53f64ff0ccfcdabd31ca9476ba68e28c86
