### ISSUE TITLE
The expresson "acsc(1 deg)" throws an error

### ISSUE THREAD

**Issue by Ixus** [josdejong/mathjs#655]
The trig function **acsc** doesn't seem to work with units.

![mathnotepad bug trig function acsc](https://cloud.githubusercontent.com/assets/4968907/15088323/500a8a70-13af-11e6-9866-bc487119d02d.png)

Edit: I browsed through the code and a few of them don't support units.

**Comment by ericman314** [comment]
That is correct. While the standard trig functions (sin, cos, tan, etc.) take an angle as the argument and return a ratio, the inverse trig functions (the ones that start with "a") take a ratio as the argument and return an angle. 

For example:

```
sin(30 deg)
  0.5

asin(0.5)
  0.5235987755983

asin(0.5) rad to deg
  30 deg
```

The default output from the inverse trig functions is in radians. Math.js doesn't insert units onto the results of the inverse trig functions because it would be unexpected and outside of most people's use cases. But as seen in the third example, you can add an angle unit and/or convert the result to degrees yourself.

**Comment by Ixus** [comment]
Right. That makes sense. I completely forgot about how that works. Thank you for clarifying that for me.
