### ISSUE TITLE
SIMD plans

### ISSUE THREAD

**Issue by s4sarishma** [josdejong/mathjs#675]
Do you have plans to implement the matrix APIs using SIMD.js?

**Comment by josdejong** [comment]
Not directly: first we have to change the library such that it can utilize Typed Arrays (refactor the format of DenseMatrix into a flat structure rather than the current nested structure). That will probably give a much larger performance boost. Looking into SIMD could be next, I currently don't have a clear picture on whether that would be feasible and what will be involved.

**Comment by s4sarishma** [comment]
Thanks for the reply.
