### ISSUE TITLE
Implement erf function

### ISSUE THREAD

**Issue by SWE-DZP** [josdejong/mathjs#678]
I have tried my best to find erf function, but failed. So， is there one ?

**Comment by josdejong** [comment]
This function isn't yet available in math.js. I will mark this as a feature request, thanks for your input.

**Comment by solo474** [comment]
Thanks for the implementation of **erf** function. because of this I'm able to write gaussian distribution function as follows `(1 - erf((m - x ) / (Math.sqrt(2) * sd))) / 2` 

It is good to have **inverse** **erf** function so some thing like this ![image](https://user-images.githubusercontent.com/13312112/97104227-0d666d80-16aa-11eb-9f41-c44fa60ae076.png) quantile function of gaussian distribution can be implemented.

**Comment by josdejong** [comment]
Thanks for your suggestion @solo474 . Can you please open a separate issue for this titled "Inverse erf function" or something like that?

(this issue is a merged, finished PR, so we do not clearly see that there is another feature request here)

**Comment by solo474** [comment]
Created a new issue here #2011
