### ISSUE TITLE
support for mixed fractions (e.g. '3 4/5')

### ISSUE THREAD

**Issue by makarandkarkare** [josdejong/mathjs#693]
There was a issue filed for this (#370) but I think it was mistakenly closed.

May be inclusion of a new operator (&) can solve this issue. This operator can be treated like a + operator during evaluation, but treated differently while converting  toString, or toTex

Please check the calculator at this link https://mathpapa.com/algebra-calculator.html
Here, you can enter 3&4/5 and it shows it correctly as a mixed fraction, and also treats it correctly as one.

**Comment by josdejong** [comment]
Ah, that's a funny notation: `3&4/5`, thanks for sharing this idea :)

There is one practical problem though: the `&` is already in use for [bitwise and](http://mathjs.org/docs/expressions/syntax.html#operators).

We could indeed use something like this to change displaying an expression like `3+4/5` in LaTeX like `2 \frac{4}{5}` but still it would be ambiguous what this means then: implicit addition or multiplication? I'm not sure whether that's a good idea.

**Comment by makarandkarkare** [comment]
That is the reason I am suggesting using a new operator, rather than overloading the +. Then there is no ambiguity. If & is already taken, may be we can use something else like an _ (underbar).
My two bits. :)

**Comment by josdejong** [comment]
Yes that's a good point and definitely a solution. 

I'm in doubt though whether that would be worth it: it's quite a specific use case and as far as I know there is no "standard" notation for this so nobody will know about this notation, and when people see this notation used somewhere they will not know what it is about, and using this notation will give lock-in since no other applications use this syntax. 

It's an interesting idea but I think it's best to stick with using an explicit plus character and parenthesis in these cases. Unambiguous and understood by everyone and everything.

**Comment by josdejong** [comment]
I will close this issue now.
