### ISSUE TITLE
Modifying the transpose function to support vectors

### ISSUE THREAD

**Issue by pabloahb** [josdejong/mathjs#706]
Hi, I am trying to modify the transpose function to support vectors. The code that I have made actually works very well with row and column vectors, but when I run the test before pulling the changes I'm getting this error:  

1) transpose should transpose a vector:

      AssertionError: [ [ 1 ], [ 2 ], [ 3 ] ] deepEqual [ 1, 2, 3 ]
      + expected - actual

       [
      -  [
      -    1
      -  ]
      -  [
      -    2
      -  ]
      -  [
      -    3
      -  ]
      +  1
      +  2
      +  3
       ]

      at Context.<anonymous> (C:\Users\inint\Downloads\mathjs-master\test\function\matrix\transpose.test.js:13:12)
      at callFn (C:\Users\inint\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:334:21)
      at Test.Runnable.run (C:\Users\inint\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:327:7)
      at Runner.runTest (C:\Users\inint\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:429:10)
      at C:\Users\inint\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:535:12
      at next (C:\Users\inint\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:349:14)
      at C:\Users\inint\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:359:7
      at next (C:\Users\inint\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:14)
      at Immediate._onImmediate (C:\Users\inint\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:327:5)

_________________________________________________

In some cases, the transpose function must admit column vectors (and return a row vector) and return colum vectors (if the input is a row vector). Then, I don't know what to do.

This is the code.

@@ -49,7 +49,29 @@ function factory (type, config, load, typed) {
       switch (size.length) {
         case 1:
           // vector
|-          c = x.clone();
|+          var columns=size[0];
|+          var rows=1;
|+          var data = x._data;
|+          // transposed matrix data
|+          var transposed = [];
|+          var transposedRow;
|+          // loop columns
|+          for (var j = 0; j < columns; j++) {
|+          // initialize row
|+            transposedRow = transposed[j] = [];
|+            // loop rows
|+            for (var i = 0; i < rows; i++) {
|+            // set data
|+            transposedRow[i] = clone(data[j]);
|+            }
|+          }
|+          
|+          // return matrix
|+          c = new DenseMatrix({
|+          data: transposed,
|+          size: [columns, rows],
|+          datatype: x._datatype
|+          });
           break;
 
         case 2:

Thanks

**Comment by josdejong** [comment]
Math.js uses [geometric dimensions](http://mathjs.org/docs/datatypes/matrices.html#size-and-dimensions), so it's behavior for transposing a vector like `[1,2,3]` is to return the vector unchanged since it has only one dimension. A vector with two dimensions like `[[1,2,3]]` is transposed to `[[1],[2],[3]]` and vice versa. 

If I understand you correctly you want to change this behavior, and convert input vectors with 1 dimension to 2 dimensions first and then execute the transpose? That will indeed break existing unit tests since you change the behavior.

**Comment by pabloahb** [comment]
Hi. 
The transpose of a row vector is a column vector and the transpose of a column vector is a row vector.
Then returning the vector unchanged is only valid for 1x1 vectors.
The transpose of [1,2,3] is not [1,2,3]. 
That answer is against the definition of the transpose function.

https://en.wikipedia.org/wiki/Row_and_column_vectors

To transpose [1,2,3] (fulfilling the definition of the transpose function) you have to take each element (column) and put it in a row of a Matrix. 

I am working in the following code:

...
case 1:
// vector
var columns=size[0];
var rows=1;
var data = x._data;

// transposed matrix data
var transposed = [];
var transposedRow;

// loop vector elements
for (var j = 0; j < columns; j++) {
	// initialize row
	transposedRow = transposed[j] = [];
	// set data
	transposedRow[0] = clone(data[j]);
}

// return matrix
c = new DenseMatrix({
data: transposed,
size: [columns, rows],
datatype: x._datatype
});

 break;
...

Thanks
MathJS is great!!!!

**Comment by josdejong** [comment]
Thanks, glad you like mathjs :). 

In math.js you can have:

- row vectors like `[[1,2,3]]` having 2 dimensions `[1, 3]`
- column vectors like `[[1],[2],[3]]` having 2 dimensions `[3, 1]`
- and... just vectors, like `[1,2,3]`, having 1 dimension `[3]`

The transpose of a 1 dimensional vector is itself, like the transpose of a scalar value returns itself.

I don't know how I can help you: as far as I understand you want to change the behavior of transposing one dimensional vectors. It sounds logical to me that you will break some of the existing unit tests then.

**Comment by ThomasBrierley** [comment]
I think the issue here is that @pabloahb wants to interpret a vector as a row vector but not a column vector. But column and row vectors are really 1 x n and n x 1 matrices, interpreting a vector as a matrix is ambiguous, so it's better to transpose it into another ambiguous vector which happens to be exactly the same.

@pabloahb:

Lets say vectors are **row** vectors:
```
math.transpose([1, 2, 3]); // [[1], [2], [3]]
```

Lets say vectors are **column** vectors:
```
math.transpose([1, 2, 3]); // [[1, 2, 3]]
```

Their is no reason to assume it should be either one.

**Comment by pabloahb** [comment]
Hi Thomas, thanks for your reply.

The issue here is that Mathjs answers are different from the other CAS systems (Matlab, Octave and my TI V200).

If you use 1D vectors you will get different answers and if you use 2D vectors you can’t use functions like dot and cross product. 

I know that a column vector can contain the same data than a row vector but in algebra, those vectors are totally different (remember that Mathjs is a Computer algebra system CAS).

I already modified the code and now is returning the same answers than Matlab and Octave. I found that the Mathjs code is great, is very well documented and is very easy to understand. The developer is a pro. 

I think that the potential of Mathjs is enormous because you have the possibility to reuse the code made for another CAS like Matlab. There are thousands of engineering applications made for Matlab, Octave, etc. that could be deployed in the Internet and mobile phones if the compatibility issues are fixed.

**Comparison between Octave, Mathjs using 1D vectors and Mathjs using 2D vectors:**

**Test using GNU OCTAVE**
```
 [1,2,3]'
ans =

   1
   2
   3

 cross([1;2;3]',[4,5,6])
ans =

  -3   6  -3
  
 [1,2,3;4,5,6;7,8,9]*[1,2,3]'
ans =

   14
   32
   50

 [1,2,3;4,5,6;7,8,9]*[1,2,3]
error: operator *: nonconformant arguments (op1 is 3x3, op2 is 1x3)
  

```
**Test using Mathjs and 1D vectors**

```
 [1,2,3]'
[1, 2, 3]

 cross([1;2;3]',[4,5,6])
RangeError: Vectors with length 3 expected (Size A = [1, 3], B = [3])

 [1,2,3;4,5,6;7,8,9]*[1,2,3]'
[14, 32, 50]

 [1,2,3;4,5,6;7,8,9]*[1,2,3]
[14, 32, 50]
```

**Test using Mathjs and 2D vectors**

```
 [[1,2,3]]'
[[1], [2], [3]]

 cross([1;2;3]',[[4,5,6]])
RangeError: Vectors with length 3 expected (Size A = [1, 3], B = [1, 3])

 [1,2,3;4,5,6;7,8,9]*[[1,2,3]]'
[[14], [32], [50]]

 [1,2,3;4,5,6;7,8,9]*[[1,2,3]]
RangeError: Dimension mismatch in multiplication. Matrix A columns (3) must match Matrix B rows (1)

```
I will wait for an ACK  and close this issue because the modified code is working very well with my Matlab M-files.

Thanks.

**Comment by josdejong** [comment]
Good to hear you've a working solution now, thanks for the feedback. 

Actually, math.js is already used for example in the built-in [calculator of Ubuntu Touch](https://developer.ubuntu.com/en/community/core-apps/calculator/) :).

**Comment by ThomasBrierley** [comment]
Ah ok I think I get it... sorry I will stop stoking this issue soon as I'm probably out of my depth now.

I looked at Octave (not being very familiar with CAS outside of Mathjs), I suspect that internally column vectors and row vectors are all stored as matrices. Notice how in Octave regardless of whether you've defined a matrix or a column vector they are both printed out in the same way.

So I think in Mathjs does this (correct me if i'm wrong):

``` JavaScript
[1, 2, 3] // -> [1, 2, 3]
[1; 2; 3] // -> [[1], [2], [3]]
```

And Octave probably does something like:
``` JavaScript
[1, 2, 3] // -> [[1, 2, 3]]
[1; 2; 3] // -> [[1], [2], [3]]
```

So with Octave etc, if all vectors are actually stored as a special case matrices then we automatically have all matrix operators available to us (provided the dimensions are compatible). But then it also means that all vector operations are actually special case matrix operations which probably makes them a bit more annoying to implement with extra checks etc.

With Mathjs we have two different data types and have to handle operations between them more explicitly (like with your transpose function) or with coercion... but the problem remains that when converting 1D to 2D it's still ambiguous, the 1D vector is neither a column or row... I know it looks that way syntactically but it's just 1D. I can see how this is a bit confusing when coming from other libraries.

**Comment by balagge** [comment]
Couple of comments:

The terms "row vector" and "column vector" are a bit misleading and confusing, because those do NOT mean vectors, but 2D matrices having a single row or column. I know, because I had to sort out a similar issue recently. Check it:
[Wikipedia](https://en.wikipedia.org/wiki/Row_and_column_vectors)

Therefore I think keeping the explicit distinction between a 1D vector, and a 2D row vector / column vector (i.e. matrices) is a good thing, because actually those are different mathematical objects. Therefore I strongly beleive there should be no implicit conversion.

As an example, multiplication would become confusing and obscure. Currently a 1×n row vector (i.e. matrix) and an n×1 column vector (i.e. matrix) can be multiplied with matrix multiplication (in any order, either giving an n×n matrix or a 1×1 matrix). Two vectors (1D) of length n can be multiplied to give a scalar. 

`A = [[1,2,3]]*[[1],[2],[3]] # A is [[14]]`

`B = [[1],[2],[3]]*[[1,2,3]] # B is  [[1, 2, 3], [2, 4, 6], [3, 6, 9]]`

`C = [1,2,3]*[1,2,3] # C is 14

This is unambiguous, preserves the geometry and corresponds to the correct mathematical definition. With implicit conversions added, some things will become ambiguous pretty soon, I think, and a lot of surprises would follow.

In any case, a 1D vector `v` can easily be converted to a row vector (i.e. matrix) by writing `[v]`, or to a column vector by writing `[v]'`, which makes the conversion explicit, and causes no surprises.

I know that in mathematical thinking some default isomorphisms are treated as quasi-equalities, but it is not necessarily a good idea to implement those in a system, because in real life the contextual info makes things work ("I know I write a vector here, but I mean a 1×n matrix, because otherwise the whole thing makes no sense"), but in the computer that information is not present or hard / impossible to process correctly.

**Comment by pabloahb** [comment]
Hi

I think that the transpose function for 1D vectors must not be supported and must throw an exception like 
`"Only two dimensional matrices are supported."`

In fact, if you look the documentation you will see: 

> Only two dimensional matrices are supported.
> http://mathjs.org/docs/reference/functions/transpose.html

And functions like cross and dot product must support 2D vectors, then you can evaluate an expression like:
`cross([1;2;3]',[[4,5,6]])`
Answer using Mathjs:
`RangeError: Vectors with length 3 expected (Size A = [1, 3], B = [1, 3])`
Answer using Octave
 ` -3   6  -3`

That will solve the compatibility issues with other systems (using 2D vectors).

Thanks

**Comment by pabloahb** [comment]
Hi,
I will close this issue because  I already solve the original problem and the last comments are going off topic.
Thank you for your help.

**Comment by josdejong** [comment]
@pabloahb thanks for your suggestions. I've improved the docs on the function `cross`, and created a new issue to implement support for 2d vectors in the function `cross` (see #713).
