### ISSUE TITLE
Parsing numbers with ending dot

### ISSUE THREAD

**Issue by trojanowski** [josdejong/mathjs#711]
I've noticed that after resolving #707 it's not possible to parse expressions like `1. / 2.` anymore. Would be possible to add a config option to bring back the previous behavior? That expression is correct in JavaScript, Python, Excel and many calculators. I'm using mathjs parser eg. for calculating expressions with significant numbers. There is an important difference between `1000` and `1000.` in that case.

**Comment by ThomasBrierley** [comment]
I think the intention of the fix for #707 was only to change the behaviour of the ambiguous case (where there are no space delimiters). This looks like another bug because clearly the dot belongs to the operand.

**Comment by josdejong** [comment]
In #707 I simply removed support for a dot at the end of a number. Sorry to hear that this notation was actually used, I have never seen this in practice (unlike short notations like `.2` or numbers entered as `2.0` to enforce creating a floating point instead of an integer).

The reason for the fix was ambiguity, since math.js has element wise operators `.*`, `./`, and `.^`. Thinking about it, it should be possible to still support both, the parser should do a look ahead when parsing a digit in a number. I will have a look into it soon.

Please note that a difference between `1000` and `1000.` is artificial: they are both parsed as a number with the exact same value. It can have meaning though for the people reading the expression.

**Comment by trojanowski** [comment]
> Thinking about it, it should be possible to still support both, the parser should do a look ahead when parsing a digit in a number. I will have a look into it soon.

Thank you.

> Please note that a difference between 1000 and 1000. is artificial: they are both parsed as a number with the exact same value. It can have meaning though for the people reading the expression.

Yes. In the case I mentioned before (calculating significant numbers - [working version](https://www.omnicalculator.com/math/sig-fig)) I'm using `mathjs.parse` to build an expression tree and calculate it by myself.
