### ISSUE TITLE
unit convertor error when convert W/K to W/degC

### ISSUE THREAD

**Issue by Nofuture123** [josdejong/mathjs#722]
We plan to  use math.js as one core component in our database. The system has around 200+ units. But we met issue when convert W/K to W/degC
K(C)=273.15+C

`document.write(math.eval('1 W/K to W/degC')+"<br>");`
Result :1 W / degC,  Wrong result
`document.write(math.eval('1 W/degC to W/K')+"<br>");`
Result: 0.0036476381542950944 W / K, Right result

Another sample:
 W/m·K to kcal/(m·h·℃), thermal conductivity unit. 

So hope to get help from here.

**Comment by ericman314** [comment]
This is a result of how units with offset (`degC`, `degF`) are used when combined with other units.

When used alone, the units `degC` and `degF` work just as you'd expect them:

```
25 degC to K   // 298.15 K
298.15 K to degC  // 25 degC
```

But when combined with other units, the offsets are not applied:

```
1 (W / degC) to W / K     // 1 W / K
```

Chemists/engineers/physicists etc. consider `W/K` and `W/degC` to be identical units, whether to use one instead of the other is just convention. So `1 (W / degC) to W / K` should give the result `1 W / K`.

Now, the reason the expression `1 W/degC to W/K` gives the incorrect result `0.0036476381542950944 W / K` is due to the order of operations. First, the unit `1 W` is created, and then divided by the unit `1 degC`, which is _actually_ `274.15 K`, so the expression is interpreted as `(1 W) / (274.15 K)`. If this default behavior was changed it would lead to unexpected results elsewhere, which is why we decided to leave it alone. For this reason we always recommended enclosing the units inside parentheses, or to avoid the problem altogether by using `K` and `R` instead of `degC` and `degF`.

You can find more examples of unexpected behavior related to temperature units [here](http://mathjs.org/docs/datatypes/units.html#calculations).
