### ISSUE TITLE
1 cm is parsed to 10 mm

### ISSUE THREAD

**Issue by thekarel** [josdejong/mathjs#737]
I was wondering why parsing `'1 cm'` is returned as `'10 mm'` and not `'1 cm'`?

It's unexpected if you compare it to some other units:

```
1 mm -> 1 mm
1 cm -> 10 mm
1 m -> 1 m
1 km -> 1 km
```

I'd like to parse `1 cm` to 1 cm, what is the recommended way to do it?

**Comment by ericman314** [comment]
That is interesting. I'll look into it.

**Comment by josdejong** [comment]
If I'm not mistaken the algorithm that searches for the best prefix only uses prefixes mm, m, km (powers of three). Not cm, dm, etc.

**Comment by ericman314** [comment]
If you want to force a certain prefix you can use the `to` keyword: `1 cm to cm`, although this is not ideal.

When math.js chooses the best prefix to display a unit, it tries to make the numeric value between about 0.6 and 500, so you get a sequence like:

```1mm 100mm 500mm 0.6m 1m 10m 100m 500m 0.6km 1km ...```

This feature is designed to help the user so that `0.000000495761 m` becomes a more manageable `495.761 nm`, not to enforce certain prefixes over others.

@josdejong that is correct, although the prefix `c` is a valid prefix it is not included in the search for the best prefix.

If we wanted to change this, we could have `_bestPrefix` ask itself whether the current prefix (`c` in this example) results in a display value between 0.6 and 500 (or perhaps a slightly wider range like 0.1 to 1000), and if so, return the same prefix. Presumably, if the user specified a certain prefix he is OK with keeping the same, within a certain range.

**Comment by josdejong** [comment]
> If we wanted to change this, we could have _bestPrefix ask itself whether the current prefix (c in this example) results in a display value between 0.6 and 500 (or perhaps a slightly wider range like 0.1 to 1000), and if so, return the same prefix. Presumably, if the user specified a certain prefix he is OK with keeping the same, within a certain range.

That could indeed work, adding `cm` to the best prefix search when that was in the input, good idea.

**Comment by ericman314** [comment]
Actually, the original prefix is already included in the search, but sometimes the prefixes near it (`mm`) result in a better match:

```
5 cm -> 50 mm
6 cm -> 6 cm
150 cm -> 150 cm
160 cm -> 1.6 m
```

The easiest and fastest thing I've found is to just accept the original unit without searching if it is close enough:

```
0.09 cm -> 0.9 mm
0.1 cm -> 0.1 cm
1000 cm -> 1000 cm
1001 cm -> 10.01 m
```

This breaks some tests so I will examine if the new results seem acceptable.

**Comment by ericman314** [comment]
I really like the new behavior. There is a higher chance of keeping the user's original units. I've submitted #738.
