### ISSUE TITLE
Unused library functions

### ISSUE THREAD

**Issue by hcvazquez** [josdejong/mathjs#766]
My name is Hernan; with a group of colleagues we are conducting a research about unused code present in dependencies of JavaScript projects. We call this functions, UFF (Unused foreign functions). We found that in most projects there exist a great amount of UFF that are being included in the final bundle. 
 
In the case of mathjs (v 3.5.1) our tools detected approximately 72 unused function in the dependencies. Removing those functions, the size of mathjs bundled could be reduced at least 2% (All tests passed). I replaced the bundled in several projects that use mathjs as loess, dn2a, dext and pullquoter. I’m attaching the reduced version of your project. 
[math(optimized).txt](https://github.com/josdejong/mathjs/files/671126/math.optimized.txt)

 
I’ll be very grateful if you can answer me the following questions:
-Did you were aware of the existence of these unused functions in your projects?
-Do you think that this is a problem? 
-Do you think that can be useful a tool for deal with this kind of problem?

Thanks in advance.

Cheers,

**Comment by josdejong** [comment]
Thanks Hernan. Unused code is in libraries indeed a serious problem. I think that projects using math.js typically only use a small portion, not 98% of it. But it's not so trivial to extract only the used parts. There is a difficulty here that math.js implements all functions for various data types (number, BigNumber, Matrix, Complex, Unit). If you would know beforehand that you want to use only numbers, it would be great if we could automatically strip all matrix related code from the library. That would yield a huge reduction in bundle size.

I see you've stripped these 72 functions from the non-minified version (dist/math.js). Do these 72 functions also exist in the minified version (dist/math.min.js)? If I'm not mistaken the minifier automatically removes dead code.

More and more libraries make use of [tree shaking](https://blog.engineyard.com/2016/tree-shaking) by a bundler. I would love to enable that too for math.js, but that's not so easy because of the aforementioned reasons. You can create [custom bundles](http://mathjs.org/docs/custom_bundling.html), but it's much better when this would be done automatically by our bundlers (like dead code is removed automatically by minifiers).  See #71.
