### ISSUE TITLE
Eval and divide broken on Node.JS? - Tried 7.8.0 and 7.7.3

### ISSUE THREAD

**Issue by SamuelMarks** [josdejong/mathjs#820]
Was debugging some math when I realised it was acting the same as the Node interpreter:
```
> const math = require('mathjs')
undefined
> math.eval('0.3/0.2')
1.4999999999999998
> process.version
'v7.7.3'
```

```
> math.eval('0.3/0.2')
1.4999999999999998
> process.version
'v7.8.0'
>
```

This works though:
```
> math.divide(math.bignumber(0.3), math.bignumber(0.2)).toString()
'1.5'
```

**Comment by CapacitorSet** [comment]
This looks normal: eval will use normal floating-point numbers, whereas bignumber will use numbers of arbitrary size (or at least much larger), therefore having much less rounding error.

**Comment by josdejong** [comment]
This is indeed a "normal" round-off error, you can read more about it here:

http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

**Comment by Snorvarg** [comment]
I have a similar (?) problem, I think. I am using bigmath 'right through', because I need to avoid rounding errrors. But I get a rounding error when using variables containing an expression. 

This triggers it:

  var bigmath = math.create({
    number: 'BigNumber',
    precision: 32
  });

  theExpression = 'a-b';
  theVariables['a'] = bigmath.bignumber('1/3');
  theVariables['b'] = bigmath.bignumber('4/3');
  
  theResult = bigmath.eval(theExpression, theVariables);

theResult now contains -0.999999999999.. instead of the expected -1.

This works though:

  theResult = bigmath.eval('1/3-4/3');

Gives -1.

So, somehow the variables are part of the problem. Sounds like they are evaluated first, on their own, rounded to 0.3333... and 1.33333... respectively, and then the subtraction happens. 

I am considering to make a simple search and replace of the variables, and _then_ give the expression to bigmath, but that seem so wrong. :)

**Comment by SamuelMarks** [comment]
@Snorvarg maybe try adding context to the eval?

**Comment by Snorvarg** [comment]
My mistake! I pre-computed the variables into a decimal number before giving them to math.js. I blame it on immense amounts of code. :P 

@SamuelMarks, I believe I do add context with the line "number: 'BigNumber'," in the call to create(). Or do I misunderstand you? 

Anyway, my code example above might be of use, this line of code solved a problem for me in the past:

    theVariables['a'] = bigmath.bignumber('1/3');

If I assign the variable the value '1/3' without first transforming it into a bignumber, it is considered a 'normal' number, and so is transformed into 0.3333..

**Comment by SamuelMarks** [comment]
Great, glad you resolved it
