### ISSUE TITLE
Calling math.random() freezes IE and node.js

### ISSUE THREAD

**Issue by mahmoud690** [josdejong/mathjs#824]
calling this method causes the IE 11.0 hangs:

`math.ceil(math.random() * 10000000000000);`

**Comment by FSMaxB** [comment]
This not only happens with IE 11.0. I just confirmed it with nodejs 7.7.3.

Interestingly `math.eval('ceil(random() * 10000000000000)` works fine

This can be reproduced by just typing `math.random` or `math.randomInt` and hitting enter. Maybe related to lazyloading, not sure though.

**Comment by mahmoud690** [comment]
Oh! Interseting bug :) 
also your workaround doesn't worked for me! I replaced it with javascript pure lib (Math class)

**Comment by FSMaxB** [comment]
Yes, `math.eval` does in fact not work. It works with `bin/cli.js` though, strange.

@josdejong @morsecodist  This happened somewhere between 3d46e21ee5b120eb81d6b6d029c22b8fcc0a9b19 and 0502921d7e98ec3cd4ba4b87fcb07043e4e921f2 where the RNG was replaced.

**Comment by josdejong** [comment]
I found the underlying cause. Calling `seed-random` caused an infinite loop, because it was being called inside an object getter of a globally defined object (`math.random`), whilst `seed-random` uses all globally defined objects to generate a local entropy.

See https://github.com/ForbesLindesay/seed-random/issues/6 for more details.

**Comment by josdejong** [comment]
Should be fixed in `v3.12.0`
