### ISSUE TITLE
Floor of log fails!!!

### ISSUE THREAD

**Issue by claudiosousa** [josdejong/mathjs#825]
math.floor(math.log(math.bignumber(128), math.bignumber(2))).toNumber()
returns 6 and it should be 7!!!!

**Comment by josdejong** [comment]
Check out the output of the log function:

```js
math.log(math.bignumber(128), math.bignumber(2)).toString()
   // "6.999999999999999999999999999999999999999999999999999999999999999"
```
so floor will indeed round to 6 instead of 7.

When using BigNumbers, you're still using floating point arithmetic, so you can still have round-off errors. They only occur less often. What you can do is round to say 62 digits (a bit less than 64), so the value `6.999...` is rounded into `7.000...`.

See docs: http://mathjs.org/docs/datatypes/bignumbers.html#limitations

**Comment by Yaffle** [comment]
if you are working with integers only, you could use:
```
floor(log(add(bignumber(128), bignumber(0.5)), bignumber(2))).toNumber()
```

**Comment by claudiosousa** [comment]
Thanks for the advice, increasing the precision from 20 to 62 did help.
By the way, with the initial precision of 20, `math.bignumber(2).pow(math.bignumber(K).log(2).floor())` did output 7
