### ISSUE TITLE
Equation gets parsed wrong?

### ISSUE THREAD

**Issue by onkarjit** [josdejong/mathjs#871]
I was playing a bit with MathJS, I found the following issue:

-1^2

gets parsed as:

-(1 ^ 2) = -1

instead of:

-1^2 = 1

I'm not sure if it's intended that way or not. But I thought that I should point that out :D

**Comment by josdejong** [comment]
That's correct: power `^` has a higher precedence than unary minus `-`, so power gets evaluated first. Many math applications calculate it like this. Precedence can be confusing indeed, in case of doubt, always use parenthesis.

**Comment by josdejong** [comment]
See docs for an in-depth description of the operators and their precedence:

http://mathjs.org/docs/expressions/syntax.html

**Comment by onkarjit** [comment]
Is there a way to tweak the precedence to make the unary - and the unary + have higher precedence than the power ^?

**Comment by josdejong** [comment]
No this precedence is not configurable. 

You should be very careful with changing precedence, since people expect certain behavior. All math applications that I know of have a power operator with higher precedence than (unary) minus, there should be a *really* good reason to change this behavior.

An option would be to create your own parser instead, you could use a parser generator like [jison](http://zaach.github.io/jison/) or [peg.js](http://pegjs.org/) for that.
