### ISSUE TITLE
math.eval wont parse variable names with $

### ISSUE THREAD

**Issue by madprops** [josdejong/mathjs#895]
I generate dynamic variables names, $a, $b, $c .... $aa, $ab, $bz  .. etc, like in Excel.

I need to add the $ to the variables because I need to parse them myself for certain functions. 

The problem is when I tried to use math.eval. I tried math.eval('$a', myscope)  I get "Uncaught SyntaxError: Syntax error in part "$a" (char 1)" 

So it seems the parser is not taking into account special characters like $, which are allowed in javascript variable names. 

If I save the variables without the $, then I can run into the problem of having a variable called pi for example, which gets confused with math.pi

Thanks

**Comment by madprops** [comment]
I think I can workaround it by preppending the variables with _ 

But $ should still be taken into account  by the parser I think.

**Comment by ThomasBrierley** [comment]
I can't find it but there was a similar issue a while back. MathJS has an operand character block, it has math safe symbols but does not allow all non operand or syntax characters by default because:

1. They might be used as operators in future and
2. It would cause backward incompatibility

However exposing the block for custom extension was suggested as a good way around this. I don't think that has been done yet.

I also use the $ character for spreadsheet type syntax (for locking cells that are copied), although due to the nature of my application this is a one time operation that I can do before it's run, so I pre-process the expressions with some simple regex then remove the $ before passing to MathJS. That might be an option for you.

**Comment by madprops** [comment]
Yep I could get around it like this --> math.eval(val.replace(/\$/g, '_'), linevars);

Since this seem to be an already discussed issue I'm going to close this.

**Comment by josdejong** [comment]
The concerning discussion referred to by Thomas is here: #715 .

Maybe it's time to simply allow the `$` character. I still haven't found a reason why we would want to turn it in an operator or something.

**Comment by HarrySarson** [comment]
Could mathjs end up supporting monetary units?

**Comment by josdejong** [comment]
That's an interesting one Harry. Being able to use $ for to denote a number of dollars like `$5` would conflict with using the $ as a regular character of a symbol, because in that case `$5` would be interpreted as a symbol just like `x5` or something. 

I think using `$` as dollar sign would be convenient for end users, whilst using `$` as a prefix for a specific type of variable is convenient for programmers (which are used to this pattern from JavaScript or Python for example).

**Comment by madprops** [comment]
What is the point of monetary units though? Would they have some special calculations or would they just be cosmetic? Because it's not hard at all to prepend a '$' to a result.

**Comment by josdejong** [comment]
Allowing `$5` to be interpreted as `5 * dollar` would require special handling in the expression parser, though it's not difficult or so. It's more important whether we *want* this or not. 

Supporting currencies would be a bit less trivial than other units that are already built in, because the exchange rate is dynamic so you need to built in a (universal) way to refresh the exchange rate. 

Just brainstorming here...

**Comment by madprops** [comment]
It would require some service to update the exchange rates, which might be outside the scope of a standalone library, but would certainly make it more powerful/useful. Also currencies might have to be letter based since you have American dollars, Canadian dollars, Mexican dollars etc. So maybe something like 'usd' and other might be used. Or prepend some character to know you're dealing with a currency: $usd, $eur, etc. Just some thoughts.

**Comment by firepick1** [comment]
Parsing currency should be a localization concern, not a math concern. I shy away from Frankenstein packages.

**Comment by Nekomajin42** [comment]
The Opera browser has a built-in currency converter, which uses the exchange rates of European Central Bank. I don't know if the ECB provides an API for that or they use some workaround, but is works fine.

But to stay ontopic, @madprops is right about the symbols. If mathjs will support currencies, it must use `USD`, `EUR` and such, and not the the special characters, so the `$` sign should not be a concern regarding this problem.

**Comment by josdejong** [comment]
Thanks for all the input, I agree. Let's allow `$` as a regular character for symbols, and not reserve it for a special and ambiguous currency notation.

> Parsing currency should be a localization concern, not a math concern. I shy away from Frankenstein packages.

LOL well said. In that regard I think we have to make math.js easier/better customizable (like lodash vs underscore). It's too large for my liking right now, which is not a problem if you can easily cherry pick the parts that you actually need.

Let's indeed not integrate currencies in math.js, it's out of scope. If needed, you can always load currencies in math.js yourself, there is even an example on that: 
http://mathjs.org/examples/browser/currency_conversion.html

**Comment by josdejong** [comment]
Ok then `$` is now supported in the `develop` branch.
