### ISSUE TITLE
Unit's .toString() method doesn't convert 1000 W to 1 kW

### ISSUE THREAD

**Issue by pvoznyuk** [josdejong/mathjs#898]
I expect 1000 W to be converted to 1 kW as well as 1000 kW is converted to 1 MW. However I see that: 
```js
math.unit(1000, 'W').toString() // otputs: 1000 W
math.unit(1000.01, 'W').toString() // otputs: 1 kW
math.unit(999, 'W').toString() // otputs: 999 W
math.unit(1000000, 'W').toString() // otputs: 1 MW
```
Is there a way to convert 1000 W to 1 kW ?

**Comment by ericman314** [comment]
You can use the `to` method:

```js
var c = math.unit('1000 W');        // 1000 W
var d = c.to('kW');                 // 1 kW
```

**Comment by pvoznyuk** [comment]
@ericman314 
sure, I can if I know the value, but usually it is a variable  
```js
math.unit(value, 'W').toString();
```
and I expect it will be converted to W / kW / MW / etc depending in value

**Comment by ericman314** [comment]
math.js tries to format the unit using an appropriate prefix. Currently we have the following behavior:

```
1000000 mW --> 1 kW
1000 W     --> 1000 W
1 kW       --> 1 kW
0.001 MW   --> 1 kW
```

The function chooses a prefix that results in a numeric value between approximately `0.501187...` and `501.187...`. For three of the four cases above, this results in `1 kW`. However, a condition was added in response to a previous discussion (#737), so that when the input value is already close enough (between `0.1` and `1000`) the prefix is not changed.

The details are largely a matter of preference, and we won't be able to please everybody, but if you have a suggestion to improve it, please let us know.

For reference, see the function that chooses the prefix [here](https://github.com/josdejong/mathjs/blob/c8c4bd9b904797b3ad6b4b813b9e7b4f2a414e12/lib/type/unit/Unit.js#L1161-L1208).

**Comment by ThomasBrierley** [comment]
>```
>1000 W     --> 1000 W
>1 kW       --> 1 kW
>```

I thought in engineering notation that in addition to exponents in multiples of 3, the idea was to keep it less than one thousand (3 digits before the decimal)?

Seeing as these are all Si units I can see why one would expect this. It looks like just the boundary condition is wrong.

**Comment by josdejong** [comment]
> I see in #737 the chosen boundaries are between 0.6 and 500, I'm wondering what the thinking behind this choice is?

I'm not sure if this is a choice I've made some day or that this was the work of @ericman314 , but it mostly boils down to heuristics and trying to output a convenient, human friendly format. The boundary at 500 is halfway two prefixes, `600 mm` looks "closer" to being a meter, `400 mm` is closer to being millimeters. Some prefer an output like `0.83201 meter`, others may prefer `832.01 millimeter`. 

I'm fine with further fine-tuning these heuristics if we can make it better overall, the "number between 1 and 999" rule is also nice and simple.

**Comment by ThomasBrierley** [comment]
I guess as ericman says this is a matter of opinion, I see maybe some people prefer to say "half a KW" instead of "500 W".

Just to play devils advocate: Some people might also prefer scientific notation (exactly 1 non zero digit before the decimal), even with SI prefixes, just because of the domain they are working in...

In which case I though maybe these preferences are better solved with `format` which has engineering notation option, however it doesn't seem to be behaving either:

```js
math.unit(1000, 'W').format({notation: 'engineering'}) // "1e+3 W"

math.unit(1000.01, 'W').format({notation: 'engineering'}) // "1.00001e+0 kW"
```

It also shouldn't really be using `e+0` on that last one. I know this is a separate issue really - I should be able to have a dig at this soon because I think I need it to work properly.

**Comment by josdejong** [comment]
Ah, that's interesting indeed. 

The mechanism of units to select the best prefix is separate from formatting numbers. 

@ThomasBrierley would be great if you could dive into it and see if you can come up with some fixes or general improvements.

**Comment by ThomasBrierley** [comment]
Yes will do, I need this feature eventually and i'd rather have it as part of mathjs. I cannot promise to implement it immediately though.

@pvoznyuk would this solve your issue if you were able to explicitly select engineering or scientific notation via the `format` method?

**Comment by ThomasBrierley** [comment]
My interpretation of the behaviour you want is for numbers with SI units to select the matching SI prefix for it's order of magnitude on output... in other words engineering notation.

It should be possible to first fix the engineering notation formater behaviour to output the correct exponent/integer-range, and then for numbers with SI units replace the exponent with the matching prefix. e.g

Using your examples this would preferably result in:
```
1000 W       => 1 kW
1000.01 W  => 1.00001 kW
999 W         => 9.99 hW
1000000 W => 1 MW
```
also
```
10000 kW => 10 MW
0.01 kW      => 1 daW
```

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time. Feel free to reopen if needed.
