### ISSUE TITLE
Creating new instances of Unit impacts unit simplifications in other instances

### ISSUE THREAD

**Issue by AlexanderBeyn** [josdejong/mathjs#903]
While writing a unit test for #901 , I stumbled across an issue where creating an instance of Unit with "km2" causes units in future Unit instances to be simplified differently. http://jsbin.com/voguboyede/edit?html,js,output shows an example:

```
    const print = s => document.write(s + '<br>');
    
    const before = math.eval("1 cm * 1 m");
    print(before.formatUnits() + " " + before.toNumeric());

    km = new math.type.Unit(0.000001, 'km2');

    const after = math.eval("1 cm * 1 m");    
    print(after.formatUnits() + " " + after.toNumeric());
```

outputs
```
m^2 0.01
km2 1e-8
```

In Unit.test.js, "should create square meter correctly" test creates an instance with km2, surfacing this problem.

**Comment by josdejong** [comment]
There is a mechanism that keeps track on the units that you last used in order to make good simplifications, I think it's these heuristics which give this differing output. You can seach the code of `Unit.js` for `currentUnitSystem` to see how it works. So it's not a bug it's a feature :sunglasses: . At least that's the intention.

I can imagine you want predictable outputs, maybe we should only apply these heuristics when config option `predictable` is false.

@ericman314 what do you think?

**Comment by AlexanderBeyn** [comment]
@josdejong In that case, is it a bug if "km2" and "km^2" in the intervening operation produce different results? :)

**Comment by josdejong** [comment]
There is an important difference between these two: `km2` is a defined area unit, whilst `km^2` is a different unit: a length unit raised to the power of two, which happens to have the same base units as an area unit like `km2` or `hectare` or `sqin`. If I'm not mistaken the `currentUnitSystem` heuristics reckons with this, and when you use `km2` (or `hectare` or `sqin` etc) the conclusion is that you probably want to use this unit when formatting.

**Comment by ericman314** [comment]
Indeed. In addition to `UNIT_SYSTEMS.si` and `UNIT_SYSTEMS.us` there is `UNIT_SYSTEMS.auto` which is seeded with the units from `si` and then updated as different units are used. The private variable `currentUnitSystem` is set to reference `UNIT_SYSTEMS.auto` when Unit.js is loaded. But there is no reason we couldn't add a function allowing the user to set a different system. But because of the way Unit.js works this would have to be a global, config-level function. Something like `math.config({unitSystem: 'si'})` or `math.config({unitSystem: 'auto'})`.

**Comment by josdejong** [comment]
That makes sense Eric. 

Since this functionality is only needed for formatting units, would it make sense to pass `unitSystem` as an option to the function `format` instead of making it a global config setting?

**Comment by ericman314** [comment]
Yes, that is a possibility. If the user doesn't pass `unitSystem` to format it could just use the auto unit system.

Searching for usages of `currentUnitSystem`, I also just noticed that when a new unit is defined, it is only added to the current unit system. This is probably because I was lazy and knew that there was not yet any documented way to change the unit system, so it would always remain the default. So if we start messing with changing unit systems we'll have to revisit the `createUnitSingle` function to make sure the new unit is added to each unit system.

**Comment by josdejong** [comment]
Ok, sounds good: extend `format` with an option `{unitSystem: 'auto' | 'si' | 'cgs' | 'us'}`, and do some refactoring.

I also see that `simplifyUnitListLazy` is called in `formatUnits` as well as in `format`, where `format` calls `formatUnits` itself so effectively `simplifyUnitListLazy` is executed twice. That could probably be optimized too.

**Comment by ericman314** [comment]
Right, I don't remember why that was necessary but the simplification is
actually only done once.

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time. Feel free to reopen if needed.
