### ISSUE TITLE
problems mixing number and BigNumber in calculations

### ISSUE THREAD

**Issue by jonathan-saunders-ge** [josdejong/mathjs#935]
The results of some of our calculations are BigNumbers (`a` below) and some are numbers (`b` below). However when we try to mix them in calculations, it fails because sometimes the numbers cannot be converted to BigNumbers ("*Cannot implicitly convert a number with >15 significant digits to BigNumber (value: 1.0999999999999996). Use function bignumber(x) to convert to BigNumber.*").

This sort of means we cannot mix numbers and BigNumbers that we either have to do everything with numbers or do everything with BigNumbers -- neither of those work arounds are very good for us.

```javascript
var math = require('mathjs'); // 3.16.2 (or 2.2.0)

const scope = {
    'a': math.bignumber('0'),
    'b': 3.3 % 2.2 // 1.0999999999999996
};
console.log('scope = ' + JSON.stringify(scope));

// This happens with a simple "math.add(a ,b)" as well, but since we are
// experiencing it with parse-compile-eval, I'm showing it that way.
//const result = math.add(scope.a, scope.b)
const node1 = math.parse('add(a, b)');
const compiledCode = node1.compile();
const result = compiledCode.eval(scope);

console.log('result = ' + JSON.stringify(result));
```

**Comment by jonathan-saunders-ge** [comment]
**Background**: We are using MathJS as a runtime evaluation engine for evaluating expressions which are configured by a user in a separate package. We recently introduced some functions that use BigNumber instead of number so our calculations now have a mix of number types and BigNumber types. Unfortunately, calculations now sometimes fail because the implicit conversion from number to BigNumber won't work.

**Comment by josdejong** [comment]
Thanks for your input. This error is there for a good reason: when mixing bignumbers with numbers which already contains round off errors, you can end up with a false feeling of working with high precision.

If the main reason for using BigNumbers is to get rid of round-off errors, it can be just fine and you may just want to ignore these errors. 

There is no built in configuration to disable this error, maybe we should consider this since you're not the first with this question. 

Some ideas to work around it:
- wrap all functions that can output numbers instead of bignumbers in a function that converts the outcome to bignumber, like
  ```js
  math.import({
    myFunction: function (a, b, c) {
      return math.bignumber(myFunction(a, b, c));
    }
  });
  ```
- redefine the conversion from number to bignumber. To do this, you can use example [/advanced/convert_fraction_to_bignumber.js](https://github.com/josdejong/mathjs/blob/master/examples/advanced/convert_fraction_to_bignumber.js), and instead of adding a new conversion, replace [the original conversion](https://github.com/josdejong/mathjs/blob/master/lib/core/typed.js#L121-L132) from number to bignumber with one that doesn't throw an error. This conversion is currently at index 0, but that may not always be the case, so it's safest to find the index of the conversion which has properties `from: 'number'` and `to: 'BigNumber'` and replace that.

**Comment by jonathan-saunders-ge** [comment]
It's an unfortunate problem because it means we cannot use MathJS as a nice polymorphic math package where we can freely mix numbers, BigNumbers, Fractions, and Complex in arbitrary  calculations.

Although I don't need all the precision, I will just switch everything to use BigNumber (and wrap all my constants in `math.bignumber(123.456)`).

(Since I started on that path, I'll just  finish that way. I did look at modifying the source to fix the conversion, but didn't like modifying the source. I hadn't thought of replacing the conversion function at runtime -- that might have been a better way to go.)

Thanks!

**Comment by josdejong** [comment]
I think the second solution I proposed is *exactly* what you're looking for and there is nothing unfortunate to that solution...

**Comment by jonathan-saunders-ge** [comment]
Perhaps "unfortunate" was an unfortunate choice of words. :-)

So I did this and it's looking good:
```
var foundConversion = false;
math.typed.conversions.forEach(function (conversion) {
    // math.conversions is an array of objects that look like: { from: 'number', to: 'BigNumber', convert: [Function: convert] }
    if (conversion.from === 'number' && conversion.to === 'BigNumber') {
        conversion.convert = function convert_number_BigNumber(x) {
            // convert a number to a BigNumber, even if it has more that 15 digits of precision
            return math.bignumber(x);
        };
        foundConversion = true;
    }
});
if (!foundConversion) {
    throw new Error('Could not find number-BigNumber conversion in MathJS.');
}
```

Thanks!

**Comment by josdejong** [comment]
> Perhaps "unfortunate" was an unfortunate choice of words. :-)

:joy: 

Good to hear you have a working solution!
