### ISSUE TITLE
eval units with scope fails

### ISSUE THREAD

**Issue by XeniaSiskaki** [josdejong/mathjs#941]
I also posted my question on SO but unfortunately I got no answer yet (https://stackoverflow.com/questions/46222341/mathjs-eval-with-scope-units-fails)

I'll explain better what I want to do.

I have a doc that looks like
```
{
   test1: {
        unit: "A",
        value: 1.32
    },
    test2: {
         unit: "A",
         value: 1.643
    }
}
```
and some mappings that look like:
```
{
   a: "test1/test2 * 100",
   b: "test1+test2"
}
```
and what I want to do apart from evaluating the value of those expressions/mappings, find out the unit of the result.

What I did was the following (_ is lodash):
```
// map the doc values to units
const units = _.mapValues(doc, d => d.unit);
// map mappings to evaluated units
const unitsmap = _.mapValues(mappings, m => {
    try {
        const unit = mathjs.eval(m, units);
        return _.isObject(unit) ? unit.toJSON().unit : unit;
    } catch (e) {
        return '';
    }
})
```
This throws a "Cannot convert "A" to a number" error. However, If I do a `math.eval("(1m)/(1s)").toJSON().unit` the unit is `m/s`.

I also tried the units as `1A` but still same error.

Isn't it possible to achieve such behavior?

**Comment by josdejong** [comment]
The reason is that `math.eval(expr, scope)` just takes values in `scope` as they are, it doesn't interpret them as an expression. So in the example 

```js
math.eval("(a)/(b)", {a:"1m", b:"1s"})
```
there `a` is a string `"1m"` and `b` a string `"1s"` (similar to a variable `name` with value `"Joe Smith"`).

To solve this you will first have to evaluate the values of `a` and `b` as expressions, like:
```js
math.eval("(a)/(b)", {a: math.eval("1m"), b: math.eval("1s")})
```
or actually create these values as a Unit:
```js
math.eval("(a)/(b)", {a: math.unit("1m"), b: math.unit("1s")})
```

**Comment by XeniaSiskaki** [comment]
Thanks for the quick response! Makes sense
