### ISSUE TITLE
How to make trig functions evaluate in radians instead of degrees?

### ISSUE THREAD

**Issue by pklavins** [josdejong/mathjs#944]
I need to configure my expression tree parser to evaluate any trig functions it finds in either degrees (the default, so that's easy) or radians, and I was shocked not to find a global rad/deg config option. What's the easiest way to make this work? I can't simply append 'rad' or 'deg' to the end (like `math.eval('34 deg')`) since I'm encountering trig nodes that in turn have other operator nodes as arguments, not simple constants.

**Comment by josdejong** [comment]
Math.js indeed has no configuration for deg/rad. I'm a bit hesitant to implement such a configuration, since it's so easy to make mistakes. I prefer to use explicit units when possible (like `sin(34 deg)`), but this may indeed not be feasible in all cases. I would love to hear more about your use case - maybe we can somehow improve mathjs to accommodate for it.

See this example for an idea on how to add support for deg/rad: http://mathjs.org/examples/browser/angle_configuration.html.html
