### ISSUE TITLE
Improved Error handling

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#96]
Right now math.js throws errors like `TypeError` and `SyntaxError` with a human readable message explaining the cause as good as possible.
- Maybe we shouldn't reuse JavaScripts built in errors like `TypeError` and `SyntaxError`, but instead extend our own error messages, so you have a clear distinction whether an error was thrown by math.js or by JavaScript.
- It would be very useful if the errors do contain extra data on the error which is machine readable instead of just a human readable message. This will allow better feedback to the user on errors by applications using math.js. So instead of just a message `Uncaught SyntaxError: Value expected (char 5)`, we could add a property `data` to the error containing:
  
  ``` js
  {
      'type': 'SyntaxError',
      'char': 5,
      'token': '(',
      'cause': 'Value expected'
  }
  ```
  
  And instead of a message `UnsupportedTypeError: Function factorial(string) not supported` we could add a property `data` like:
  
  ``` js
  {
      'type': 'UnsupportedTypeError',
      'function': 'factorial'
      'arguments': 'string'
  }
  ```
  
  The `toString` function of the error messages should return the original, human readable message.

**Comment by TarVK** [comment]
I'm wondering whether this could be reopened. It seems this was handled to some degree, but in a rather limited capacity. 
The only example I could find of augmented error data is the `char` property for syntax errors.
But for instance when there is a `Units do not match` error, it would be great to specify what the given unit(and its dimension) is, what the expected dimension is, as well as related text ranges for error highlighting. 

I am quite new to MathJS, so maybe there is a way to extract that data, but I've not found such a thing yet.
I really enjoy some advanced math features MathJS has, but it would be quite a shame if I can only provide this level of error feedback to my users. 
I was working on my own parser before deciding to just switch to MathJS since it will ultimately be maintained better than anything I make myself, but I had such features in place and was kind of hoping to find them in MathJS too.

**Comment by m93a** [comment]
Hey Tar,
sorry for being late to reply. You are right, there are still things that can be improved about the error handling. Unit mismatch and parsing errors are a good example. However, I think it would be best to open a new issue for those. Would you mind doing it? :)
