### ISSUE TITLE
Percentage unary operator

### ISSUE THREAD

**Issue by klinki** [josdejong/mathjs#966]
Hello,
would it be possible to add support for % unary operator, which would interpret number as percentage?

Example:
`10%` would result into `0.1`

I know there has been some more complicated request https://github.com/josdejong/mathjs/issues/304 to add percentage operator of previous value. But IMHO that is not really needed.

I think having `%` unary operator which would interpret numbers as percentage would be sufficient and other situations could be handled by multiplication.

**Comment by firepick1** [comment]
Percentages are interesting because, although a scale is involved, so is formatting. This one is tricky since 0.1 === 10% === 1/10
In other words, we have one value with three representations. Moreover, different cultures format percentages differently. https://en.wikipedia.org/wiki/Percent_sign

I'd therefore be inclined to classify percentages as a formatting concern rather than an operator value concern.

**Comment by ThomasBrierley** [comment]
I think this could only make sense as a unit.

`0.1`, `10%` and `1/10` can be though of as three distinct formats of ratio... change factor, percentage and fraction respectively.

As a unit alone this could still be tricky as `%` is already used as a binary operator for modulo, the only way it could be differentiated is by delimiting the binary operator with a space and the unit without... that feels a little dangerous.

**Comment by josdejong** [comment]
In #304 we discussed percentages. So far we don't know of a solution which will not lead to ambiguities with the current modulus operator `%`, but if anyone knows a solution just let us know :)

Let's continue any discussion on percentages in #304 to keep the topic focused.
