### ISSUE TITLE
Bug or Automatic imperial units in demo notepad on mathjs.org?

### ISSUE THREAD

**Issue by librilex** [josdejong/mathjs#970]
On [mathjs.org](mathjs.org), when entering
`4.19 kJ/(kg K) * 10 K`
into the notepad demo the result is
`6.494512989026e+7 inch^2 / s^2`.
I would have favored if the result would be `41.9 kJ/kg` (meaning that the fraction of units would simply be reduced), but I also expected it to be `41900 m^2/s^2` in plain SI units and was rather surprised by the actual result.

Is there a reason/configuration that the unit inch is used in this particular case or is this a bug?

**Comment by ericman314** [comment]
There is. I will try to write up an explanation tonight.

**Comment by ericman314** [comment]
On the first point, you are right that `kJ/kg` would be more appropriate. Unfortunately there is no way for math.js to always know the best units to use to display a result, and the history of what units you used to type an expression are lost in the process of evaluating the expression. To display a result, it first tries to find a matching predefined unit such as W or J, and if there is no matching unit it displays the result in powers of base units.

On the second point, the base units it uses to display a result are chosen from the current unit system. Initially, the unit system is not set so it uses units used in previous input, defaulting to SI in the case that there was no previous input. In the example on mathjs.org, the last operation involving a unit was to convert something to inches. This is why your result returned inch^2/s^2 instead of m^2/s^2.

You can override this behavior using the undocumented function `setUnitSystem()`, but beware that this is in effect a global setting:

```js
math.type.Unit.setUnitSystem('SI');
```

**Comment by librilex** [comment]
Thank you for explaining! I will close this issue, but will try to understand how exactly the units are calculated and what might need to be changed or added so that reduced units as a result would be possible
