### ISSUE TITLE
Is it possible to do partial fraction decomposition with Mathjs?

### ISSUE THREAD

**Issue by q2apro** [josdejong/mathjs#984]
Is it possible to do partial fraction decomposition with Mathjs? And if so, is there any code example to be used?

Goal is to create a widget that can return the solution.

Findings in other websites: 

Examples of calculators:
http://www.emathhelp.net/calculators/algebra-2/partial-fraction-decomposition-calculator/
http://calculator.tutorvista.com/math/605/partial-fractions-calculator.html
http://www.emathhelp.net/calculators/algebra-2/partial-fraction-decomposition-calculator/

Implementation for Sage: https://github.com/stringman45/part_frac
Implementation Mathworks: 
https://se.mathworks.com/matlabcentral/fileexchange/22375-multiple-root-polynomial-solved-by-partial-fraction-expansion
https://se.mathworks.com/help/symbolic/partfrac.html

**Comment by josdejong** [comment]
That's not supported, though the just created function `rationalize` is a related I think. This function is not yet released, you can find it in the develop branch: https://github.com/josdejong/mathjs/blob/develop/lib/function/algebra/rationalize.js

@paulobuchsbaum  what do you think? Could it be interesting/doable to build a solution for partial fraction decomposition?

**Comment by paulobuchsbaum** [comment]
`rationalize` function will do the opposite.  It one enters with any kind of fractions sum, it returns with an unique fraction. 

`Partial Fraction decomposition` is not that simple because it involves generate  fractions sums like

`c1/(x-a1) + c2/(x-a2) + .... + cn/(x-an) `

where  a1,... an are numerical solutions from denominator part.

So one need to use some numerical method to solve the denominator equation and after assemble the equations and solve them for discovering c1, ...,cN.

If there are some complex solutions, the fractions may be of degree greater than 1.

The only application that I can notice it's the partial fraction decomposition is a previous step for integration of general polynomial fraction.

**Comment by josdejong** [comment]
Thanks for your explanation @paulobuchsbaum. Good to know that it will probably not easy to implement. Like integration, which is way harder to implement than derivative.

**Comment by josdejong** [comment]
@q2apro shall we close this issue, or would you like to keep it open as a feature request?
