### ISSUE TITLE
Spaces and underscores are not escaped in TeX representation

### ISSUE THREAD

**Issue by ovk** [josdejong/mathjs#995]
To illustrate the issue, take a look at TeX representation of the following expression:
`foo_bar = "Hello World"`
TeX:
```foo_{bar}:=\mathtt{"Hello World"}```

There are two problems here:
1. The underscore symbol is unescaped and thus makes `bar` to be a subscript of `foo`. It should be escaped as `\_`.
2. Whitespace inside `"Hello World"` string is unescaped and thus ignored. It should be replaced with some of the TeX space commands, for example `\:`.

You can see both issues in action by opening this link https://clcalc.net#eyJjIjpbImZvb19iYXLCoD3CoFwiSGVsbG/CoFdvcmxkXCIiXSwidiI6IjEifQ== and clicking on **T** button on the left panel to open TeX panel. You'll see that `bar` is subscripted and space is ignored.

I think the correct TeX representation for this string should be:
```foo\_bar:=\mathtt{"Hello\:World"}```

**Comment by HarrySarson** [comment]
In the correct representation the space is still unescaped, is that intentional?

**Comment by ovk** [comment]
@HarrySarson oops no, fixed it now.

**Comment by HarrySarson** [comment]
To fix the string escaping https://github.com/josdejong/mathjs/blob/master/lib/type/string.js#L62.

`args[0]` should be replaced by `args[0].replace(' ', ':/')`.

Although newlines my also need escaping.

**Comment by ovk** [comment]
@HarrySarson I think you meant `args[0].replace(' ', '\:')`.
Also a non-breaking space probably needs to be replaced as well, so a better option would be:
```javascript
args[0].replace(/\s/g, '\:')
```
since `\s` works for both regular and non-breakable space (char code 160).

**Comment by FSMaxB** [comment]
The `foo_{bar}` was intentional because it allows variable names with subscripts.

Strings should be properly escaped though, I will have to fix that! @HarrySarson: Note that the `args[0]` in the link you used isn't actually javascript code, but a template string that is expanded [here](https://github.com/josdejong/mathjs/blob/161b8edd8e0385e40e63483afa240418a2096d43/lib/expression/node/FunctionNode.js#L286).

**Comment by ovk** [comment]
@FSMaxB treating one of the characters in MathJS code as a TeX command is very weird. Not only this is inconsistent (why would you only treat `_` as a TeX command but not the other commands) but it also makes it impossible to use an extremely common underscore-separated naming convention for functions and variables. It is even inconsistent with built-in MathJS constants like `SQRT1_2`. If this was intentional, I really think it should be reconsidered.

**Comment by FSMaxB** [comment]
Yes, maybe you are right. I don't fully remember the rationale behind it. I probably just felt like it should behave this way but didn't really think about it.

About escaping strings: Do you know a good method to print strings as is in a LaTeX formula? Because currently only spaces would be fixed with this string replacement, but none of the other characters because there is absolutely no escaping going on at all.

**Comment by josdejong** [comment]
Your point of inconsistency in handling _some_ TeX commands and others not makes sense Oleg, sounds good simply escape everything (spaces, underscores, others?) in toTex function . 

@FSMaxB since there is an option to hook into the toTex function and override it, I think we already have a a way to do special things like create a variable name with subscripts, right?

**Comment by FSMaxB** [comment]
>  Since there is an option to hook into the toTex function and override it, I think we already have a a way to do special things like create a variable name with subscripts, right?

Yes, this can be achieved by overriding the `toTex` handler of `ConstantNode`, `AssignmentNode` and `FunctionAssignmentNode`. But this is a quite intrusive and tedious thing to do!

Would it be ok to add a new dependency (something like https://github.com/dangmai/escape-latex) for handling the `toTex` of strings?

**Comment by josdejong** [comment]
> Would it be ok to add a new dependency (something like https://github.com/dangmai/escape-latex) for handling the toTex of strings?

Yes that makes sense. It's not much code and if we would implement it ourselves we would probably end up with about the same amount of code (but reinventing the wheel...)

**Comment by FSMaxB** [comment]
I'll work on it then. I can give no time estimate at this point though.

**Comment by josdejong** [comment]
:+1: thanks beforehand. Take it easy, it's holidays ;)

**Comment by josdejong** [comment]
Fixed via #995 (fix is not yet released)

**Comment by harrysarson** [comment]
This was merged into master for version 4 :)

**Comment by josdejong** [comment]
thanks Harry :+1:

**Comment by dpnova** [comment]
We're about to try and get back subs/super in toTex (engineers need it) is there an established way to override toTex?
